CREATE TABLE public.abc_classification_runs (
    id integer NOT NULL,
    run_date timestamp with time zone NOT NULL,
    total_parts integer NOT NULL,
    class_acount integer NOT NULL,
    class_bcount integer NOT NULL,
    class_ccount integer NOT NULL,
    class_athreshold_percent numeric(5,2) NOT NULL,
    class_bthreshold_percent numeric(5,2) NOT NULL,
    total_annual_usage_value numeric(18,4) NOT NULL,
    lookback_months integer NOT NULL
);

ALTER TABLE public.abc_classification_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.abc_classification_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.abc_classification_runs
    ADD CONSTRAINT pk_abc_classification_runs PRIMARY KEY (id);
