CREATE TABLE public.abc_classifications (
    id integer NOT NULL,
    part_id integer NOT NULL,
    classification integer NOT NULL,
    annual_usage_value numeric(18,4) NOT NULL,
    annual_demand_quantity numeric(18,4) NOT NULL,
    unit_cost numeric(18,4) NOT NULL,
    cumulative_percent numeric(7,4) NOT NULL,
    rank integer NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    run_id integer NOT NULL
);

ALTER TABLE public.abc_classifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.abc_classifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.abc_classifications
    ADD CONSTRAINT pk_abc_classifications PRIMARY KEY (id);

ALTER TABLE ONLY public.abc_classifications
    ADD CONSTRAINT fk_abc_classifications__abc_classification_runs_run_id FOREIGN KEY (run_id) REFERENCES public.abc_classification_runs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.abc_classifications
    ADD CONSTRAINT fk_abc_classifications__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;
