CREATE TABLE public.accounts (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(2000),
    industry character varying(100),
    website character varying(500),
    phone character varying(50),
    address character varying(200),
    city character varying(100),
    state character varying(50),
    postal_code character varying(20),
    country character varying(50),
    size_bracket character varying(50),
    owner_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT pk_accounts PRIMARY KEY (id);
