CREATE TABLE public.account_contacts (
    id integer NOT NULL,
    account_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(200),
    phone character varying(50),
    role character varying(50),
    is_primary boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.account_contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.account_contacts
    ADD CONSTRAINT pk_account_contacts PRIMARY KEY (id);

ALTER TABLE ONLY public.account_contacts
    ADD CONSTRAINT fk_account_contacts_accounts_account_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
