CREATE TABLE public.acct_bank_statement_imports (
    id integer NOT NULL,
    book_id integer NOT NULL,
    cash_gl_account_id integer NOT NULL,
    file_name character varying(260) NOT NULL,
    format character varying(10) NOT NULL,
    imported_by_user_id integer NOT NULL,
    line_count integer NOT NULL,
    duplicate_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_bank_statement_imports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_bank_statement_imports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_bank_statement_imports
    ADD CONSTRAINT pk_acct_bank_statement_imports PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_bank_statement_imports
    ADD CONSTRAINT fk_acct_stmt_imports_cash_account FOREIGN KEY (cash_gl_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE RESTRICT;
