CREATE TABLE public.acct_inventory_valuations (
    id integer NOT NULL,
    book_id integer NOT NULL,
    part_id integer NOT NULL,
    on_hand_quantity numeric(18,4) NOT NULL,
    average_unit_cost numeric(18,6) NOT NULL,
    total_value numeric(18,2) NOT NULL,
    version bigint DEFAULT 1 NOT NULL
);

ALTER TABLE public.acct_inventory_valuations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_inventory_valuations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_inventory_valuations
    ADD CONSTRAINT pk_acct_inventory_valuations PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_inventory_valuations
    ADD CONSTRAINT fk_acct_inventory_valuations_part FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
