CREATE TABLE public.acct_number_sequences (
    id integer NOT NULL,
    book_id integer NOT NULL,
    fiscal_year_id integer NOT NULL,
    next_value bigint NOT NULL
);

ALTER TABLE public.acct_number_sequences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_number_sequences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_number_sequences
    ADD CONSTRAINT pk_acct_number_sequences PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_number_sequences
    ADD CONSTRAINT fk_acct_number_sequences_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_number_sequences
    ADD CONSTRAINT fk_acct_number_sequences_year FOREIGN KEY (fiscal_year_id) REFERENCES public.acct_fiscal_years(id) ON DELETE RESTRICT;
