CREATE TABLE public.acct_qbo_export_logs (
    id integer NOT NULL,
    book_id integer NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    qbo_doc_id character varying(50) NOT NULL,
    total_debit numeric(18,2) NOT NULL,
    pushed_at timestamp with time zone NOT NULL,
    pushed_by integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_qbo_export_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_qbo_export_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_qbo_export_logs
    ADD CONSTRAINT pk_acct_qbo_export_logs PRIMARY KEY (id);
