CREATE TABLE public.acct_journal_entries (
    id bigint NOT NULL,
    book_id integer NOT NULL,
    entry_number bigint NOT NULL,
    entry_date date NOT NULL,
    fiscal_period_id integer NOT NULL,
    fiscal_year_id integer NOT NULL,
    source character varying(20) NOT NULL,
    source_type character varying(100),
    source_id bigint,
    idempotency_key character varying(200),
    currency_id integer NOT NULL,
    memo character varying(2000),
    status character varying(20) NOT NULL,
    auto_reverse_next_period boolean NOT NULL,
    reversal_of_entry_id bigint,
    reversed_by_entry_id bigint,
    approved_by integer,
    posted_by integer,
    posted_at timestamp with time zone
);

ALTER TABLE public.acct_journal_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_journal_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_journal_entries
    ADD CONSTRAINT pk_acct_journal_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_journal_entries
    ADD CONSTRAINT fk_acct_journal_entries_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_entries
    ADD CONSTRAINT fk_acct_journal_entries_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_entries
    ADD CONSTRAINT fk_acct_journal_entries_period FOREIGN KEY (fiscal_period_id) REFERENCES public.acct_fiscal_periods(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_entries
    ADD CONSTRAINT fk_acct_journal_entries_reversal_of FOREIGN KEY (reversal_of_entry_id) REFERENCES public.acct_journal_entries(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_entries
    ADD CONSTRAINT fk_acct_journal_entries_reversed_by FOREIGN KEY (reversed_by_entry_id) REFERENCES public.acct_journal_entries(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_entries
    ADD CONSTRAINT fk_acct_journal_entries_year FOREIGN KEY (fiscal_year_id) REFERENCES public.acct_fiscal_years(id) ON DELETE RESTRICT;
