CREATE TABLE public.acct_pay_runs (
    id integer NOT NULL,
    book_id integer NOT NULL,
    pay_date date NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    gross_wages numeric(18,2) NOT NULL,
    employee_tax_withheld numeric(18,2) NOT NULL,
    employer_tax numeric(18,2) NOT NULL,
    status character varying(20) NOT NULL,
    journal_entry_id bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_pay_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_pay_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_pay_runs
    ADD CONSTRAINT pk_acct_pay_runs PRIMARY KEY (id);
