CREATE TABLE public.acct_journal_templates (
    id integer NOT NULL,
    book_id integer NOT NULL,
    name character varying(150) NOT NULL,
    description character varying(1000),
    source character varying(20) NOT NULL,
    memo character varying(500),
    auto_reverse_next_period boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_journal_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_journal_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_journal_templates
    ADD CONSTRAINT pk_acct_journal_templates PRIMARY KEY (id);
