CREATE TABLE public.acct_fiscal_periods (
    id integer NOT NULL,
    fiscal_year_id integer NOT NULL,
    period_number integer NOT NULL,
    name character varying(100) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status character varying(20) NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    closed_by_user_id integer,
    closed_at timestamp with time zone,
    reopened_by_user_id integer,
    reopened_at timestamp with time zone
);

ALTER TABLE public.acct_fiscal_periods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_fiscal_periods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_fiscal_periods
    ADD CONSTRAINT pk_acct_fiscal_periods PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_fiscal_periods
    ADD CONSTRAINT fk_acct_fiscal_periods_year FOREIGN KEY (fiscal_year_id) REFERENCES public.acct_fiscal_years(id) ON DELETE RESTRICT;
