CREATE TABLE public.acct_ar_open_items (
    id integer NOT NULL,
    book_id integer NOT NULL,
    customer_id integer NOT NULL,
    source_type character varying(50) NOT NULL,
    source_id integer NOT NULL,
    document_number character varying(100) NOT NULL,
    document_date timestamp with time zone NOT NULL,
    due_date timestamp with time zone NOT NULL,
    currency_id integer NOT NULL,
    fx_rate numeric(18,8) NOT NULL,
    original_txn_amount numeric(18,4) NOT NULL,
    original_functional_amount numeric(18,4) NOT NULL,
    applied_txn_amount numeric(18,4) NOT NULL,
    applied_functional_amount numeric(18,4) NOT NULL,
    status character varying(20) NOT NULL
);

ALTER TABLE public.acct_ar_open_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_ar_open_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_ar_open_items
    ADD CONSTRAINT pk_acct_ar_open_items PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_ar_open_items
    ADD CONSTRAINT fk_acct_ar_open_items_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_ar_open_items
    ADD CONSTRAINT fk_acct_ar_open_items_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;
