CREATE TABLE public.acct_gl_accounts (
    id integer NOT NULL,
    book_id integer NOT NULL,
    account_number character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    account_type character varying(20) NOT NULL,
    normal_balance character varying(10) NOT NULL,
    parent_account_id integer,
    is_control_account boolean NOT NULL,
    control_type character varying(20),
    is_postable boolean NOT NULL,
    is_active boolean NOT NULL,
    requires_job boolean DEFAULT false NOT NULL,
    requires_cost_center boolean DEFAULT false NOT NULL,
    cash_flow_category character varying(20),
    description character varying(1000)
);

ALTER TABLE public.acct_gl_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_gl_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_gl_accounts
    ADD CONSTRAINT pk_acct_gl_accounts PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_gl_accounts
    ADD CONSTRAINT fk_acct_gl_accounts_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_gl_accounts
    ADD CONSTRAINT fk_acct_gl_accounts_parent FOREIGN KEY (parent_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE RESTRICT;
