CREATE TABLE public.acct_ledger_balances (
    id integer NOT NULL,
    book_id integer NOT NULL,
    gl_account_id integer NOT NULL,
    fiscal_period_id integer NOT NULL,
    currency_id integer NOT NULL,
    debit_total numeric(18,4) NOT NULL,
    credit_total numeric(18,4) NOT NULL
);

ALTER TABLE public.acct_ledger_balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_ledger_balances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_ledger_balances
    ADD CONSTRAINT pk_acct_ledger_balances PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_ledger_balances
    ADD CONSTRAINT fk_acct_ledger_balances_account FOREIGN KEY (gl_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_ledger_balances
    ADD CONSTRAINT fk_acct_ledger_balances_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_ledger_balances
    ADD CONSTRAINT fk_acct_ledger_balances_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_ledger_balances
    ADD CONSTRAINT fk_acct_ledger_balances_period FOREIGN KEY (fiscal_period_id) REFERENCES public.acct_fiscal_periods(id) ON DELETE RESTRICT;
