CREATE TABLE public.acct_journal_lines (
    id bigint NOT NULL,
    journal_entry_id bigint NOT NULL,
    book_id integer NOT NULL,
    line_number integer NOT NULL,
    gl_account_id integer NOT NULL,
    job_id integer,
    cost_center_id integer,
    debit numeric(18,4) NOT NULL,
    credit numeric(18,4) NOT NULL,
    currency_id integer NOT NULL,
    txn_amount numeric(18,4) NOT NULL,
    functional_amount numeric(18,4) NOT NULL,
    fx_rate numeric(18,8) NOT NULL,
    subledger_party_type character varying(20),
    subledger_party_id integer,
    description character varying(500),
    CONSTRAINT ck_acct_journal_lines_debit_xor_credit CHECK (((debit = (0)::numeric) <> (credit = (0)::numeric)))
);

ALTER TABLE public.acct_journal_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_journal_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_journal_lines
    ADD CONSTRAINT pk_acct_journal_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_journal_lines
    ADD CONSTRAINT fk_acct_journal_lines_account FOREIGN KEY (gl_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_lines
    ADD CONSTRAINT fk_acct_journal_lines_cost_center FOREIGN KEY (cost_center_id) REFERENCES public.acct_cost_centers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_lines
    ADD CONSTRAINT fk_acct_journal_lines_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_lines
    ADD CONSTRAINT fk_acct_journal_lines_entry FOREIGN KEY (journal_entry_id) REFERENCES public.acct_journal_entries(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_journal_lines
    ADD CONSTRAINT fk_acct_journal_lines_job FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;
