CREATE TABLE public.acct_pay_run_lines (
    id integer NOT NULL,
    pay_run_id integer NOT NULL,
    employee_name character varying(120) NOT NULL,
    gross_pay numeric(18,2) NOT NULL,
    federal_withholding numeric(18,2) NOT NULL,
    state_withholding numeric(18,2) NOT NULL,
    fica_employee numeric(18,2) NOT NULL,
    other_deductions numeric(18,2) NOT NULL,
    employer_tax numeric(18,2) NOT NULL,
    net_pay numeric(18,2) NOT NULL
);

ALTER TABLE public.acct_pay_run_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_pay_run_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_pay_run_lines
    ADD CONSTRAINT pk_acct_pay_run_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_pay_run_lines
    ADD CONSTRAINT fk_acct_pay_run_lines_run FOREIGN KEY (pay_run_id) REFERENCES public.acct_pay_runs(id) ON DELETE CASCADE;
