CREATE TABLE public.acct_journal_template_lines (
    id integer NOT NULL,
    journal_template_id integer NOT NULL,
    line_number integer NOT NULL,
    account_determination_key character varying(60),
    gl_account_id integer,
    debit numeric(18,2) NOT NULL,
    credit numeric(18,2) NOT NULL,
    description character varying(500),
    party_type character varying(20),
    party_id integer
);

ALTER TABLE public.acct_journal_template_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_journal_template_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_journal_template_lines
    ADD CONSTRAINT pk_acct_journal_template_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_journal_template_lines
    ADD CONSTRAINT fk_acct_journal_template_lines_template FOREIGN KEY (journal_template_id) REFERENCES public.acct_journal_templates(id) ON DELETE CASCADE;
