CREATE TABLE public.acct_bank_reconciliation_items (
    id integer NOT NULL,
    bank_reconciliation_id integer NOT NULL,
    journal_line_id bigint NOT NULL,
    is_cleared boolean NOT NULL
);

ALTER TABLE public.acct_bank_reconciliation_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_bank_reconciliation_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_bank_reconciliation_items
    ADD CONSTRAINT pk_acct_bank_reconciliation_items PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_bank_reconciliation_items
    ADD CONSTRAINT fk_acct_bank_rec_items_line FOREIGN KEY (journal_line_id) REFERENCES public.acct_journal_lines(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_bank_reconciliation_items
    ADD CONSTRAINT fk_acct_bank_rec_items_rec FOREIGN KEY (bank_reconciliation_id) REFERENCES public.acct_bank_reconciliations(id) ON DELETE CASCADE;
