CREATE TABLE public.acct_books (
    id integer NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    functional_currency_id integer NOT NULL,
    reporting_time_zone character varying(64) NOT NULL,
    rounding_tolerance numeric(18,4) NOT NULL,
    maker_checker_threshold numeric,
    default_costing_method character varying(20) DEFAULT 'Standard'::character varying NOT NULL,
    revenue_recognition_method character varying(30) DEFAULT 'PointInTime'::character varying NOT NULL,
    is_active boolean NOT NULL
);

ALTER TABLE public.acct_books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_books
    ADD CONSTRAINT pk_acct_books PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_books
    ADD CONSTRAINT fk_acct_books_currency FOREIGN KEY (functional_currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;
