CREATE TABLE public.acct_cost_centers (
    id integer NOT NULL,
    book_id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    parent_id integer,
    is_active boolean NOT NULL
);

ALTER TABLE public.acct_cost_centers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_cost_centers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_cost_centers
    ADD CONSTRAINT pk_acct_cost_centers PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_cost_centers
    ADD CONSTRAINT fk_acct_cost_centers_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_cost_centers
    ADD CONSTRAINT fk_acct_cost_centers_parent FOREIGN KEY (parent_id) REFERENCES public.acct_cost_centers(id) ON DELETE RESTRICT;
