CREATE TABLE public.acct_qbo_account_maps (
    id integer NOT NULL,
    gl_account_id integer NOT NULL,
    qbo_account_id character varying(50) NOT NULL,
    qbo_account_name character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_qbo_account_maps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_qbo_account_maps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_qbo_account_maps
    ADD CONSTRAINT pk_acct_qbo_account_maps PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_qbo_account_maps
    ADD CONSTRAINT fk_acct_qbo_account_maps_gl_account FOREIGN KEY (gl_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE CASCADE;
