CREATE TABLE public.acct_budgets (
    id integer NOT NULL,
    book_id integer NOT NULL,
    gl_account_id integer NOT NULL,
    fiscal_year integer NOT NULL,
    period_month integer,
    amount numeric(18,2) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_budgets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_budgets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_budgets
    ADD CONSTRAINT pk_acct_budgets PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_budgets
    ADD CONSTRAINT fk_acct_budgets_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_budgets
    ADD CONSTRAINT fk_acct_budgets_gl_account FOREIGN KEY (gl_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE RESTRICT;
