CREATE TABLE public.acct_bank_reconciliations (
    id integer NOT NULL,
    book_id integer NOT NULL,
    cash_gl_account_id integer NOT NULL,
    statement_date date NOT NULL,
    statement_ending_balance numeric(18,2) NOT NULL,
    status character varying(20) NOT NULL,
    finalized_at timestamp with time zone,
    version bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_bank_reconciliations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_bank_reconciliations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_bank_reconciliations
    ADD CONSTRAINT pk_acct_bank_reconciliations PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_bank_reconciliations
    ADD CONSTRAINT fk_acct_bank_recs_cash_account FOREIGN KEY (cash_gl_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE RESTRICT;
