CREATE TABLE public.acct_account_determination_rules (
    id integer NOT NULL,
    book_id integer NOT NULL,
    key character varying(50) NOT NULL,
    gl_account_id integer NOT NULL,
    item_id integer,
    category_id integer,
    valuation_class_id integer
);

ALTER TABLE public.acct_account_determination_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_account_determination_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_account_determination_rules
    ADD CONSTRAINT pk_acct_account_determination_rules PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_account_determination_rules
    ADD CONSTRAINT fk_acct_determination_account FOREIGN KEY (gl_account_id) REFERENCES public.acct_gl_accounts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.acct_account_determination_rules
    ADD CONSTRAINT fk_acct_determination_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;
