CREATE TABLE public.acct_bank_statement_lines (
    id integer NOT NULL,
    bank_statement_import_id integer NOT NULL,
    cash_gl_account_id integer NOT NULL,
    posted_date date NOT NULL,
    amount numeric(18,2) NOT NULL,
    description character varying(256) NOT NULL,
    fitid character varying(128) NOT NULL,
    match_status character varying(20) NOT NULL,
    matched_journal_line_id bigint,
    confirmed_by_user_id integer,
    confirmed_at timestamp with time zone
);

ALTER TABLE public.acct_bank_statement_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_bank_statement_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_bank_statement_lines
    ADD CONSTRAINT pk_acct_bank_statement_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_bank_statement_lines
    ADD CONSTRAINT fk_acct_stmt_lines_import FOREIGN KEY (bank_statement_import_id) REFERENCES public.acct_bank_statement_imports(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.acct_bank_statement_lines
    ADD CONSTRAINT fk_acct_stmt_lines_journal_line FOREIGN KEY (matched_journal_line_id) REFERENCES public.acct_journal_lines(id) ON DELETE SET NULL;
