CREATE TABLE public.acct_fiscal_years (
    id integer NOT NULL,
    book_id integer NOT NULL,
    name character varying(100) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status character varying(20) NOT NULL,
    closed_by_user_id integer,
    closed_at timestamp with time zone
);

ALTER TABLE public.acct_fiscal_years ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_fiscal_years_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_fiscal_years
    ADD CONSTRAINT pk_acct_fiscal_years PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_fiscal_years
    ADD CONSTRAINT fk_acct_fiscal_years_book FOREIGN KEY (book_id) REFERENCES public.acct_books(id) ON DELETE RESTRICT;
