CREATE TABLE public.acct_fixed_assets (
    id integer NOT NULL,
    book_id integer NOT NULL,
    name character varying(200) NOT NULL,
    asset_tag character varying(60),
    cost numeric(18,2) NOT NULL,
    salvage_value numeric(18,2) NOT NULL,
    in_service_date date NOT NULL,
    useful_life_months integer NOT NULL,
    method character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    useful_life_units numeric(18,2),
    linked_asset_id integer,
    last_depreciated_units numeric(18,2) DEFAULT 0.0 NOT NULL,
    asset_gl_account_id integer NOT NULL,
    accumulated_depreciation_gl_account_id integer NOT NULL,
    depreciation_expense_gl_account_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.acct_fixed_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_fixed_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_fixed_assets
    ADD CONSTRAINT pk_acct_fixed_assets PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_fixed_assets
    ADD CONSTRAINT fk_acct_fixed_assets_linked_asset FOREIGN KEY (linked_asset_id) REFERENCES public.assets(id) ON DELETE SET NULL;
