CREATE TABLE public.acct_depreciation_entries (
    id integer NOT NULL,
    fixed_asset_id integer NOT NULL,
    period_month date NOT NULL,
    amount numeric(18,2) NOT NULL,
    journal_entry_id bigint NOT NULL
);

ALTER TABLE public.acct_depreciation_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acct_depreciation_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acct_depreciation_entries
    ADD CONSTRAINT pk_acct_depreciation_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.acct_depreciation_entries
    ADD CONSTRAINT fk_acct_depreciation_entries_asset FOREIGN KEY (fixed_asset_id) REFERENCES public.acct_fixed_assets(id) ON DELETE CASCADE;
