CREATE TABLE public.activity_logs (
    id integer NOT NULL,
    entity_type character varying(100) NOT NULL,
    entity_id integer NOT NULL,
    user_id integer,
    action character varying(100) NOT NULL,
    description text NOT NULL,
    field_name character varying(200),
    old_value text,
    new_value text,
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE public.activity_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT pk_activity_logs PRIMARY KEY (id);
