CREATE TABLE public.ai_assistants (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500) NOT NULL,
    icon character varying(50) NOT NULL,
    color character varying(20) NOT NULL,
    category character varying(50) NOT NULL,
    system_prompt character varying(50000) NOT NULL,
    allowed_entity_types character varying(2000) NOT NULL,
    starter_questions character varying(5000) NOT NULL,
    is_active boolean NOT NULL,
    is_built_in boolean NOT NULL,
    sort_order integer NOT NULL,
    temperature double precision NOT NULL,
    max_context_chunks integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.ai_assistants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_assistants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ai_assistants
    ADD CONSTRAINT pk_ai_assistants PRIMARY KEY (id);
