CREATE TABLE public.ai_provenances (
    id integer NOT NULL,
    entity_type character varying(60) NOT NULL,
    entity_id integer NOT NULL,
    model character varying(120),
    notes character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.ai_provenances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_provenances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ai_provenances
    ADD CONSTRAINT pk_ai_provenances PRIMARY KEY (id);
