CREATE TABLE public.andon_alerts (
    id integer NOT NULL,
    work_center_id integer NOT NULL,
    type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    requested_by_id integer NOT NULL,
    requested_at timestamp with time zone NOT NULL,
    acknowledged_at timestamp with time zone,
    acknowledged_by_id integer,
    resolved_at timestamp with time zone,
    resolved_by_id integer,
    notes character varying(2000),
    job_id integer
);

ALTER TABLE public.andon_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.andon_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.andon_alerts
    ADD CONSTRAINT pk_andon_alerts PRIMARY KEY (id);

ALTER TABLE ONLY public.andon_alerts
    ADD CONSTRAINT fk_andon_alerts__jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.andon_alerts
    ADD CONSTRAINT fk_andon_alerts__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE RESTRICT;
