CREATE TABLE public.announcements (
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    content character varying(5000) NOT NULL,
    severity character varying(20) NOT NULL,
    scope character varying(20) NOT NULL,
    requires_acknowledgment boolean NOT NULL,
    expires_at timestamp with time zone,
    is_system_generated boolean NOT NULL,
    system_source character varying(50),
    template_id integer,
    department_id integer,
    created_by_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT pk_announcements PRIMARY KEY (id);

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fk_announcements__announcement_templates_template_id FOREIGN KEY (template_id) REFERENCES public.announcement_templates(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fk_announcements__asp_net_users_created_by_id FOREIGN KEY (created_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;
