CREATE TABLE public.announcement_acknowledgments (
    id integer NOT NULL,
    announcement_id integer NOT NULL,
    user_id integer NOT NULL,
    acknowledged_at timestamp with time zone NOT NULL
);

ALTER TABLE public.announcement_acknowledgments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_acknowledgments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.announcement_acknowledgments
    ADD CONSTRAINT pk_announcement_acknowledgments PRIMARY KEY (id);

ALTER TABLE ONLY public.announcement_acknowledgments
    ADD CONSTRAINT fk_announcement_acknowledgments__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.announcement_acknowledgments
    ADD CONSTRAINT fk_announcement_acknowledgments_announcements_announcement_id FOREIGN KEY (announcement_id) REFERENCES public.announcements(id) ON DELETE CASCADE;
