CREATE TABLE public.announcement_templates (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    content character varying(5000) NOT NULL,
    default_severity character varying(20) NOT NULL,
    default_scope character varying(20) NOT NULL,
    default_requires_acknowledgment boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.announcement_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.announcement_templates
    ADD CONSTRAINT pk_announcement_templates PRIMARY KEY (id);
