CREATE TABLE public.approval_steps (
    id integer NOT NULL,
    workflow_id integer NOT NULL,
    step_number integer NOT NULL,
    name character varying(200) NOT NULL,
    approver_type character varying(20) NOT NULL,
    approver_user_id integer,
    approver_role character varying(50),
    use_direct_manager boolean NOT NULL,
    auto_approve_below numeric(18,2),
    escalation_hours integer,
    require_comments boolean NOT NULL,
    allow_delegation boolean NOT NULL
);

ALTER TABLE public.approval_steps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.approval_steps
    ADD CONSTRAINT pk_approval_steps PRIMARY KEY (id);

ALTER TABLE ONLY public.approval_steps
    ADD CONSTRAINT fk_approval_steps__approval_workflows_workflow_id FOREIGN KEY (workflow_id) REFERENCES public.approval_workflows(id) ON DELETE CASCADE;
