CREATE TABLE public.approval_decisions (
    id integer NOT NULL,
    request_id integer NOT NULL,
    step_number integer NOT NULL,
    decided_by_id integer NOT NULL,
    decision character varying(20) NOT NULL,
    comments character varying(1000),
    decided_at timestamp with time zone NOT NULL,
    delegated_to_user_id integer
);

ALTER TABLE public.approval_decisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_decisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.approval_decisions
    ADD CONSTRAINT pk_approval_decisions PRIMARY KEY (id);

ALTER TABLE ONLY public.approval_decisions
    ADD CONSTRAINT fk_approval_decisions__approval_requests_request_id FOREIGN KEY (request_id) REFERENCES public.approval_requests(id) ON DELETE CASCADE;
