CREATE TABLE public.approval_requests (
    id integer NOT NULL,
    workflow_id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    current_step_number integer NOT NULL,
    status character varying(20) NOT NULL,
    requested_by_id integer NOT NULL,
    requested_at timestamp with time zone NOT NULL,
    amount numeric(18,2),
    entity_summary character varying(500),
    completed_at timestamp with time zone,
    escalated_at timestamp with time zone
);

ALTER TABLE public.approval_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.approval_requests
    ADD CONSTRAINT pk_approval_requests PRIMARY KEY (id);

ALTER TABLE ONLY public.approval_requests
    ADD CONSTRAINT fk_approval_requests__approval_workflows_workflow_id FOREIGN KEY (workflow_id) REFERENCES public.approval_workflows(id) ON DELETE RESTRICT;
