CREATE TABLE public.approval_workflows (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    entity_type character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    description character varying(500),
    activation_conditions_json text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.approval_workflows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_workflows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.approval_workflows
    ADD CONSTRAINT pk_approval_workflows PRIMARY KEY (id);
