CREATE TABLE public.asp_net_users (
    id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    initials text,
    avatar_color text,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    setup_token text,
    setup_token_expires_at timestamp with time zone,
    pin_hash text,
    employee_barcode text,
    team_id integer,
    work_location_id integer,
    accounting_employee_id text,
    google_id text,
    microsoft_id text,
    oidc_subject_id text,
    oidc_provider text,
    mfa_enabled boolean DEFAULT false NOT NULL,
    mfa_enforced_by_policy boolean DEFAULT false NOT NULL,
    mfa_enabled_at timestamp with time zone,
    mfa_recovery_codes_remaining integer DEFAULT 0 NOT NULL,
    role_template_id integer,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL
);

ALTER TABLE public.asp_net_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asp_net_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.asp_net_users
    ADD CONSTRAINT pk_asp_net_users PRIMARY KEY (id);

ALTER TABLE ONLY public.asp_net_users
    ADD CONSTRAINT fk_asp_net_users_company_locations_work_location_id FOREIGN KEY (work_location_id) REFERENCES public.company_locations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.asp_net_users
    ADD CONSTRAINT fk_asp_net_users_role_templates_role_template_id FOREIGN KEY (role_template_id) REFERENCES public.role_templates(id) ON DELETE SET NULL;
