CREATE TABLE public.asp_net_role_claims (
    id integer NOT NULL,
    role_id integer NOT NULL,
    claim_type text,
    claim_value text
);

ALTER TABLE public.asp_net_role_claims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asp_net_role_claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.asp_net_role_claims
    ADD CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id);

ALTER TABLE ONLY public.asp_net_role_claims
    ADD CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES public.asp_net_roles(id) ON DELETE CASCADE;
