CREATE TABLE public.asp_net_roles (
    id integer NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text
);

ALTER TABLE public.asp_net_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asp_net_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.asp_net_roles
    ADD CONSTRAINT pk_asp_net_roles PRIMARY KEY (id);
