CREATE TABLE public.assets (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    asset_type integer NOT NULL,
    location character varying(200),
    manufacturer character varying(200),
    model character varying(200),
    serial_number character varying(100),
    status integer NOT NULL,
    photo_file_id character varying(200),
    current_hours numeric(18,2) NOT NULL,
    notes character varying(2000),
    is_customer_owned boolean NOT NULL,
    cavity_count integer,
    tool_life_expectancy integer,
    current_shot_count integer NOT NULL,
    source_job_id integer,
    source_part_id integer,
    acquisition_cost numeric(18,2),
    depreciation_method integer,
    work_center_id integer,
    gl_account character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT pk_assets PRIMARY KEY (id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT fk_assets__jobs_source_job_id FOREIGN KEY (source_job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT fk_assets__parts_source_part_id FOREIGN KEY (source_part_id) REFERENCES public.parts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT fk_assets__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;
