CREATE TABLE public.assignment_rules (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    kind character varying(40) NOT NULL,
    priority integer NOT NULL,
    is_active boolean NOT NULL,
    spec jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.assignment_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignment_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.assignment_rules
    ADD CONSTRAINT pk_assignment_rules PRIMARY KEY (id);
