CREATE TABLE public.attestations (
    id integer NOT NULL,
    sales_order_id integer,
    party_type character varying(20),
    party_id integer,
    statement_type character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    method character varying(30) NOT NULL,
    artifact_id integer,
    communication_id integer,
    superseded_by_id integer,
    supported_by_attestation_id integer,
    captured_at timestamp with time zone,
    file_attachment_id integer,
    recorded_by_user_id integer,
    accepted_by_name character varying(200),
    accepted_by_contact_id integer,
    provider character varying(50),
    provider_reference character varying(200),
    access_token character varying(128),
    verification_key_hash character varying(200),
    sent_to character varying(320),
    ip_address character varying(64),
    note character varying(1000),
    expires_at timestamp with time zone,
    accepted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.attestations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attestations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT pk_attestations PRIMARY KEY (id);

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT ck_attestations_scope CHECK (sales_order_id IS NOT NULL OR party_id IS NOT NULL);

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT fk_attestations__communication_artifacts_artifact_id FOREIGN KEY (artifact_id) REFERENCES public.communication_artifacts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT fk_attestations__communications_communication_id FOREIGN KEY (communication_id) REFERENCES public.communications(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT fk_attestations_attestations_superseded_by_id FOREIGN KEY (superseded_by_id) REFERENCES public.attestations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT fk_attestations_attestations_supported_by_attestation_id FOREIGN KEY (supported_by_attestation_id) REFERENCES public.attestations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT fk_attestations__file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.attestations
    ADD CONSTRAINT fk_attestations__sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE RESTRICT;
