CREATE TABLE public.audit_log_entries (
    id integer NOT NULL,
    user_id integer NOT NULL,
    action character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    entity_type character varying(50),
    entity_id integer,
    details text,
    ip_address character varying(45),
    user_agent character varying(500)
);

ALTER TABLE public.audit_log_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.audit_log_entries
    ADD CONSTRAINT pk_audit_log_entries PRIMARY KEY (id);
