CREATE TABLE public.auto_po_suggestions (
    id integer NOT NULL,
    part_id integer NOT NULL,
    vendor_id integer NOT NULL,
    suggested_qty numeric(18,4) NOT NULL,
    needed_by_date timestamp with time zone NOT NULL,
    source_sales_order_ids jsonb,
    status character varying(20) NOT NULL,
    converted_purchase_order_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.auto_po_suggestions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auto_po_suggestions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.auto_po_suggestions
    ADD CONSTRAINT pk_auto_po_suggestions PRIMARY KEY (id);

ALTER TABLE ONLY public.auto_po_suggestions
    ADD CONSTRAINT fk_auto_po_suggestions__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.auto_po_suggestions
    ADD CONSTRAINT fk_auto_po_suggestions__purchase_orders_converted_purchase_orde FOREIGN KEY (converted_purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.auto_po_suggestions
    ADD CONSTRAINT fk_auto_po_suggestions__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE RESTRICT;
