CREATE TABLE public.barcodes (
    id integer NOT NULL,
    value character varying(500) NOT NULL,
    entity_type character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    user_id integer,
    part_id integer,
    job_id integer,
    sales_order_id integer,
    purchase_order_id integer,
    asset_id integer,
    storage_location_id integer,
    lot_record_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.barcodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barcodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT pk_barcodes PRIMARY KEY (id);

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes__jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes__purchase_orders_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes__sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes__storage_locations_storage_location_id FOREIGN KEY (storage_location_id) REFERENCES public.storage_locations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.barcodes
    ADD CONSTRAINT fk_barcodes__lot_records_lot_record_id FOREIGN KEY (lot_record_id) REFERENCES public.lot_records(id) ON DELETE CASCADE;
