CREATE TABLE public.bi_api_keys (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    key_hash character varying(500) NOT NULL,
    key_prefix character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    allowed_entity_sets_json jsonb,
    allowed_ips_json jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.bi_api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bi_api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bi_api_keys
    ADD CONSTRAINT pk_bi_api_keys PRIMARY KEY (id);
