CREATE TABLE public.bin_movements (
    id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    lot_number character varying(100),
    from_location_id integer,
    to_location_id integer,
    moved_by integer NOT NULL,
    moved_at timestamp with time zone NOT NULL,
    reason integer,
    notes character varying(1000),
    reversed_movement_id integer,
    scan_action_log_id integer
);

ALTER TABLE public.bin_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bin_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bin_movements
    ADD CONSTRAINT pk_bin_movements PRIMARY KEY (id);

ALTER TABLE ONLY public.bin_movements
    ADD CONSTRAINT fk_bin_movements__scan_action_logs_scan_action_log_id FOREIGN KEY (scan_action_log_id) REFERENCES public.scan_action_logs(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.bin_movements
    ADD CONSTRAINT fk_bin_movements__storage_locations_from_location_id FOREIGN KEY (from_location_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.bin_movements
    ADD CONSTRAINT fk_bin_movements__storage_locations_to_location_id FOREIGN KEY (to_location_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.bin_movements
    ADD CONSTRAINT fk_bin_movements_bin_movements_reversed_movement_id FOREIGN KEY (reversed_movement_id) REFERENCES public.bin_movements(id) ON DELETE RESTRICT;
