CREATE TABLE public.bin_contents (
    id integer NOT NULL,
    location_id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    lot_number character varying(100),
    job_id integer,
    status integer NOT NULL,
    placed_by integer NOT NULL,
    placed_at timestamp with time zone NOT NULL,
    removed_at timestamp with time zone,
    removed_by integer,
    notes character varying(500),
    uom_id integer,
    reserved_quantity numeric(18,4) NOT NULL
);

ALTER TABLE public.bin_contents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bin_contents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bin_contents
    ADD CONSTRAINT pk_bin_contents PRIMARY KEY (id);

ALTER TABLE ONLY public.bin_contents
    ADD CONSTRAINT fk_bin_contents__jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.bin_contents
    ADD CONSTRAINT fk_bin_contents__storage_locations_location_id FOREIGN KEY (location_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.bin_contents
    ADD CONSTRAINT fk_bin_contents__units_of_measure_uom_id FOREIGN KEY (uom_id) REFERENCES public.units_of_measure(id);
