CREATE TABLE public.bom_revisions (
    id integer NOT NULL,
    part_id integer NOT NULL,
    revision_number integer NOT NULL,
    effective_date timestamp with time zone NOT NULL,
    notes character varying(2000),
    created_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.bom_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bom_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bom_revisions
    ADD CONSTRAINT pk_bom_revisions PRIMARY KEY (id);

ALTER TABLE ONLY public.bom_revisions
    ADD CONSTRAINT fk_bom_revisions__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;
