CREATE TABLE public.bom_revision_lines (
    id integer NOT NULL,
    bom_revision_id integer NOT NULL,
    part_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_of_measure character varying(50) NOT NULL,
    operation_id integer,
    reference_designator character varying(50),
    source_type integer NOT NULL,
    lead_time_days integer,
    notes character varying(500),
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.bom_revision_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bom_revision_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bom_revision_lines
    ADD CONSTRAINT pk_bom_revision_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.bom_revision_lines
    ADD CONSTRAINT fk_bom_revision_lines__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.bom_revision_lines
    ADD CONSTRAINT fk_bom_revision_lines_bom_revisions_bom_revision_id FOREIGN KEY (bom_revision_id) REFERENCES public.bom_revisions(id) ON DELETE CASCADE;
