CREATE TABLE public.bomlines (
    id integer NOT NULL,
    parent_part_id integer NOT NULL,
    child_part_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    reference_designator character varying(50),
    sort_order integer NOT NULL,
    source_type integer NOT NULL,
    lead_time_days integer,
    notes character varying(500),
    uom_id integer,
    vendor_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.bomlines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bomlines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bomlines
    ADD CONSTRAINT pk_bomlines PRIMARY KEY (id);

ALTER TABLE ONLY public.bomlines
    ADD CONSTRAINT fk_bomlines__parts_child_part_id FOREIGN KEY (child_part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.bomlines
    ADD CONSTRAINT fk_bomlines__parts_parent_part_id FOREIGN KEY (parent_part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.bomlines
    ADD CONSTRAINT fk_bomlines__units_of_measure_uom_id FOREIGN KEY (uom_id) REFERENCES public.units_of_measure(id);

ALTER TABLE ONLY public.bomlines
    ADD CONSTRAINT fk_bomlines__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;
