-- Registry of human-readable business numbers (part numbers, order/invoice/…
-- numbers, customer/vendor/lead codes), with rename history. The entity's own
-- `*_number` column stays as the fast denormalized "current value"; this table
-- adds temporal history + resolution so a past number keeps resolving to its
-- owner after a rename.
CREATE TABLE public.business_identifiers (
    id integer NOT NULL,
    -- The kind of business object this number belongs to (Part, Customer, SalesOrder, …).
    entity_type character varying(40) NOT NULL,
    entity_id integer NOT NULL,
    value character varying(80) NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    -- NULL = currently active; set to the rename timestamp when superseded.
    effective_to timestamp with time zone,
    -- Calculated: an identifier is active while it has no end date. Uniqueness is
    -- enforced among active rows off this column; the current number is derived from it.
    is_active boolean GENERATED ALWAYS AS (effective_to IS NULL) STORED,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.business_identifiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_identifiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.business_identifiers
    ADD CONSTRAINT pk_business_identifiers PRIMARY KEY (id);
