CREATE TABLE public.calendar_super_groups (
    id integer NOT NULL,
    key character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(1000),
    color character varying(20),
    icon_name character varying(60),
    default_visible boolean NOT NULL,
    requires_tracking boolean NOT NULL,
    industry_gate character varying(40),
    sort_order integer NOT NULL,
    is_system boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.calendar_super_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_super_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.calendar_super_groups
    ADD CONSTRAINT pk_calendar_super_groups PRIMARY KEY (id);
