CREATE TABLE public.calendar_saved_views (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    owner_user_id integer,
    role_key character varying(60),
    scope character varying(60) NOT NULL,
    selected_super_group_ids integer[] NOT NULL,
    selected_event_type_ids integer[] NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.calendar_saved_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_saved_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.calendar_saved_views
    ADD CONSTRAINT pk_calendar_saved_views PRIMARY KEY (id);
