CREATE TABLE public.calendar_super_group_role_visibilities (
    id integer NOT NULL,
    super_group_id integer NOT NULL,
    role character varying(60) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.calendar_super_group_role_visibilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_super_group_role_visibilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.calendar_super_group_role_visibilities
    ADD CONSTRAINT pk_calendar_super_group_role_visibilities PRIMARY KEY (id);

ALTER TABLE ONLY public.calendar_super_group_role_visibilities
    ADD CONSTRAINT fk_calendar_super_group_role_visibilities__calendar_super_groups_super_group_id FOREIGN KEY (super_group_id) REFERENCES public.calendar_super_groups(id) ON DELETE CASCADE;
