CREATE TABLE public.calendar_event_types (
    id integer NOT NULL,
    super_group_id integer NOT NULL,
    key character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    color character varying(20),
    requires_tracking boolean NOT NULL,
    sort_order integer NOT NULL,
    is_system boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.calendar_event_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_event_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.calendar_event_types
    ADD CONSTRAINT pk_calendar_event_types PRIMARY KEY (id);

ALTER TABLE ONLY public.calendar_event_types
    ADD CONSTRAINT fk_calendar_event_types__calendar_super_groups_super_group_id FOREIGN KEY (super_group_id) REFERENCES public.calendar_super_groups(id) ON DELETE RESTRICT;
