CREATE TABLE public.calibration_records (
    id integer NOT NULL,
    gage_id integer NOT NULL,
    calibrated_by_id integer NOT NULL,
    calibrated_at timestamp with time zone NOT NULL,
    result integer NOT NULL,
    lab_name character varying(200),
    certificate_file_id integer,
    standards_used character varying(500),
    as_found_condition character varying(2000),
    as_left_condition character varying(2000),
    next_calibration_due date,
    notes character varying(2000)
);

ALTER TABLE public.calibration_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calibration_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.calibration_records
    ADD CONSTRAINT pk_calibration_records PRIMARY KEY (id);

ALTER TABLE ONLY public.calibration_records
    ADD CONSTRAINT fk_calibration_records__file_attachments_certificate_file_id FOREIGN KEY (certificate_file_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.calibration_records
    ADD CONSTRAINT fk_calibration_records__gages_gage_id FOREIGN KEY (gage_id) REFERENCES public.gages(id) ON DELETE CASCADE;
