CREATE TABLE public.capa_tasks (
    id integer NOT NULL,
    capa_id integer NOT NULL,
    title character varying(500) NOT NULL,
    description character varying(4000),
    assignee_id integer NOT NULL,
    due_date timestamp with time zone NOT NULL,
    status integer NOT NULL,
    completed_at timestamp with time zone,
    completed_by_id integer,
    completion_notes character varying(4000),
    sort_order integer NOT NULL
);

ALTER TABLE public.capa_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.capa_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.capa_tasks
    ADD CONSTRAINT pk_capa_tasks PRIMARY KEY (id);

ALTER TABLE ONLY public.capa_tasks
    ADD CONSTRAINT fk_capa_tasks__asp_net_users_assignee_id FOREIGN KEY (assignee_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.capa_tasks
    ADD CONSTRAINT fk_capa_tasks__asp_net_users_completed_by_id FOREIGN KEY (completed_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.capa_tasks
    ADD CONSTRAINT fk_capa_tasks__corrective_actions_capa_id FOREIGN KEY (capa_id) REFERENCES public.corrective_actions(id) ON DELETE CASCADE;
