CREATE TABLE public.capabilities (
    id integer NOT NULL,
    code character varying(64) NOT NULL,
    area character varying(16) NOT NULL,
    name character varying(256) NOT NULL,
    description text NOT NULL,
    enabled boolean NOT NULL,
    is_default_on boolean NOT NULL,
    requires_roles character varying(256),
    version bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.capabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.capabilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.capabilities
    ADD CONSTRAINT pk_capabilities PRIMARY KEY (id);
