CREATE TABLE public.capability_configs (
    id integer NOT NULL,
    capability_id integer NOT NULL,
    config_json jsonb NOT NULL,
    schema_version integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.capability_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.capability_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.capability_configs
    ADD CONSTRAINT pk_capability_configs PRIMARY KEY (id);

ALTER TABLE ONLY public.capability_configs
    ADD CONSTRAINT fk_capability_configs_capabilities_capability_id FOREIGN KEY (capability_id) REFERENCES public.capabilities(id) ON DELETE CASCADE;
