CREATE TABLE public.carriers (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(50),
    scac character varying(10),
    integration_kind integer NOT NULL,
    delivery_update_mode integer NOT NULL,
    integration_service_id character varying(50),
    requires_scan_to_ship boolean NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.carriers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carriers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.carriers
    ADD CONSTRAINT pk_carriers PRIMARY KEY (id);
