CREATE TABLE public.channel_listings (
    id integer NOT NULL,
    channel_id integer NOT NULL,
    external_listing_id character varying(200) NOT NULL,
    external_sku character varying(200),
    title character varying(500),
    part_id integer,
    listed_price numeric(18,4),
    published_quantity numeric(18,4),
    last_synced_at timestamp with time zone,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.channel_listings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_listings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.channel_listings
    ADD CONSTRAINT pk_channel_listings PRIMARY KEY (id);

ALTER TABLE ONLY public.channel_listings
    ADD CONSTRAINT fk_channel_listings__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.channel_listings
    ADD CONSTRAINT fk_channel_listings__sales_channels_channel_id FOREIGN KEY (channel_id) REFERENCES public.sales_channels(id) ON DELETE CASCADE;
