CREATE TABLE public.channel_settlement_lines (
    id integer NOT NULL,
    settlement_id integer NOT NULL,
    line_type character varying(30) NOT NULL,
    sales_order_id integer,
    external_order_id character varying(200),
    amount numeric(18,2) NOT NULL,
    description character varying(500),
    posted_at timestamp with time zone
);

ALTER TABLE public.channel_settlement_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_settlement_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.channel_settlement_lines
    ADD CONSTRAINT pk_channel_settlement_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.channel_settlement_lines
    ADD CONSTRAINT fk_channel_settlement_lines__sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.channel_settlement_lines
    ADD CONSTRAINT fk_channel_settlement_lines_channel_settlements_settlement_id FOREIGN KEY (settlement_id) REFERENCES public.channel_settlements(id) ON DELETE CASCADE;
