CREATE TABLE public.channel_settlements (
    id integer NOT NULL,
    channel_id integer NOT NULL,
    external_settlement_id character varying(200) NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    deposited_at timestamp with time zone,
    reported_net_amount numeric(18,2) NOT NULL,
    currency_code character varying(3) NOT NULL,
    status character varying(20) NOT NULL,
    resolution_notes character varying(2000),
    raw_payload_json jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.channel_settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.channel_settlements
    ADD CONSTRAINT pk_channel_settlements PRIMARY KEY (id);

ALTER TABLE ONLY public.channel_settlements
    ADD CONSTRAINT fk_channel_settlements__sales_channels_channel_id FOREIGN KEY (channel_id) REFERENCES public.sales_channels(id) ON DELETE RESTRICT;
