CREATE TABLE public.chat_rooms (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    is_group boolean NOT NULL,
    created_by_id integer NOT NULL,
    channel_type character varying(20) DEFAULT ''::character varying NOT NULL,
    description character varying(500),
    team_id integer,
    is_read_only boolean DEFAULT false NOT NULL,
    icon_name character varying(50),
    created_by_system boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.chat_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT pk_chat_rooms PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT fk_chat_rooms__asp_net_users_created_by_id FOREIGN KEY (created_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT fk_chat_rooms__teams_team_id FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL;
