CREATE TABLE public.chat_messages (
    id integer NOT NULL,
    sender_id integer NOT NULL,
    recipient_id integer NOT NULL,
    content text NOT NULL,
    is_read boolean NOT NULL,
    read_at timestamp with time zone,
    chat_room_id integer,
    file_attachment_id integer,
    linked_entity_type text,
    linked_entity_id integer,
    parent_message_id integer,
    thread_reply_count integer DEFAULT 0 NOT NULL,
    thread_last_reply_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT pk_chat_messages PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_chat_messages__asp_net_users_recipient_id FOREIGN KEY (recipient_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_chat_messages__asp_net_users_sender_id FOREIGN KEY (sender_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_chat_messages__chat_rooms_chat_room_id FOREIGN KEY (chat_room_id) REFERENCES public.chat_rooms(id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_chat_messages__file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk_chat_messages_chat_messages_parent_message_id FOREIGN KEY (parent_message_id) REFERENCES public.chat_messages(id) ON DELETE RESTRICT;
