CREATE TABLE public.chat_message_mentions (
    id integer NOT NULL,
    chat_message_id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    display_text character varying(200) NOT NULL
);

ALTER TABLE public.chat_message_mentions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_mentions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.chat_message_mentions
    ADD CONSTRAINT pk_chat_message_mentions PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_message_mentions
    ADD CONSTRAINT fk_chat_message_mentions_chat_messages_chat_message_id FOREIGN KEY (chat_message_id) REFERENCES public.chat_messages(id) ON DELETE CASCADE;
