CREATE TABLE public.chat_room_members (
    id integer NOT NULL,
    chat_room_id integer NOT NULL,
    user_id integer NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    role character varying(20) DEFAULT ''::character varying NOT NULL,
    muted_until timestamp with time zone,
    last_read_message_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.chat_room_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.chat_room_members
    ADD CONSTRAINT pk_chat_room_members PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_room_members
    ADD CONSTRAINT fk_chat_room_members__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.chat_room_members
    ADD CONSTRAINT fk_chat_room_members_chat_messages_last_read_message_id FOREIGN KEY (last_read_message_id) REFERENCES public.chat_messages(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.chat_room_members
    ADD CONSTRAINT fk_chat_room_members_chat_rooms_chat_room_id FOREIGN KEY (chat_room_id) REFERENCES public.chat_rooms(id) ON DELETE CASCADE;
