CREATE TABLE public.clock_events (
    id integer NOT NULL,
    user_id integer NOT NULL,
    event_type integer NOT NULL,
    event_type_code character varying(50) NOT NULL,
    operation_id integer,
    reason character varying(100),
    scan_method character varying(50),
    "timestamp" timestamp with time zone NOT NULL,
    source character varying(50)
);

ALTER TABLE public.clock_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clock_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.clock_events
    ADD CONSTRAINT pk_clock_events PRIMARY KEY (id);

ALTER TABLE ONLY public.clock_events
    ADD CONSTRAINT fk_clock_events__operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;
