CREATE TABLE public.cloud_storage_providers (
    id integer NOT NULL,
    provider_code character varying(50) NOT NULL,
    mode integer NOT NULL,
    is_active boolean NOT NULL,
    root_folder_id character varying(500),
    service_account_id character varying(500),
    oauth_token_encrypted character varying(4000),
    refresh_token_encrypted character varying(4000),
    token_expires_at timestamp with time zone,
    last_connected_at timestamp with time zone,
    last_error character varying(2000),
    settings jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.cloud_storage_providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cloud_storage_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cloud_storage_providers
    ADD CONSTRAINT pk_cloud_storage_providers PRIMARY KEY (id);
