CREATE TABLE public.communication_artifacts (
    id integer NOT NULL,
    communication_id integer NOT NULL,
    kind character varying(20) NOT NULL,
    sha256 character(64) NOT NULL,
    content_type character varying(255) NOT NULL,
    byte_size bigint NOT NULL,
    original_filename character varying(500),
    bucket_name character varying(100) NOT NULL,
    object_key character varying(500) NOT NULL,
    ingested_at timestamp with time zone NOT NULL
);

ALTER TABLE public.communication_artifacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communication_artifacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.communication_artifacts
    ADD CONSTRAINT pk_communication_artifacts PRIMARY KEY (id);

ALTER TABLE ONLY public.communication_artifacts
    ADD CONSTRAINT fk_communication_artifacts_communications_communication_id FOREIGN KEY (communication_id) REFERENCES public.communications(id) ON DELETE CASCADE;
