CREATE TABLE public.communications (
    id integer NOT NULL,
    contact_id integer,
    party_type character varying(20),
    party_id integer,
    match_confidence character varying(20),
    channel character varying(20) NOT NULL,
    flow character varying(20) NOT NULL,
    thread_id character varying(998),
    external_id character varying(200),
    from_address character varying(320),
    handled_by_user_id integer,
    type character varying(20) NOT NULL,
    subject character varying(200) NOT NULL,
    body text,
    occurred_at timestamp with time zone NOT NULL,
    duration_minutes integer,
    is_triaged boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.communications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.communications
    ADD CONSTRAINT pk_communications PRIMARY KEY (id);

ALTER TABLE ONLY public.communications
    ADD CONSTRAINT fk_communications__contacts_contact_id FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE;
