CREATE TABLE public.communication_links (
    id integer NOT NULL,
    communication_id integer NOT NULL,
    entity_type character varying(30) NOT NULL,
    entity_id integer NOT NULL,
    party_type character varying(20),
    party_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.communication_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communication_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.communication_links
    ADD CONSTRAINT pk_communication_links PRIMARY KEY (id);

ALTER TABLE ONLY public.communication_links
    ADD CONSTRAINT ck_communication_links_part_requires_party CHECK (entity_type <> 'Part' OR party_id IS NOT NULL);

ALTER TABLE ONLY public.communication_links
    ADD CONSTRAINT fk_communication_links_communications_communication_id FOREIGN KEY (communication_id) REFERENCES public.communications(id) ON DELETE CASCADE;
