CREATE TABLE public.communication_sync_configs (
    id integer NOT NULL,
    user_id integer NOT NULL,
    kind character varying(16) NOT NULL,
    provider_id character varying(50) NOT NULL,
    display_label character varying(120),
    is_connected boolean NOT NULL,
    access_token character varying(4000),
    refresh_token character varying(4000),
    access_token_expires_at timestamp with time zone,
    external_account_id character varying(200),
    last_synced_at timestamp with time zone,
    last_synced_external_id character varying(200),
    config_json jsonb,
    last_error character varying(1024),
    last_error_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.communication_sync_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communication_sync_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.communication_sync_configs
    ADD CONSTRAINT pk_communication_sync_configs PRIMARY KEY (id);

ALTER TABLE ONLY public.communication_sync_configs
    ADD CONSTRAINT fk_communication_sync_configs__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;
