CREATE TABLE public.communication_ingest_rules (
    id integer NOT NULL,
    match_type character varying(20) NOT NULL,
    pattern character varying(320) NOT NULL,
    is_enabled boolean NOT NULL,
    party_type character varying(20),
    party_id integer,
    note character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.communication_ingest_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communication_ingest_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.communication_ingest_rules
    ADD CONSTRAINT pk_communication_ingest_rules PRIMARY KEY (id);
