CREATE TABLE public.compliance_form_templates (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    form_type integer NOT NULL,
    description character varying(500) NOT NULL,
    icon character varying(50) NOT NULL,
    source_url character varying(500),
    sha256_hash character varying(64),
    is_auto_sync boolean NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    requires_identity_docs boolean NOT NULL,
    docu_seal_template_id integer,
    last_synced_at timestamp with time zone,
    manual_override_file_id integer,
    blocks_job_assignment boolean NOT NULL,
    profile_completion_key character varying(50) NOT NULL,
    acro_field_map_json jsonb,
    filled_pdf_template_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.compliance_form_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compliance_form_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.compliance_form_templates
    ADD CONSTRAINT pk_compliance_form_templates PRIMARY KEY (id);

ALTER TABLE ONLY public.compliance_form_templates
    ADD CONSTRAINT fk_compliance_form_templates__file_attachments_filled_pdf_templ FOREIGN KEY (filled_pdf_template_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.compliance_form_templates
    ADD CONSTRAINT fk_compliance_form_templates__file_attachments_manual_override_ FOREIGN KEY (manual_override_file_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;
