CREATE TABLE public.compliance_field_rules (
    id integer NOT NULL,
    compliance_profile_id integer NOT NULL,
    field_key character varying(80) NOT NULL,
    process_step character varying(80) NOT NULL,
    condition character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.compliance_field_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compliance_field_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.compliance_field_rules
    ADD CONSTRAINT pk_compliance_field_rules PRIMARY KEY (id);

ALTER TABLE ONLY public.compliance_field_rules
    ADD CONSTRAINT fk_compliance_field_rules__compliance_profiles_compliance_profile_id FOREIGN KEY (compliance_profile_id) REFERENCES public.compliance_profiles(id) ON DELETE CASCADE;
