CREATE TABLE public.compliance_form_submissions (
    id integer NOT NULL,
    template_id integer NOT NULL,
    user_id integer NOT NULL,
    docu_seal_submission_id integer,
    status integer NOT NULL,
    signed_at timestamp with time zone,
    signed_pdf_file_id integer,
    docu_seal_submit_url character varying(1000),
    form_data_json jsonb,
    form_definition_version_id integer,
    filled_pdf_file_id integer,
    i9_section1_signed_at timestamp with time zone,
    i9_section2_signed_at timestamp with time zone,
    i9_employer_user_id integer,
    i9_document_list_type character varying(3),
    i9_document_data_json jsonb,
    i9_section2_overdue_at timestamp with time zone,
    i9_reverification_due_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.compliance_form_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compliance_form_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.compliance_form_submissions
    ADD CONSTRAINT pk_compliance_form_submissions PRIMARY KEY (id);

ALTER TABLE ONLY public.compliance_form_submissions
    ADD CONSTRAINT fk_compliance_form_submissions__compliance_form_templates_templ FOREIGN KEY (template_id) REFERENCES public.compliance_form_templates(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.compliance_form_submissions
    ADD CONSTRAINT fk_compliance_form_submissions__file_attachments_filled_pdf_fil FOREIGN KEY (filled_pdf_file_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.compliance_form_submissions
    ADD CONSTRAINT fk_compliance_form_submissions__file_attachments_signed_pdf_fil FOREIGN KEY (signed_pdf_file_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.compliance_form_submissions
    ADD CONSTRAINT fk_compliance_form_submissions__form_definition_versions_form_d FOREIGN KEY (form_definition_version_id) REFERENCES public.form_definition_versions(id) ON DELETE SET NULL;
