CREATE TABLE public.company_locations (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    line1 character varying(200) NOT NULL,
    line2 character varying(200),
    city character varying(100) NOT NULL,
    state character varying(50) NOT NULL,
    postal_code character varying(20) NOT NULL,
    country character varying(10) NOT NULL,
    phone character varying(20),
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    working_calendar_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.company_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.company_locations
    ADD CONSTRAINT pk_company_locations PRIMARY KEY (id);

ALTER TABLE ONLY public.company_locations
    ADD CONSTRAINT fk_company_locations__working_calendars_working_calendar_id FOREIGN KEY (working_calendar_id) REFERENCES public.working_calendars(id) ON DELETE SET NULL;
