CREATE TABLE public.compliance_profiles (
    id integer NOT NULL,
    industry_key character varying(60) NOT NULL,
    name character varying(120) NOT NULL,
    required_traceability_type character varying(20) NOT NULL,
    sds_required boolean NOT NULL,
    is_active boolean NOT NULL,
    is_system boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.compliance_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compliance_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.compliance_profiles
    ADD CONSTRAINT pk_compliance_profiles PRIMARY KEY (id);
