CREATE TABLE public.configurator_options (
    id integer NOT NULL,
    configurator_id integer NOT NULL,
    name character varying(200) NOT NULL,
    option_type integer NOT NULL,
    values_json text NOT NULL,
    pricing_rule_json text,
    bom_impact_json text,
    routing_impact_json text,
    depends_on_option_id character varying(50),
    sort_order integer NOT NULL,
    is_required boolean NOT NULL,
    help_text character varying(500),
    default_value character varying(500)
);

ALTER TABLE public.configurator_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configurator_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.configurator_options
    ADD CONSTRAINT pk_configurator_options PRIMARY KEY (id);

ALTER TABLE ONLY public.configurator_options
    ADD CONSTRAINT fk_configurator_options__product_configurators_configurator_id FOREIGN KEY (configurator_id) REFERENCES public.product_configurators(id) ON DELETE CASCADE;
