CREATE TABLE public.consignment_transactions (
    id integer NOT NULL,
    agreement_id integer NOT NULL,
    type integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    extended_amount numeric(18,4) NOT NULL,
    purchase_order_id integer,
    invoice_id integer,
    bin_content_id integer,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE public.consignment_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consignment_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.consignment_transactions
    ADD CONSTRAINT pk_consignment_transactions PRIMARY KEY (id);

ALTER TABLE ONLY public.consignment_transactions
    ADD CONSTRAINT fk_consignment_transactions__invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.consignment_transactions
    ADD CONSTRAINT fk_consignment_transactions__purchase_orders_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.consignment_transactions
    ADD CONSTRAINT fk_consignment_transactions_consignment_agreements_agreement_id FOREIGN KEY (agreement_id) REFERENCES public.consignment_agreements(id) ON DELETE CASCADE;
