CREATE TABLE public.consignment_agreements (
    id integer NOT NULL,
    direction integer NOT NULL,
    vendor_id integer,
    customer_id integer,
    part_id integer NOT NULL,
    agreed_unit_price numeric(18,4) NOT NULL,
    min_stock_quantity numeric(18,4),
    max_stock_quantity numeric(18,4),
    effective_from date NOT NULL,
    effective_to date,
    invoice_on_consumption boolean NOT NULL,
    status integer NOT NULL,
    terms character varying(4000),
    reconciliation_frequency_days integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.consignment_agreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consignment_agreements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.consignment_agreements
    ADD CONSTRAINT pk_consignment_agreements PRIMARY KEY (id);

ALTER TABLE ONLY public.consignment_agreements
    ADD CONSTRAINT fk_consignment_agreements__customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.consignment_agreements
    ADD CONSTRAINT fk_consignment_agreements__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.consignment_agreements
    ADD CONSTRAINT fk_consignment_agreements__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;
