CREATE TABLE public.contact_outreach_preferences (
    id integer NOT NULL,
    contact_id integer NOT NULL,
    email_opt_out boolean NOT NULL,
    email_opt_out_at timestamp with time zone,
    email_opt_out_source character varying(200),
    call_opt_out boolean NOT NULL,
    call_opt_out_at timestamp with time zone,
    call_opt_out_source character varying(200),
    sms_opt_out boolean NOT NULL,
    sms_opt_out_at timestamp with time zone,
    sms_opt_out_source character varying(200),
    cooldown_until timestamp with time zone,
    cooldown_reason_code character varying(100),
    cooldown_notes character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.contact_outreach_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_outreach_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.contact_outreach_preferences
    ADD CONSTRAINT pk_contact_outreach_preferences PRIMARY KEY (id);

ALTER TABLE ONLY public.contact_outreach_preferences
    ADD CONSTRAINT fk_contact_outreach_preferences_contacts_contact_id FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE;
