CREATE TABLE public.controlled_documents (
    id integer NOT NULL,
    document_number character varying(50) NOT NULL,
    title character varying(300) NOT NULL,
    description character varying(2000),
    category character varying(50) NOT NULL,
    current_revision integer NOT NULL,
    status integer NOT NULL,
    owner_id integer NOT NULL,
    checked_out_by_id integer,
    checked_out_at timestamp with time zone,
    released_at timestamp with time zone,
    review_due_date timestamp with time zone,
    review_interval_days integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.controlled_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.controlled_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.controlled_documents
    ADD CONSTRAINT pk_controlled_documents PRIMARY KEY (id);
