CREATE TABLE public.contact_interactions (
    id integer NOT NULL,
    contact_id integer NOT NULL,
    user_id integer NOT NULL,
    type character varying(20) NOT NULL,
    subject character varying(200) NOT NULL,
    body character varying(4000),
    interaction_date timestamp with time zone NOT NULL,
    duration_minutes integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.contact_interactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_interactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.contact_interactions
    ADD CONSTRAINT pk_contact_interactions PRIMARY KEY (id);

ALTER TABLE ONLY public.contact_interactions
    ADD CONSTRAINT fk_contact_interactions_contacts_contact_id FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE;
