CREATE TABLE public.corrective_actions (
    id integer NOT NULL,
    capa_number character varying(25) NOT NULL,
    type integer NOT NULL,
    source_type integer NOT NULL,
    source_entity_id integer,
    source_entity_type character varying(100),
    title character varying(500) NOT NULL,
    problem_description character varying(4000) NOT NULL,
    impact_description character varying(4000),
    root_cause_analysis character varying(4000),
    root_cause_method integer,
    root_cause_method_data jsonb,
    root_cause_analyzed_by_id integer,
    root_cause_completed_at timestamp with time zone,
    containment_action character varying(4000),
    corrective_action_description character varying(4000),
    preventive_action character varying(4000),
    verification_method character varying(2000),
    verification_result character varying(4000),
    verified_by_id integer,
    verification_date timestamp with time zone,
    effectiveness_check_due_date timestamp with time zone,
    effectiveness_check_date timestamp with time zone,
    effectiveness_result character varying(4000),
    is_effective boolean,
    effectiveness_checked_by_id integer,
    owner_id integer NOT NULL,
    status integer NOT NULL,
    priority integer NOT NULL,
    due_date timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    closed_by_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.corrective_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.corrective_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.corrective_actions
    ADD CONSTRAINT pk_corrective_actions PRIMARY KEY (id);

ALTER TABLE ONLY public.corrective_actions
    ADD CONSTRAINT fk_corrective_actions__asp_net_users_closed_by_id FOREIGN KEY (closed_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.corrective_actions
    ADD CONSTRAINT fk_corrective_actions__asp_net_users_effectiveness_checked_by_i FOREIGN KEY (effectiveness_checked_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.corrective_actions
    ADD CONSTRAINT fk_corrective_actions__asp_net_users_owner_id FOREIGN KEY (owner_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.corrective_actions
    ADD CONSTRAINT fk_corrective_actions__asp_net_users_root_cause_analyzed_by_id FOREIGN KEY (root_cause_analyzed_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.corrective_actions
    ADD CONSTRAINT fk_corrective_actions__asp_net_users_verified_by_id FOREIGN KEY (verified_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;
