CREATE TABLE public.costing_template_lines (
    id integer NOT NULL,
    costing_template_id integer NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    behavior integer NOT NULL,
    driver integer NOT NULL,
    amount_basis integer NOT NULL,
    default_value numeric(18,2),
    gl_account_number character varying(16),
    gl_account_name character varying(128),
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.costing_template_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.costing_template_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.costing_template_lines
    ADD CONSTRAINT pk_costing_template_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.costing_template_lines
    ADD CONSTRAINT fk_costing_template_lines__costing_templates_costing_template_id FOREIGN KEY (costing_template_id) REFERENCES public.costing_templates(id) ON DELETE CASCADE;

CREATE INDEX ix_costing_template_lines_costing_template_id ON public.costing_template_lines USING btree (costing_template_id);
