CREATE TABLE public.cost_calculation_inputs (
    id integer NOT NULL,
    cost_calculation_id integer NOT NULL,
    direct_material_cost numeric(18,4),
    direct_labor_hours numeric(10,2),
    direct_labor_cost numeric(18,4),
    machine_hours numeric(10,2),
    overhead_amount numeric(18,4),
    overhead_rate_pct numeric(7,4),
    custom_inputs jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.cost_calculation_inputs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cost_calculation_inputs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cost_calculation_inputs
    ADD CONSTRAINT pk_cost_calculation_inputs PRIMARY KEY (id);

ALTER TABLE ONLY public.cost_calculation_inputs
    ADD CONSTRAINT "fk_cost_calculation_inputs_cost_calculations_cost_calculation_~" FOREIGN KEY (cost_calculation_id) REFERENCES public.cost_calculations(id) ON DELETE CASCADE;
