CREATE TABLE public.cost_calculations (
    id integer NOT NULL,
    entity_type character varying(64) NOT NULL,
    entity_id integer NOT NULL,
    profile_id integer NOT NULL,
    profile_version integer NOT NULL,
    result_amount numeric(18,4) NOT NULL,
    result_breakdown jsonb,
    calculated_at timestamp with time zone NOT NULL,
    calculated_by integer,
    is_current boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.cost_calculations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cost_calculations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cost_calculations
    ADD CONSTRAINT pk_cost_calculations PRIMARY KEY (id);

ALTER TABLE ONLY public.cost_calculations
    ADD CONSTRAINT fk_cost_calculations__costing_profiles_profile_id FOREIGN KEY (profile_id) REFERENCES public.costing_profiles(id) ON DELETE RESTRICT;
