CREATE TABLE public.costing_templates (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    description character varying(512),
    is_system boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.costing_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.costing_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.costing_templates
    ADD CONSTRAINT pk_costing_templates PRIMARY KEY (id);

CREATE UNIQUE INDEX ux_costing_templates_name ON public.costing_templates USING btree (name) WHERE (deleted_at IS NULL);
