CREATE TABLE public.costing_cost_centers (
    id integer NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    parent_id integer,
    type integer NOT NULL,
    sqft numeric(18,4),
    headcount numeric(18,4),
    is_inventoriable boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.costing_cost_centers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.costing_cost_centers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.costing_cost_centers
    ADD CONSTRAINT pk_costing_cost_centers PRIMARY KEY (id);

ALTER TABLE ONLY public.costing_cost_centers
    ADD CONSTRAINT fk_costing_cost_centers__costing_cost_centers_parent_id FOREIGN KEY (parent_id) REFERENCES public.costing_cost_centers(id) ON DELETE SET NULL;

CREATE INDEX ix_costing_cost_centers_parent_id ON public.costing_cost_centers (parent_id);
