CREATE TABLE public.cost_allocation_rules (
    id integer NOT NULL,
    source_account_pattern character varying(256) NOT NULL,
    basis integer NOT NULL,
    split_json text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.cost_allocation_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cost_allocation_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cost_allocation_rules
    ADD CONSTRAINT pk_cost_allocation_rules PRIMARY KEY (id);
