CREATE TABLE public.costing_profiles (
    id integer NOT NULL,
    code character varying(64) NOT NULL,
    mode character varying(16) NOT NULL,
    flat_rate_pct numeric(7,4),
    departmental_rates jsonb,
    pools jsonb,
    effective_from date NOT NULL,
    effective_to date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.costing_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.costing_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.costing_profiles
    ADD CONSTRAINT pk_costing_profiles PRIMARY KEY (id);
