CREATE TABLE public.credit_holds (
    id integer NOT NULL,
    customer_id integer NOT NULL,
    reason integer NOT NULL,
    notes character varying(2000),
    placed_by_id integer NOT NULL,
    placed_at timestamp with time zone NOT NULL,
    released_by_id integer,
    released_at timestamp with time zone,
    release_notes character varying(2000),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.credit_holds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_holds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.credit_holds
    ADD CONSTRAINT pk_credit_holds PRIMARY KEY (id);

ALTER TABLE ONLY public.credit_holds
    ADD CONSTRAINT fk_credit_holds__customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
