CREATE TABLE public.customer_tax_documents (
    id integer NOT NULL,
    customer_id integer NOT NULL,
    file_attachment_id integer NOT NULL,
    state_code character varying(2),
    certificate_type character varying(30) NOT NULL,
    certificate_number character varying(100),
    status character varying(20) DEFAULT 'Pending'::character varying NOT NULL,
    verified_by_id integer,
    verified_at timestamp with time zone,
    rejection_reason character varying(500),
    expiration_date timestamp with time zone,
    parsed_fields jsonb,
    signature_provider character varying(50),
    signature_ref character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.customer_tax_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_tax_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customer_tax_documents
    ADD CONSTRAINT pk_customer_tax_documents PRIMARY KEY (id);

ALTER TABLE ONLY public.customer_tax_documents
    ADD CONSTRAINT fk_customer_tax_documents_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.customer_tax_documents
    ADD CONSTRAINT fk_customer_tax_documents_file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.customer_tax_documents
    ADD CONSTRAINT fk_customer_tax_documents__asp_net_users_verified_by_id FOREIGN KEY (verified_by_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;
