CREATE TABLE public.customer_segments (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    filter_criteria jsonb,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.customer_segments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_segments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customer_segments
    ADD CONSTRAINT pk_customer_segments PRIMARY KEY (id);
