CREATE TABLE public.customer_portal_accesses (
    id integer NOT NULL,
    contact_id integer NOT NULL,
    customer_id integer NOT NULL,
    one_time_token_hash character varying(128),
    one_time_token_expires_at timestamp with time zone,
    is_enabled boolean NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.customer_portal_accesses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_portal_accesses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customer_portal_accesses
    ADD CONSTRAINT pk_customer_portal_accesses PRIMARY KEY (id);

ALTER TABLE ONLY public.customer_portal_accesses
    ADD CONSTRAINT fk_customer_portal_accesses_contacts_contact_id FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.customer_portal_accesses
    ADD CONSTRAINT fk_customer_portal_accesses_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
