CREATE TABLE public.customers (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    company_name character varying(200),
    email character varying(200),
    phone character varying(50),
    is_active boolean NOT NULL,
    deactivation_date timestamp with time zone,
    credit_limit numeric(18,2),
    is_on_credit_hold boolean DEFAULT false NOT NULL,
    credit_hold_reason character varying(500),
    credit_hold_at timestamp with time zone,
    credit_hold_by_id integer,
    last_credit_review_date timestamp with time zone,
    credit_review_frequency_days integer,
    is_tax_exempt boolean DEFAULT false NOT NULL,
    tax_exemption_id character varying(50),
    exemption_expiry_date date,
    default_tax_code_id integer,
    default_currency character varying(3),
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    is_fda_regulated boolean DEFAULT false NOT NULL,
    is_aerospace boolean DEFAULT false NOT NULL,
    is_automotive boolean DEFAULT false NOT NULL,
    is_itar_controlled boolean DEFAULT false NOT NULL,
    is_reference_ok boolean DEFAULT false NOT NULL,
    reference_notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT pk_customers PRIMARY KEY (id);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fk_customers__sales_tax_rates_default_tax_code_id FOREIGN KEY (default_tax_code_id) REFERENCES public.sales_tax_rates(id) ON DELETE SET NULL;
