CREATE TABLE public.customer_po_documents (
    id integer NOT NULL,
    sales_order_id integer NOT NULL,
    document_number character varying(30) NOT NULL,
    generated_from_quote_id integer,
    generated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.customer_po_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_po_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customer_po_documents
    ADD CONSTRAINT pk_customer_po_documents PRIMARY KEY (id);

ALTER TABLE ONLY public.customer_po_documents
    ADD CONSTRAINT fk_customer_po_documents_sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.customer_po_documents
    ADD CONSTRAINT fk_customer_po_documents_quotes_generated_from_quote_id FOREIGN KEY (generated_from_quote_id) REFERENCES public.quotes(id) ON DELETE SET NULL;
