CREATE TABLE public.customer_returns (
    id integer NOT NULL,
    return_number character varying(50) NOT NULL,
    customer_id integer NOT NULL,
    original_job_id integer NOT NULL,
    rework_job_id integer,
    reason character varying(1000) NOT NULL,
    notes character varying(2000),
    status integer NOT NULL,
    return_date timestamp with time zone NOT NULL,
    inspected_by_id integer,
    inspected_at timestamp with time zone,
    inspection_notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.customer_returns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_returns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customer_returns
    ADD CONSTRAINT pk_customer_returns PRIMARY KEY (id);

ALTER TABLE ONLY public.customer_returns
    ADD CONSTRAINT fk_customer_returns__jobs_original_job_id FOREIGN KEY (original_job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.customer_returns
    ADD CONSTRAINT fk_customer_returns__jobs_rework_job_id FOREIGN KEY (rework_job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.customer_returns
    ADD CONSTRAINT fk_customer_returns_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;
