CREATE TABLE public.cycle_count_lines (
    id integer NOT NULL,
    cycle_count_id integer NOT NULL,
    bin_content_id integer,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    expected_quantity integer NOT NULL,
    actual_quantity integer NOT NULL,
    notes character varying(500)
);

ALTER TABLE public.cycle_count_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cycle_count_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cycle_count_lines
    ADD CONSTRAINT pk_cycle_count_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.cycle_count_lines
    ADD CONSTRAINT fk_cycle_count_lines_bin_contents_bin_content_id FOREIGN KEY (bin_content_id) REFERENCES public.bin_contents(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.cycle_count_lines
    ADD CONSTRAINT fk_cycle_count_lines_cycle_counts_cycle_count_id FOREIGN KEY (cycle_count_id) REFERENCES public.cycle_counts(id) ON DELETE CASCADE;
