CREATE TABLE public.cycle_counts (
    id integer NOT NULL,
    location_id integer NOT NULL,
    counted_by_id integer NOT NULL,
    counted_at timestamp with time zone NOT NULL,
    status character varying(50) NOT NULL,
    notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.cycle_counts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cycle_counts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cycle_counts
    ADD CONSTRAINT pk_cycle_counts PRIMARY KEY (id);

ALTER TABLE ONLY public.cycle_counts
    ADD CONSTRAINT fk_cycle_counts__asp_net_users_counted_by_id FOREIGN KEY (counted_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.cycle_counts
    ADD CONSTRAINT fk_cycle_counts__storage_locations_location_id FOREIGN KEY (location_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;
