CREATE TABLE public.data_protection_keys (
    id integer NOT NULL,
    friendly_name text,
    xml text
);

ALTER TABLE public.data_protection_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_protection_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.data_protection_keys
    ADD CONSTRAINT pk_data_protection_keys PRIMARY KEY (id);
