CREATE TABLE public.deliverables (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(4000),
    job_id integer,
    project_id integer,
    customer_id integer,
    deliverable_type_id integer NOT NULL,
    status character varying(50) DEFAULT 'Draft'::character varying NOT NULL,
    due_date timestamp with time zone,
    delivered_at timestamp with time zone,
    delivered_by_user_id integer,
    file_attachment_ids jsonb,
    cloud_link_external_id character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.deliverables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deliverables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.deliverables
    ADD CONSTRAINT pk_deliverables PRIMARY KEY (id);

ALTER TABLE ONLY public.deliverables
    ADD CONSTRAINT fk_deliverables__jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.deliverables
    ADD CONSTRAINT fk_deliverables__projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.deliverables
    ADD CONSTRAINT fk_deliverables_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
