CREATE TABLE public.demand_forecasts (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    part_id integer NOT NULL,
    method integer NOT NULL,
    status integer NOT NULL,
    historical_periods integer NOT NULL,
    forecast_periods integer NOT NULL,
    smoothing_factor double precision,
    forecast_start_date timestamp with time zone NOT NULL,
    forecast_data_json jsonb,
    applied_to_master_schedule_id integer,
    created_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.demand_forecasts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demand_forecasts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.demand_forecasts
    ADD CONSTRAINT pk_demand_forecasts PRIMARY KEY (id);

ALTER TABLE ONLY public.demand_forecasts
    ADD CONSTRAINT fk_demand_forecasts__master_schedules_applied_to_master_schedul FOREIGN KEY (applied_to_master_schedule_id) REFERENCES public.master_schedules(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.demand_forecasts
    ADD CONSTRAINT fk_demand_forecasts__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
