CREATE TABLE public.device_enrollment_tokens (
    id integer NOT NULL,
    token_hash character varying(64) NOT NULL,
    target_user_id integer,
    is_shared boolean NOT NULL,
    issued_by_user_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    consumed_by_device_id integer
);

ALTER TABLE public.device_enrollment_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_enrollment_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.device_enrollment_tokens
    ADD CONSTRAINT pk_device_enrollment_tokens PRIMARY KEY (id);
