CREATE TABLE public.device_refresh_tokens (
    id integer NOT NULL,
    user_device_id integer NOT NULL,
    user_id integer NOT NULL,
    family_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    revoked_at timestamp with time zone
);

ALTER TABLE public.device_refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.device_refresh_tokens
    ADD CONSTRAINT pk_device_refresh_tokens PRIMARY KEY (id);

ALTER TABLE ONLY public.device_refresh_tokens
    ADD CONSTRAINT fk_device_refresh_tokens__user_devices_user_device_id FOREIGN KEY (user_device_id) REFERENCES public.user_devices(id) ON DELETE CASCADE;
