CREATE TABLE public.discovery_runs (
    id integer NOT NULL,
    run_by_user_id integer NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    answers_json jsonb NOT NULL,
    recommended_preset_id character varying(64) NOT NULL,
    applied_preset_id character varying(64) NOT NULL,
    recommended_confidence double precision NOT NULL,
    applied_deltas_json jsonb NOT NULL,
    ran_in_consultant_mode boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.discovery_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discovery_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.discovery_runs
    ADD CONSTRAINT pk_discovery_runs PRIMARY KEY (id);
