CREATE TABLE public.document_set_links (
    id integer NOT NULL,
    document_set_id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.document_set_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_set_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.document_set_links
    ADD CONSTRAINT pk_document_set_links PRIMARY KEY (id);

ALTER TABLE ONLY public.document_set_links
    ADD CONSTRAINT fk_document_set_links_document_sets_document_set_id FOREIGN KEY (document_set_id) REFERENCES public.document_sets(id) ON DELETE CASCADE;
