CREATE TABLE public.document_revisions (
    id integer NOT NULL,
    document_id integer NOT NULL,
    revision_number integer NOT NULL,
    file_attachment_id integer NOT NULL,
    change_description character varying(2000) NOT NULL,
    authored_by_id integer NOT NULL,
    reviewed_by_id integer,
    approved_by_id integer,
    approved_at timestamp with time zone,
    status integer NOT NULL
);

ALTER TABLE public.document_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.document_revisions
    ADD CONSTRAINT pk_document_revisions PRIMARY KEY (id);

ALTER TABLE ONLY public.document_revisions
    ADD CONSTRAINT fk_document_revisions__file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.document_revisions
    ADD CONSTRAINT fk_document_revisions_controlled_documents_document_id FOREIGN KEY (document_id) REFERENCES public.controlled_documents(id) ON DELETE CASCADE;
