CREATE TABLE public.document_embeddings (
    id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    chunk_text character varying(8000) NOT NULL,
    chunk_index integer NOT NULL,
    source_field character varying(100),
    embedding public.vector(384),
    model_name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.document_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.document_embeddings
    ADD CONSTRAINT pk_document_embeddings PRIMARY KEY (id);
