CREATE TABLE public.document_set_versions (
    id integer NOT NULL,
    document_set_id integer NOT NULL,
    version integer NOT NULL,
    file_name character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    size bigint NOT NULL,
    bucket_name character varying(100) NOT NULL,
    object_key character varying(500) NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    is_archived boolean DEFAULT false NOT NULL,
    created_by integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.document_set_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_set_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.document_set_versions
    ADD CONSTRAINT pk_document_set_versions PRIMARY KEY (id);

ALTER TABLE ONLY public.document_set_versions
    ADD CONSTRAINT fk_document_set_versions_document_sets_document_set_id FOREIGN KEY (document_set_id) REFERENCES public.document_sets(id) ON DELETE CASCADE;
