CREATE TABLE public.domain_event_failures (
    id integer NOT NULL,
    event_type character varying(200) NOT NULL,
    event_payload text NOT NULL,
    handler_name character varying(200) NOT NULL,
    error_message character varying(4000) NOT NULL,
    failed_at timestamp with time zone NOT NULL,
    retry_count integer NOT NULL,
    last_retry_at timestamp with time zone,
    resolved_at timestamp with time zone,
    status character varying(20) NOT NULL
);

ALTER TABLE public.domain_event_failures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domain_event_failures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.domain_event_failures
    ADD CONSTRAINT pk_domain_event_failures PRIMARY KEY (id);
