CREATE TABLE public.downtime_logs (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    work_center_id integer,
    reported_by_id integer,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    category character varying(50),
    downtime_reason_id integer,
    reason character varying(500) NOT NULL,
    resolution character varying(500),
    description character varying(2000),
    is_planned boolean NOT NULL,
    job_id integer,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.downtime_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.downtime_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.downtime_logs
    ADD CONSTRAINT pk_downtime_logs PRIMARY KEY (id);

ALTER TABLE ONLY public.downtime_logs
    ADD CONSTRAINT fk_downtime_logs__jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.downtime_logs
    ADD CONSTRAINT fk_downtime_logs__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.downtime_logs
    ADD CONSTRAINT fk_downtime_logs_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE RESTRICT;
