CREATE TABLE public.eco_affected_items (
    id integer NOT NULL,
    eco_id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    change_description character varying(500) NOT NULL,
    old_value jsonb,
    new_value jsonb,
    is_implemented boolean NOT NULL
);

ALTER TABLE public.eco_affected_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eco_affected_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.eco_affected_items
    ADD CONSTRAINT pk_eco_affected_items PRIMARY KEY (id);

ALTER TABLE ONLY public.eco_affected_items
    ADD CONSTRAINT fk_eco_affected_items__engineering_change_orders_eco_id FOREIGN KEY (eco_id) REFERENCES public.engineering_change_orders(id) ON DELETE CASCADE;
