CREATE TABLE public.ecommerce_order_syncs (
    id integer NOT NULL,
    integration_id integer NOT NULL,
    external_order_id character varying(200) NOT NULL,
    external_order_number character varying(200) NOT NULL,
    sales_order_id integer,
    status character varying(20) NOT NULL,
    error_message character varying(2000),
    order_data_json jsonb NOT NULL,
    imported_at timestamp with time zone NOT NULL
);

ALTER TABLE public.ecommerce_order_syncs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_order_syncs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ecommerce_order_syncs
    ADD CONSTRAINT pk_ecommerce_order_syncs PRIMARY KEY (id);

ALTER TABLE ONLY public.ecommerce_order_syncs
    ADD CONSTRAINT fk_ecommerce_order_syncs__sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ecommerce_order_syncs
    ADD CONSTRAINT fk_ecommerce_order_syncs_ecommerce_integrations_integration_id FOREIGN KEY (integration_id) REFERENCES public.ecommerce_integrations(id) ON DELETE CASCADE;
