CREATE TABLE public.ecommerce_integrations (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    platform character varying(30) NOT NULL,
    encrypted_credentials character varying(4000) NOT NULL,
    store_url character varying(500),
    is_active boolean NOT NULL,
    auto_import_orders boolean NOT NULL,
    sync_inventory boolean NOT NULL,
    last_sync_at timestamp with time zone,
    last_error character varying(2000),
    part_mappings_json jsonb,
    default_customer_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.ecommerce_integrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_integrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ecommerce_integrations
    ADD CONSTRAINT pk_ecommerce_integrations PRIMARY KEY (id);

ALTER TABLE ONLY public.ecommerce_integrations
    ADD CONSTRAINT fk_ecommerce_integrations_customers_default_customer_id FOREIGN KEY (default_customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
