CREATE TABLE public.edi_transactions (
    id integer NOT NULL,
    trading_partner_id integer NOT NULL,
    direction character varying(20) NOT NULL,
    transaction_set character varying(10) NOT NULL,
    control_number character varying(50),
    group_control_number character varying(50),
    transaction_control_number character varying(50),
    raw_payload text NOT NULL,
    parsed_data_json jsonb,
    payload_size_bytes integer,
    status character varying(30) NOT NULL,
    related_entity_type character varying(100),
    related_entity_id integer,
    received_at timestamp with time zone,
    processed_at timestamp with time zone,
    error_message character varying(2000),
    error_detail_json jsonb,
    retry_count integer NOT NULL,
    last_retry_at timestamp with time zone,
    acknowledgment_transaction_id integer,
    is_acknowledged boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.edi_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.edi_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.edi_transactions
    ADD CONSTRAINT pk_edi_transactions PRIMARY KEY (id);

ALTER TABLE ONLY public.edi_transactions
    ADD CONSTRAINT fk_edi_transactions_edi_trading_partners_trading_partner_id FOREIGN KEY (trading_partner_id) REFERENCES public.edi_trading_partners(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.edi_transactions
    ADD CONSTRAINT "fk_edi_transactions_edi_transactions_acknowledgment_transactio~" FOREIGN KEY (acknowledgment_transaction_id) REFERENCES public.edi_transactions(id) ON DELETE SET NULL;
