CREATE TABLE public.edi_mappings (
    id integer NOT NULL,
    trading_partner_id integer NOT NULL,
    transaction_set character varying(10) NOT NULL,
    name character varying(200) NOT NULL,
    field_mappings_json jsonb NOT NULL,
    value_translations_json jsonb NOT NULL,
    is_default boolean NOT NULL,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.edi_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.edi_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.edi_mappings
    ADD CONSTRAINT pk_edi_mappings PRIMARY KEY (id);

ALTER TABLE ONLY public.edi_mappings
    ADD CONSTRAINT fk_edi_mappings__edi_trading_partners_trading_partner_id FOREIGN KEY (trading_partner_id) REFERENCES public.edi_trading_partners(id) ON DELETE CASCADE;
