CREATE TABLE public.edi_trading_partners (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    customer_id integer,
    vendor_id integer,
    qualifier_id character varying(10) NOT NULL,
    qualifier_value character varying(100) NOT NULL,
    interchange_sender_id character varying(50),
    interchange_receiver_id character varying(50),
    application_sender_id character varying(50),
    application_receiver_id character varying(50),
    default_format character varying(20) NOT NULL,
    transport_method character varying(20) NOT NULL,
    transport_config_json jsonb,
    auto_process boolean NOT NULL,
    require_acknowledgment boolean NOT NULL,
    default_mapping_profile_id character varying(100),
    notes character varying(2000),
    is_active boolean NOT NULL,
    test_mode_partner_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.edi_trading_partners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.edi_trading_partners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.edi_trading_partners
    ADD CONSTRAINT pk_edi_trading_partners PRIMARY KEY (id);

ALTER TABLE ONLY public.edi_trading_partners
    ADD CONSTRAINT fk_edi_trading_partners__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.edi_trading_partners
    ADD CONSTRAINT fk_edi_trading_partners_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
