CREATE TABLE public.employee_profiles (
    id integer NOT NULL,
    user_id integer,
    first_name character varying(100),
    last_name character varying(100),
    work_email character varying(256),
    date_of_birth timestamp with time zone,
    gender character varying(50),
    street1 character varying(200),
    street2 character varying(200),
    city character varying(100),
    state character varying(100),
    zip_code character varying(20),
    country character varying(100),
    phone_number character varying(50),
    personal_email character varying(200),
    emergency_contact_name character varying(200),
    emergency_contact_phone character varying(50),
    emergency_contact_relationship character varying(100),
    start_date timestamp with time zone,
    department character varying(200),
    job_title character varying(200),
    employee_number character varying(50),
    pay_type integer,
    hourly_rate numeric(10,2),
    salary_amount numeric(12,2),
    w4_completed_at timestamp with time zone,
    state_withholding_completed_at timestamp with time zone,
    i9_completed_at timestamp with time zone,
    i9_expiration_date timestamp with time zone,
    direct_deposit_completed_at timestamp with time zone,
    workers_comp_acknowledged_at timestamp with time zone,
    handbook_acknowledged_at timestamp with time zone,
    onboarding_bypassed_at timestamp with time zone,
    ssn_protected text,
    bank_name character varying(200),
    bank_routing_protected text,
    bank_account_protected text,
    bank_account_type character varying(20),
    w4_filing_status character varying(20),
    w4_multiple_jobs boolean,
    w4_qualifying_children integer,
    w4_other_dependents integer,
    w4_other_income numeric(12,2),
    w4_deductions numeric(12,2),
    w4_extra_withholding numeric(12,2),
    w4_exempt_from_withholding boolean,
    state_filing_status character varying(20),
    state_allowances integer,
    state_additional_withholding numeric(12,2),
    state_exempt boolean,
    i9_citizenship_status character varying(4),
    i9_alien_reg_protected text,
    i9_i94_protected text,
    i9_foreign_passport_protected text,
    i9_foreign_passport_country character varying(100),
    i9_work_auth_expiry timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.employee_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.employee_profiles
    ADD CONSTRAINT pk_employee_profiles PRIMARY KEY (id);
