CREATE TABLE public.engineering_change_orders (
    id integer NOT NULL,
    eco_number character varying(30) NOT NULL,
    title character varying(200) NOT NULL,
    description character varying(2000) NOT NULL,
    change_type integer NOT NULL,
    status integer NOT NULL,
    priority integer NOT NULL,
    reason_for_change character varying(2000),
    impact_analysis character varying(2000),
    effective_date date,
    requested_by_id integer NOT NULL,
    approved_by_id integer,
    approved_at timestamp with time zone,
    implemented_at timestamp with time zone,
    implemented_by_id integer,
    approval_request_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.engineering_change_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.engineering_change_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.engineering_change_orders
    ADD CONSTRAINT pk_engineering_change_orders PRIMARY KEY (id);
