CREATE TABLE public.entity_notes (
    id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    text character varying(4000) NOT NULL,
    created_by integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.entity_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.entity_notes
    ADD CONSTRAINT pk_entity_notes PRIMARY KEY (id);

ALTER TABLE ONLY public.entity_notes
    ADD CONSTRAINT fk_entity_notes__asp_net_users_created_by FOREIGN KEY (created_by) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;
