CREATE TABLE public.entity_readiness_validators (
    id integer NOT NULL,
    entity_type character varying(64) NOT NULL,
    validator_id character varying(64) NOT NULL,
    predicate jsonb NOT NULL,
    applicability_predicate jsonb,
    display_name_key character varying(128) NOT NULL,
    missing_message_key character varying(128) NOT NULL,
    is_seed_data boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.entity_readiness_validators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_readiness_validators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.entity_readiness_validators
    ADD CONSTRAINT pk_entity_readiness_validators PRIMARY KEY (id);
