CREATE TABLE public.entity_cloud_links (
    id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    provider_id integer NOT NULL,
    folder_external_id character varying(500) NOT NULL,
    folder_path character varying(2000),
    folder_url character varying(2000),
    created_by_user_id uuid,
    created_via character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.entity_cloud_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_cloud_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.entity_cloud_links
    ADD CONSTRAINT pk_entity_cloud_links PRIMARY KEY (id);

ALTER TABLE ONLY public.entity_cloud_links
    ADD CONSTRAINT fk_entity_cloud_links_cloud_storage_providers_provider_id FOREIGN KEY (provider_id) REFERENCES public.cloud_storage_providers(id) ON DELETE RESTRICT;
