CREATE TABLE public.entity_capability_requirements (
    id integer NOT NULL,
    entity_type character varying(64) NOT NULL,
    capability_code character varying(64) NOT NULL,
    requirement_id character varying(64) NOT NULL,
    predicate jsonb NOT NULL,
    display_name_key character varying(128) NOT NULL,
    missing_message_key character varying(128) NOT NULL,
    sort_order integer NOT NULL,
    is_seed_data boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.entity_capability_requirements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_capability_requirements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.entity_capability_requirements
    ADD CONSTRAINT pk_entity_capability_requirements PRIMARY KEY (id);
