CREATE TABLE public.event_attendees (
    id integer NOT NULL,
    event_id integer NOT NULL,
    user_id integer NOT NULL,
    status character varying(20) NOT NULL,
    responded_at timestamp with time zone
);

ALTER TABLE public.event_attendees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_attendees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.event_attendees
    ADD CONSTRAINT pk_event_attendees PRIMARY KEY (id);

ALTER TABLE ONLY public.event_attendees
    ADD CONSTRAINT fk_event_attendees_events_event_id FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;
