CREATE TABLE public.events (
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    description character varying(2000),
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    location character varying(200),
    event_type character varying(20) NOT NULL,
    event_type_id integer,
    is_required boolean NOT NULL,
    created_by_user_id integer NOT NULL,
    is_cancelled boolean NOT NULL,
    reminder_sent_at timestamp with time zone,
    is_all_day boolean DEFAULT false NOT NULL,
    is_system_generated boolean DEFAULT false NOT NULL,
    status character varying(20),
    owner_user_id integer,
    completed_by_user_id integer,
    completed_at timestamp with time zone,
    waived_reason character varying(1000),
    is_blocking boolean DEFAULT false NOT NULL,
    acknowledged_by_user_id integer,
    acknowledged_at timestamp with time zone,
    evidence_document_set_id integer,
    evidence_url character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT pk_events PRIMARY KEY (id);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_events__calendar_event_types_event_type_id FOREIGN KEY (event_type_id) REFERENCES public.calendar_event_types(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_events__document_sets_evidence_document_set_id FOREIGN KEY (evidence_document_set_id) REFERENCES public.document_sets(id) ON DELETE SET NULL;
