CREATE TABLE public.exchange_rates (
    id integer NOT NULL,
    from_currency_id integer NOT NULL,
    to_currency_id integer NOT NULL,
    rate numeric(18,8) NOT NULL,
    effective_date date NOT NULL,
    source integer NOT NULL,
    fetched_at timestamp with time zone
);

ALTER TABLE public.exchange_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchange_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT pk_exchange_rates PRIMARY KEY (id);

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT fk_exchange_rates_currencies_from_currency_id FOREIGN KEY (from_currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT fk_exchange_rates_currencies_to_currency_id FOREIGN KEY (to_currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;
