CREATE TABLE public.expenses (
    id integer NOT NULL,
    user_id integer NOT NULL,
    job_id integer,
    amount numeric(18,2) NOT NULL,
    category character varying(100) NOT NULL,
    description character varying(1000) NOT NULL,
    receipt_file_id character varying(200),
    status integer NOT NULL,
    approved_by integer,
    approval_notes character varying(500),
    external_expense_id character varying(100),
    external_id text,
    external_ref text,
    provider text,
    expense_date timestamp with time zone NOT NULL,
    settlement_target character varying(30),
    vendor_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT pk_expenses PRIMARY KEY (id);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fk_expenses__jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fk_expenses__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;
