CREATE TABLE public.file_attachments (
    id integer NOT NULL,
    file_name character varying(500) NOT NULL,
    content_type character varying(200) NOT NULL,
    size bigint NOT NULL,
    bucket_name character varying(100) NOT NULL,
    object_key character varying(500) NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    uploaded_by_id integer NOT NULL,
    document_type text,
    expiration_date timestamp with time zone,
    part_revision_id integer,
    required_role character varying(100),
    sensitivity text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.file_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.file_attachments
    ADD CONSTRAINT pk_file_attachments PRIMARY KEY (id);

ALTER TABLE ONLY public.file_attachments
    ADD CONSTRAINT fk_file_attachments__part_revisions_part_revision_id FOREIGN KEY (part_revision_id) REFERENCES public.part_revisions(id) ON DELETE SET NULL;
