CREATE TABLE public.fmea_analyses (
    id integer NOT NULL,
    fmea_number character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    type integer NOT NULL,
    part_id integer,
    operation_id integer,
    status integer NOT NULL,
    prepared_by character varying(200),
    responsibility character varying(200),
    original_date date,
    revision_date date,
    revision_number integer NOT NULL,
    notes character varying(4000),
    ppap_submission_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.fmea_analyses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fmea_analyses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.fmea_analyses
    ADD CONSTRAINT pk_fmea_analyses PRIMARY KEY (id);

ALTER TABLE ONLY public.fmea_analyses
    ADD CONSTRAINT fk_fmea_analyses__operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.fmea_analyses
    ADD CONSTRAINT fk_fmea_analyses__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.fmea_analyses
    ADD CONSTRAINT fk_fmea_analyses__ppap_submissions_ppap_submission_id FOREIGN KEY (ppap_submission_id) REFERENCES public.ppap_submissions(id) ON DELETE SET NULL;
