CREATE TABLE public.fmea_items (
    id integer NOT NULL,
    fmea_id integer NOT NULL,
    item_number integer NOT NULL,
    process_step character varying(500),
    function character varying(500),
    failure_mode character varying(1000) NOT NULL,
    potential_effect character varying(1000) NOT NULL,
    severity integer NOT NULL,
    classification character varying(50),
    potential_cause character varying(1000),
    occurrence integer NOT NULL,
    current_prevention_controls character varying(2000),
    current_detection_controls character varying(2000),
    detection integer NOT NULL,
    recommended_action character varying(2000),
    responsible_user_id integer,
    target_completion_date date,
    action_taken character varying(2000),
    action_completed_at timestamp with time zone,
    revised_severity integer,
    revised_occurrence integer,
    revised_detection integer,
    capa_id integer
);

ALTER TABLE public.fmea_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fmea_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.fmea_items
    ADD CONSTRAINT pk_fmea_items PRIMARY KEY (id);

ALTER TABLE ONLY public.fmea_items
    ADD CONSTRAINT fk_fmea_items__asp_net_users_responsible_user_id FOREIGN KEY (responsible_user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.fmea_items
    ADD CONSTRAINT fk_fmea_items_corrective_actions_capa_id FOREIGN KEY (capa_id) REFERENCES public.corrective_actions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.fmea_items
    ADD CONSTRAINT fk_fmea_items_fmea_analyses_fmea_id FOREIGN KEY (fmea_id) REFERENCES public.fmea_analyses(id) ON DELETE CASCADE;
