CREATE TABLE public.follow_up_tasks (
    id integer NOT NULL,
    title character varying(300) NOT NULL,
    description character varying(2000),
    assigned_to_user_id integer NOT NULL,
    due_date timestamp with time zone,
    source_entity_type character varying(100) NOT NULL,
    source_entity_id integer NOT NULL,
    trigger_type character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    completed_at timestamp with time zone,
    dismissed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.follow_up_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_up_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.follow_up_tasks
    ADD CONSTRAINT pk_follow_up_tasks PRIMARY KEY (id);

ALTER TABLE ONLY public.follow_up_tasks
    ADD CONSTRAINT fk_follow_up_tasks__asp_net_users_assigned_to_user_id FOREIGN KEY (assigned_to_user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;
