CREATE TABLE public.forecast_overrides (
    id integer NOT NULL,
    demand_forecast_id integer NOT NULL,
    period_start timestamp with time zone NOT NULL,
    original_quantity numeric(18,4) NOT NULL,
    override_quantity numeric(18,4) NOT NULL,
    reason character varying(1000),
    overridden_by_user_id integer
);

ALTER TABLE public.forecast_overrides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forecast_overrides_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.forecast_overrides
    ADD CONSTRAINT pk_forecast_overrides PRIMARY KEY (id);

ALTER TABLE ONLY public.forecast_overrides
    ADD CONSTRAINT fk_forecast_overrides_demand_forecasts_demand_forecast_id FOREIGN KEY (demand_forecast_id) REFERENCES public.demand_forecasts(id) ON DELETE CASCADE;
