CREATE TABLE public.form_definition_versions (
    id integer NOT NULL,
    template_id integer,
    state_code character varying(10),
    form_definition_json jsonb NOT NULL,
    source_url character varying(500),
    sha256_hash character varying(64),
    effective_date timestamp with time zone NOT NULL,
    expiration_date timestamp with time zone,
    revision character varying(50) NOT NULL,
    extracted_at timestamp with time zone NOT NULL,
    field_count integer NOT NULL,
    is_active boolean NOT NULL,
    visual_comparison_json jsonb,
    visual_similarity_score double precision,
    visual_comparison_passed boolean,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text,
    CONSTRAINT ck_form_definition_versions_scope CHECK (((template_id IS NOT NULL) OR (state_code IS NOT NULL)))
);

ALTER TABLE public.form_definition_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_definition_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.form_definition_versions
    ADD CONSTRAINT pk_form_definition_versions PRIMARY KEY (id);

ALTER TABLE ONLY public.form_definition_versions
    ADD CONSTRAINT "fk_form_definition_versions_compliance_form_templates_template~" FOREIGN KEY (template_id) REFERENCES public.compliance_form_templates(id) ON DELETE CASCADE;
