CREATE TABLE public.gages (
    id integer NOT NULL,
    gage_number character varying(50) NOT NULL,
    description character varying(500) NOT NULL,
    gage_type character varying(100),
    manufacturer character varying(200),
    model character varying(200),
    serial_number character varying(100),
    calibration_interval_days integer NOT NULL,
    last_calibrated_at timestamp with time zone,
    next_calibration_due date,
    status integer NOT NULL,
    location_id integer,
    asset_id integer,
    accuracy_spec character varying(100),
    range_spec character varying(100),
    resolution character varying(100),
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.gages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.gages
    ADD CONSTRAINT pk_gages PRIMARY KEY (id);

ALTER TABLE ONLY public.gages
    ADD CONSTRAINT fk_gages__storage_locations_location_id FOREIGN KEY (location_id) REFERENCES public.storage_locations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.gages
    ADD CONSTRAINT fk_gages_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE SET NULL;
