CREATE TABLE public.holidays (
    id integer NOT NULL,
    working_calendar_id integer NOT NULL,
    date date NOT NULL,
    name character varying(100) NOT NULL,
    observed_date date,
    is_recurring boolean NOT NULL
);

ALTER TABLE public.holidays ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holidays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT pk_holidays PRIMARY KEY (id);

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT fk_holidays__working_calendars_working_calendar_id FOREIGN KEY (working_calendar_id) REFERENCES public.working_calendars(id) ON DELETE CASCADE;
