CREATE TABLE public.i18n_label_overrides (
    id integer NOT NULL,
    key character varying(400) NOT NULL,
    language_code character varying(10) NOT NULL,
    value character varying(2000) NOT NULL,
    is_machine_translated boolean NOT NULL,
    is_pending_translation boolean NOT NULL,
    source_language_code character varying(10),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.i18n_label_overrides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.i18n_label_overrides_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.i18n_label_overrides
    ADD CONSTRAINT pk_i18n_label_overrides PRIMARY KEY (id);
