CREATE TABLE public.icp_dimensions (
    id integer NOT NULL,
    icp_rubric_id integer NOT NULL,
    field_key character varying(100) NOT NULL,
    label character varying(200),
    match_spec jsonb,
    weight integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.icp_dimensions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.icp_dimensions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.icp_dimensions
    ADD CONSTRAINT pk_icp_dimensions PRIMARY KEY (id);

ALTER TABLE ONLY public.icp_dimensions
    ADD CONSTRAINT fk_icp_dimensions__icp_rubrics_icp_rubric_id FOREIGN KEY (icp_rubric_id) REFERENCES public.icp_rubrics(id) ON DELETE CASCADE;
