CREATE TABLE public.icp_rubrics (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    is_active boolean NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.icp_rubrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.icp_rubrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.icp_rubrics
    ADD CONSTRAINT pk_icp_rubrics PRIMARY KEY (id);
