CREATE TABLE public.idempotency_keys (
    id integer NOT NULL,
    scope character varying(120) NOT NULL,
    idempotency_key character varying(80) NOT NULL,
    request_fingerprint character varying(64) NOT NULL,
    status_code integer NOT NULL,
    content_type character varying(120),
    response_body text,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

ALTER TABLE public.idempotency_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.idempotency_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT pk_idempotency_keys PRIMARY KEY (id);
