CREATE TABLE public.identity_documents (
    id integer NOT NULL,
    user_id integer NOT NULL,
    document_type integer NOT NULL,
    file_attachment_id integer NOT NULL,
    verified_at timestamp with time zone,
    verified_by_id integer,
    expires_at timestamp with time zone,
    notes character varying(500),
    document_name character varying(200),
    issuing_authority character varying(200),
    document_number_protected text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.identity_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.identity_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.identity_documents
    ADD CONSTRAINT pk_identity_documents PRIMARY KEY (id);

ALTER TABLE ONLY public.identity_documents
    ADD CONSTRAINT fk_identity_documents_file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE CASCADE;
