CREATE TABLE public.inter_plant_transfer_lines (
    id integer NOT NULL,
    transfer_id integer NOT NULL,
    part_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    received_quantity numeric(18,4),
    from_location_id integer,
    to_location_id integer,
    lot_number character varying(100)
);

ALTER TABLE public.inter_plant_transfer_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inter_plant_transfer_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.inter_plant_transfer_lines
    ADD CONSTRAINT pk_inter_plant_transfer_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.inter_plant_transfer_lines
    ADD CONSTRAINT fk_inter_plant_transfer_lines__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.inter_plant_transfer_lines
    ADD CONSTRAINT fk_inter_plant_transfer_lines_inter_plant_transfers_transfer_id FOREIGN KEY (transfer_id) REFERENCES public.inter_plant_transfers(id) ON DELETE CASCADE;
