CREATE TABLE public.inter_plant_transfers (
    id integer NOT NULL,
    transfer_number character varying(50) NOT NULL,
    from_plant_id integer NOT NULL,
    to_plant_id integer NOT NULL,
    status integer NOT NULL,
    shipped_at timestamp with time zone,
    received_at timestamp with time zone,
    shipped_by_id integer,
    received_by_id integer,
    tracking_number character varying(200),
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.inter_plant_transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inter_plant_transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.inter_plant_transfers
    ADD CONSTRAINT pk_inter_plant_transfers PRIMARY KEY (id);

ALTER TABLE ONLY public.inter_plant_transfers
    ADD CONSTRAINT fk_inter_plant_transfers__plants_from_plant_id FOREIGN KEY (from_plant_id) REFERENCES public.plants(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.inter_plant_transfers
    ADD CONSTRAINT fk_inter_plant_transfers__plants_to_plant_id FOREIGN KEY (to_plant_id) REFERENCES public.plants(id) ON DELETE RESTRICT;
