CREATE TABLE public.integration_outbox_entries (
    id integer NOT NULL,
    provider character varying(50) NOT NULL,
    operation_key character varying(200) NOT NULL,
    idempotency_key character varying(200) NOT NULL,
    payload jsonb NOT NULL,
    status character varying(30) NOT NULL,
    attempt_count integer NOT NULL,
    max_attempts integer NOT NULL,
    next_attempt_at timestamp with time zone,
    last_attempt_at timestamp with time zone,
    sent_at timestamp with time zone,
    last_error character varying(4000),
    entity_type character varying(100),
    entity_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.integration_outbox_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.integration_outbox_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.integration_outbox_entries
    ADD CONSTRAINT pk_integration_outbox_entries PRIMARY KEY (id);
