CREATE TABLE public.invoices (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    invoice_number character varying(20) NOT NULL,
    customer_id integer NOT NULL,
    currency_id integer DEFAULT 1 NOT NULL,
    fx_rate numeric(18,8) DEFAULT 1.0 NOT NULL,
    sales_order_id integer,
    shipment_id integer,
    status integer NOT NULL,
    invoice_date timestamp with time zone NOT NULL,
    due_date timestamp with time zone NOT NULL,
    credit_terms integer,
    tax_rate numeric(8,6) NOT NULL,
    notes character varying(2000),
    customer_po character varying(50),
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT pk_invoices PRIMARY KEY (id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoices__sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoices__shipments_shipment_id FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoices_currencies_currency_id FOREIGN KEY (currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoices_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;
