CREATE TABLE public.invoice_lines (
    id integer NOT NULL,
    invoice_id integer NOT NULL,
    part_id integer,
    description character varying(500) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    line_number integer NOT NULL,
    tax_code text
);

ALTER TABLE public.invoice_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.invoice_lines
    ADD CONSTRAINT pk_invoice_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.invoice_lines
    ADD CONSTRAINT fk_invoice_lines__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.invoice_lines
    ADD CONSTRAINT fk_invoice_lines_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;
