CREATE TABLE public.item_burdens (
    id integer NOT NULL,
    item_id integer NOT NULL,
    costing_period_id integer NOT NULL,
    element integer NOT NULL,
    basis character varying(16) NOT NULL,
    value numeric(18,6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.item_burdens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_burdens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.item_burdens
    ADD CONSTRAINT pk_item_burdens PRIMARY KEY (id);

ALTER TABLE ONLY public.item_burdens
    ADD CONSTRAINT fk_item_burdens__parts_item_id FOREIGN KEY (item_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.item_burdens
    ADD CONSTRAINT fk_item_burdens__costing_periods_costing_period_id FOREIGN KEY (costing_period_id) REFERENCES public.costing_periods(id) ON DELETE CASCADE;

CREATE INDEX ix_item_burdens_item_id ON public.item_burdens (item_id);
CREATE INDEX ix_item_burdens_costing_period_id ON public.item_burdens (costing_period_id);
