CREATE TABLE public.item_standard_costs (
    id integer NOT NULL,
    item_id integer NOT NULL,
    costing_period_id integer NOT NULL,
    this_level_json text NOT NULL,
    rolled_up_json text NOT NULL,
    total_standard numeric(18,4) NOT NULL,
    standard_lot_size numeric(18,4) NOT NULL,
    cost_to_sell numeric(18,4),
    rolled_at timestamp with time zone,
    roll_version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.item_standard_costs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_standard_costs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.item_standard_costs
    ADD CONSTRAINT pk_item_standard_costs PRIMARY KEY (id);

ALTER TABLE ONLY public.item_standard_costs
    ADD CONSTRAINT fk_item_standard_costs__parts_item_id FOREIGN KEY (item_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.item_standard_costs
    ADD CONSTRAINT fk_item_standard_costs__costing_periods_costing_period_id FOREIGN KEY (costing_period_id) REFERENCES public.costing_periods(id) ON DELETE CASCADE;

CREATE INDEX ix_item_standard_costs_item_id ON public.item_standard_costs (item_id);
CREATE INDEX ix_item_standard_costs_costing_period_id ON public.item_standard_costs (costing_period_id);
