CREATE TABLE public.job_operations (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    job_id integer NOT NULL,
    operation_id integer,
    step_number integer NOT NULL,
    title character varying(200) NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    completed_quantity numeric(10,2) DEFAULT 0.0 NOT NULL,
    scrap_quantity numeric(10,2) DEFAULT 0.0 NOT NULL,
    est_setup_minutes numeric(10,2) DEFAULT 0.0 NOT NULL,
    est_run_minutes_each numeric(14,6) DEFAULT 0.0 NOT NULL,
    est_run_minutes_lot numeric(10,2) DEFAULT 0.0 NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    completed_by_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.job_operations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_operations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_operations
    ADD CONSTRAINT pk_job_operations PRIMARY KEY (id);

ALTER TABLE ONLY public.job_operations
    ADD CONSTRAINT ck_job_operations_quantities CHECK (((completed_quantity >= (0)::numeric) AND (scrap_quantity >= (0)::numeric)));

ALTER TABLE ONLY public.job_operations
    ADD CONSTRAINT fk_job_operations_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.job_operations
    ADD CONSTRAINT fk_job_operations_operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;
