CREATE TABLE public.job_notes (
    id integer NOT NULL,
    job_id integer NOT NULL,
    text character varying(4000) NOT NULL,
    created_by integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.job_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_notes
    ADD CONSTRAINT pk_job_notes PRIMARY KEY (id);

ALTER TABLE ONLY public.job_notes
    ADD CONSTRAINT fk_job_notes__asp_net_users_created_by FOREIGN KEY (created_by) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.job_notes
    ADD CONSTRAINT fk_job_notes_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;
