CREATE TABLE public.job_activity_logs (
    id integer NOT NULL,
    job_id integer NOT NULL,
    user_id integer,
    action integer NOT NULL,
    field_name character varying(100),
    old_value character varying(1000),
    new_value character varying(1000),
    description character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    work_center_id integer,
    operation_id integer
);

ALTER TABLE public.job_activity_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_activity_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_activity_logs
    ADD CONSTRAINT pk_job_activity_logs PRIMARY KEY (id);

ALTER TABLE ONLY public.job_activity_logs
    ADD CONSTRAINT fk_job_activity_logs__operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.job_activity_logs
    ADD CONSTRAINT fk_job_activity_logs__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.job_activity_logs
    ADD CONSTRAINT fk_job_activity_logs_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;
