CREATE TABLE public.job_operation_events (
    id integer NOT NULL,
    job_operation_id integer NOT NULL,
    kind character varying(20) NOT NULL,
    quantity numeric(10,2) NOT NULL,
    reason_code character varying(50),
    user_id integer NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE public.job_operation_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_operation_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_operation_events
    ADD CONSTRAINT pk_job_operation_events PRIMARY KEY (id);

ALTER TABLE ONLY public.job_operation_events
    ADD CONSTRAINT ck_job_operation_events_kind CHECK (((kind)::text = ANY (ARRAY['Good'::text, 'Scrap'::text, 'Rework'::text])));

ALTER TABLE ONLY public.job_operation_events
    ADD CONSTRAINT ck_job_operation_events_quantity CHECK ((quantity <> (0)::numeric));

ALTER TABLE ONLY public.job_operation_events
    ADD CONSTRAINT fk_job_operation_events_job_operations_job_operation_id FOREIGN KEY (job_operation_id) REFERENCES public.job_operations(id) ON DELETE CASCADE;
