CREATE TABLE public.job_subtasks (
    id integer NOT NULL,
    job_id integer NOT NULL,
    text character varying(500) NOT NULL,
    is_completed boolean NOT NULL,
    assignee_id integer,
    sort_order integer NOT NULL,
    completed_at timestamp with time zone,
    completed_by_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.job_subtasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_subtasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_subtasks
    ADD CONSTRAINT pk_job_subtasks PRIMARY KEY (id);

ALTER TABLE ONLY public.job_subtasks
    ADD CONSTRAINT fk_job_subtasks_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;
