CREATE TABLE public.job_parts (
    id integer NOT NULL,
    job_id integer NOT NULL,
    part_id integer NOT NULL,
    quantity numeric(10,2) NOT NULL,
    notes character varying(500),
    job_id1 integer
);

ALTER TABLE public.job_parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_parts
    ADD CONSTRAINT pk_job_parts PRIMARY KEY (id);

ALTER TABLE ONLY public.job_parts
    ADD CONSTRAINT fk_job_parts__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.job_parts
    ADD CONSTRAINT fk_job_parts_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.job_parts
    ADD CONSTRAINT fk_job_parts_jobs_job_id1 FOREIGN KEY (job_id1) REFERENCES public.jobs(id);
