CREATE TABLE public.job_stages (
    id integer NOT NULL,
    track_type_id integer NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(50) NOT NULL,
    sort_order integer NOT NULL,
    color character varying(20) NOT NULL,
    wiplimit integer,
    accounting_document_type integer,
    is_irreversible boolean NOT NULL,
    is_shop_floor boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.job_stages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_stages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_stages
    ADD CONSTRAINT pk_job_stages PRIMARY KEY (id);

ALTER TABLE ONLY public.job_stages
    ADD CONSTRAINT fk_job_stages__track_types_track_type_id FOREIGN KEY (track_type_id) REFERENCES public.track_types(id) ON DELETE CASCADE;
