CREATE TABLE public.job_links (
    id integer NOT NULL,
    source_job_id integer NOT NULL,
    target_job_id integer NOT NULL,
    link_type integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE public.job_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.job_links
    ADD CONSTRAINT pk_job_links PRIMARY KEY (id);

ALTER TABLE ONLY public.job_links
    ADD CONSTRAINT fk_job_links_jobs_source_job_id FOREIGN KEY (source_job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.job_links
    ADD CONSTRAINT fk_job_links_jobs_target_job_id FOREIGN KEY (target_job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;
