CREATE TABLE public.jobs (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    job_number character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    description character varying(2000),
    track_type_id integer NOT NULL,
    current_stage_id integer NOT NULL,
    assignee_id integer,
    priority integer NOT NULL,
    customer_id integer,
    due_date timestamp with time zone,
    start_date timestamp with time zone,
    completed_date timestamp with time zone,
    is_archived boolean NOT NULL,
    board_position integer NOT NULL,
    part_id integer,
    parent_job_id integer,
    sales_order_line_id integer,
    mrp_planned_order_id integer,
    bom_revision_id_at_release integer,
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    iteration_count integer NOT NULL,
    iteration_notes text,
    is_internal boolean NOT NULL,
    internal_project_type_id integer,
    estimated_material_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    estimated_labor_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    estimated_burden_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    estimated_subcontract_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    quoted_price numeric(18,4) DEFAULT 0.0 NOT NULL,
    disposition integer,
    disposition_notes character varying(2000),
    disposition_at timestamp with time zone,
    custom_field_values jsonb,
    engagement_type_id integer,
    project_phase_id integer,
    billing_model integer,
    retainer_hours numeric(10,2),
    retainer_balance_hours numeric(10,2),
    sow_id integer,
    cover_photo_file_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT pk_jobs PRIMARY KEY (id);

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs__job_stages_current_stage_id FOREIGN KEY (current_stage_id) REFERENCES public.job_stages(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs__mrp_planned_orders_mrp_planned_order_id FOREIGN KEY (mrp_planned_order_id) REFERENCES public.mrp_planned_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs__sales_order_lines_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES public.sales_order_lines(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs__track_types_track_type_id FOREIGN KEY (track_type_id) REFERENCES public.track_types(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_bom_revisions_bom_revision_id_at_release FOREIGN KEY (bom_revision_id_at_release) REFERENCES public.bom_revisions(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_file_attachments_cover_photo_file_id FOREIGN KEY (cover_photo_file_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_jobs_parent_job_id FOREIGN KEY (parent_job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;
