CREATE TABLE public.kanban_trigger_logs (
    id integer NOT NULL,
    kanban_card_id integer NOT NULL,
    trigger_type integer NOT NULL,
    triggered_at timestamp with time zone NOT NULL,
    fulfilled_at timestamp with time zone,
    requested_quantity numeric(18,4) NOT NULL,
    fulfilled_quantity numeric(18,4),
    order_id integer,
    order_type character varying(50),
    triggered_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.kanban_trigger_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kanban_trigger_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.kanban_trigger_logs
    ADD CONSTRAINT pk_kanban_trigger_logs PRIMARY KEY (id);

ALTER TABLE ONLY public.kanban_trigger_logs
    ADD CONSTRAINT fk_kanban_trigger_logs_kanban_cards_kanban_card_id FOREIGN KEY (kanban_card_id) REFERENCES public.kanban_cards(id) ON DELETE CASCADE;
