CREATE TABLE public.kanban_cards (
    id integer NOT NULL,
    card_number character varying(20) NOT NULL,
    part_id integer NOT NULL,
    work_center_id integer NOT NULL,
    storage_location_id integer,
    bin_quantity numeric(18,4) NOT NULL,
    number_of_bins integer NOT NULL,
    status integer NOT NULL,
    supply_source integer NOT NULL,
    supply_vendor_id integer,
    supply_work_center_id integer,
    lead_time_days numeric(10,2),
    last_triggered_at timestamp with time zone,
    last_replenished_at timestamp with time zone,
    active_order_id integer,
    active_order_type character varying(50),
    trigger_count integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.kanban_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kanban_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.kanban_cards
    ADD CONSTRAINT pk_kanban_cards PRIMARY KEY (id);

ALTER TABLE ONLY public.kanban_cards
    ADD CONSTRAINT fk_kanban_cards__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.kanban_cards
    ADD CONSTRAINT fk_kanban_cards__storage_locations_storage_location_id FOREIGN KEY (storage_location_id) REFERENCES public.storage_locations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.kanban_cards
    ADD CONSTRAINT fk_kanban_cards__vendors_supply_vendor_id FOREIGN KEY (supply_vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.kanban_cards
    ADD CONSTRAINT fk_kanban_cards__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE RESTRICT;
