CREATE TABLE public.kiosk_terminals (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    device_token character varying(100) NOT NULL,
    team_id integer NOT NULL,
    configured_by_user_id integer NOT NULL,
    is_active boolean NOT NULL,
    work_center_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.kiosk_terminals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kiosk_terminals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.kiosk_terminals
    ADD CONSTRAINT pk_kiosk_terminals PRIMARY KEY (id);

ALTER TABLE ONLY public.kiosk_terminals
    ADD CONSTRAINT fk_kiosk_terminals__teams_team_id FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.kiosk_terminals
    ADD CONSTRAINT fk_kiosk_terminals__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;
