CREATE TABLE public.labor_rates (
    id integer NOT NULL,
    user_id integer NOT NULL,
    standard_rate_per_hour numeric(18,4) NOT NULL,
    actual_rate_per_hour numeric,
    overtime_rate_per_hour numeric(18,4) NOT NULL,
    doubletime_rate_per_hour numeric(18,4),
    effective_from date NOT NULL,
    effective_to date,
    notes character varying(500)
);

ALTER TABLE public.labor_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labor_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.labor_rates
    ADD CONSTRAINT pk_labor_rates PRIMARY KEY (id);

ALTER TABLE ONLY public.labor_rates
    ADD CONSTRAINT fk_labor_rates__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;
