CREATE TABLE public.lead_sources (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    code character varying(100) NOT NULL,
    quality_score integer NOT NULL,
    last_scored_at timestamp with time zone,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.lead_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lead_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.lead_sources
    ADD CONSTRAINT pk_lead_sources PRIMARY KEY (id);
