CREATE TABLE public.leads (
    id integer NOT NULL,
    company_name character varying(200) NOT NULL,
    contact_name character varying(200),
    email character varying(200),
    phone character varying(50),
    source character varying(100),
    status character varying(40) NOT NULL,
    notes character varying(2000),
    follow_up_date timestamp with time zone,
    lost_reason character varying(500),
    converted_customer_id integer,
    custom_field_values jsonb,
    created_by integer NOT NULL,
    engagement_shape integer DEFAULT 0 NOT NULL,
    campaign_id integer,
    outreach_state character varying(40) DEFAULT ''::character varying NOT NULL,
    lead_source_id integer,
    icp_score integer,
    assigned_to_user_id integer,
    account_id integer,
    capability_fit character varying(40) DEFAULT ''::character varying NOT NULL,
    nda_state character varying(40) DEFAULT ''::character varying NOT NULL,
    nda_signed_at timestamp with time zone,
    nda_expires_at timestamp with time zone,
    export_control character varying(40) DEFAULT ''::character varying NOT NULL,
    secondary_owner_user_id integer,
    part_class_code character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.leads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT pk_leads PRIMARY KEY (id);

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT fk_leads__lead_sources_lead_source_id FOREIGN KEY (lead_source_id) REFERENCES public.lead_sources(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT fk_leads__outreach_campaigns_campaign_id FOREIGN KEY (campaign_id) REFERENCES public.outreach_campaigns(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT fk_leads_accounts_account_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT fk_leads_customers_converted_customer_id FOREIGN KEY (converted_customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
