CREATE TABLE public.lead_outreach_preferences (
    id integer NOT NULL,
    lead_id integer NOT NULL,
    email_opt_out boolean NOT NULL,
    email_opt_out_at timestamp with time zone,
    email_opt_out_source character varying(200),
    call_opt_out boolean NOT NULL,
    call_opt_out_at timestamp with time zone,
    call_opt_out_source character varying(200),
    sms_opt_out boolean NOT NULL,
    sms_opt_out_at timestamp with time zone,
    sms_opt_out_source character varying(200),
    cooldown_until timestamp with time zone,
    cooldown_reason_code character varying(100),
    cooldown_notes character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.lead_outreach_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lead_outreach_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.lead_outreach_preferences
    ADD CONSTRAINT pk_lead_outreach_preferences PRIMARY KEY (id);

ALTER TABLE ONLY public.lead_outreach_preferences
    ADD CONSTRAINT fk_lead_outreach_preferences_leads_lead_id FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE;
