CREATE TABLE public.leave_balances (
    id integer NOT NULL,
    user_id integer NOT NULL,
    policy_id integer NOT NULL,
    balance numeric(10,2) NOT NULL,
    used_this_year numeric(10,2) NOT NULL,
    accrued_this_year numeric(10,2) NOT NULL,
    last_accrual_date timestamp with time zone NOT NULL
);

ALTER TABLE public.leave_balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_balances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.leave_balances
    ADD CONSTRAINT pk_leave_balances PRIMARY KEY (id);

ALTER TABLE ONLY public.leave_balances
    ADD CONSTRAINT fk_leave_balances__leave_policies_policy_id FOREIGN KEY (policy_id) REFERENCES public.leave_policies(id) ON DELETE RESTRICT;
