CREATE TABLE public.leave_policies (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    accrual_rate_per_pay_period numeric(10,4) NOT NULL,
    max_balance numeric(10,2),
    carry_over_limit numeric(10,2),
    accrue_from_hire_date boolean NOT NULL,
    waiting_period_days integer,
    is_paid_leave boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.leave_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.leave_policies
    ADD CONSTRAINT pk_leave_policies PRIMARY KEY (id);
