CREATE TABLE public.leave_requests (
    id integer NOT NULL,
    user_id integer NOT NULL,
    policy_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    hours numeric(10,2) NOT NULL,
    status integer NOT NULL,
    approved_by_id integer,
    decided_at timestamp with time zone,
    reason character varying(1000),
    denial_reason character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.leave_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT pk_leave_requests PRIMARY KEY (id);

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT fk_leave_requests_leave_policies_policy_id FOREIGN KEY (policy_id) REFERENCES public.leave_policies(id) ON DELETE RESTRICT;
