CREATE TABLE public.lot_consumptions (
    id integer NOT NULL,
    consumed_lot_id integer NOT NULL,
    produced_lot_id integer NOT NULL,
    quantity numeric(18,6) NOT NULL,
    job_id integer,
    production_run_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.lot_consumptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lot_consumptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.lot_consumptions
    ADD CONSTRAINT pk_lot_consumptions PRIMARY KEY (id);

ALTER TABLE ONLY public.lot_consumptions
    ADD CONSTRAINT fk_lot_consumptions__lot_records_consumed_lot_id FOREIGN KEY (consumed_lot_id) REFERENCES public.lot_records(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.lot_consumptions
    ADD CONSTRAINT fk_lot_consumptions__lot_records_produced_lot_id FOREIGN KEY (produced_lot_id) REFERENCES public.lot_records(id) ON DELETE RESTRICT;
