CREATE TABLE public.lot_records (
    id integer NOT NULL,
    lot_number character varying(100) NOT NULL,
    part_id integer NOT NULL,
    job_id integer,
    production_run_id integer,
    purchase_order_line_id integer,
    quantity numeric(18,4) NOT NULL,
    expiration_date timestamp with time zone,
    supplier_lot_number character varying(100),
    notes character varying(2000),
    sales_order_stage_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.lot_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lot_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.lot_records
    ADD CONSTRAINT pk_lot_records PRIMARY KEY (id);

ALTER TABLE ONLY public.lot_records
    ADD CONSTRAINT fk_lot_records__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.lot_records
    ADD CONSTRAINT fk_lot_records__production_runs_production_run_id FOREIGN KEY (production_run_id) REFERENCES public.production_runs(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.lot_records
    ADD CONSTRAINT fk_lot_records__purchase_order_lines_purchase_order_line_id FOREIGN KEY (purchase_order_line_id) REFERENCES public.purchase_order_lines(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.lot_records
    ADD CONSTRAINT fk_lot_records_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.lot_records
    ADD CONSTRAINT fk_lot_records_sales_order_stages_sales_order_stage_id FOREIGN KEY (sales_order_stage_id) REFERENCES public.sales_order_stages(id) ON DELETE SET NULL;
