CREATE TABLE public.machine_data_points (
    id integer NOT NULL,
    tag_id integer NOT NULL,
    work_center_id integer NOT NULL,
    value character varying(500) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    quality character varying(20) NOT NULL
);

ALTER TABLE public.machine_data_points ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_data_points_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.machine_data_points
    ADD CONSTRAINT pk_machine_data_points PRIMARY KEY (id);

ALTER TABLE ONLY public.machine_data_points
    ADD CONSTRAINT fk_machine_data_points__machine_tags_tag_id FOREIGN KEY (tag_id) REFERENCES public.machine_tags(id) ON DELETE CASCADE;
