CREATE TABLE public.machine_connections (
    id integer NOT NULL,
    work_center_id integer NOT NULL,
    name character varying(200) NOT NULL,
    opc_ua_endpoint character varying(500) NOT NULL,
    security_policy character varying(100),
    auth_type character varying(50),
    encrypted_credentials character varying(2000),
    status character varying(20) NOT NULL,
    last_connected_at timestamp with time zone,
    last_error character varying(2000),
    poll_interval_ms integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.machine_connections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_connections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.machine_connections
    ADD CONSTRAINT pk_machine_connections PRIMARY KEY (id);

ALTER TABLE ONLY public.machine_connections
    ADD CONSTRAINT fk_machine_connections__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE RESTRICT;
