CREATE TABLE public.machine_tags (
    id integer NOT NULL,
    connection_id integer NOT NULL,
    tag_name character varying(200) NOT NULL,
    opc_node_id character varying(500) NOT NULL,
    data_type character varying(50) NOT NULL,
    unit character varying(50),
    warning_threshold_low numeric(18,4),
    warning_threshold_high numeric(18,4),
    alarm_threshold_low numeric(18,4),
    alarm_threshold_high numeric(18,4),
    is_active boolean NOT NULL
);

ALTER TABLE public.machine_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.machine_tags
    ADD CONSTRAINT pk_machine_tags PRIMARY KEY (id);

ALTER TABLE ONLY public.machine_tags
    ADD CONSTRAINT fk_machine_tags_machine_connections_connection_id FOREIGN KEY (connection_id) REFERENCES public.machine_connections(id) ON DELETE CASCADE;
