CREATE TABLE public.maintenance_schedules (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    title character varying(200) NOT NULL,
    description character varying(2000),
    interval_days integer NOT NULL,
    interval_hours numeric(18,2),
    last_performed_at timestamp with time zone,
    next_due_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    maintenance_job_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.maintenance_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.maintenance_schedules
    ADD CONSTRAINT pk_maintenance_schedules PRIMARY KEY (id);

ALTER TABLE ONLY public.maintenance_schedules
    ADD CONSTRAINT fk_maintenance_schedules_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.maintenance_schedules
    ADD CONSTRAINT fk_maintenance_schedules_jobs_maintenance_job_id FOREIGN KEY (maintenance_job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;
