CREATE TABLE public.maintenance_logs (
    id integer NOT NULL,
    maintenance_schedule_id integer NOT NULL,
    performed_by_id integer NOT NULL,
    performed_at timestamp with time zone NOT NULL,
    hours_at_service numeric(18,2),
    notes character varying(2000),
    cost numeric(18,2)
);

ALTER TABLE public.maintenance_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.maintenance_logs
    ADD CONSTRAINT pk_maintenance_logs PRIMARY KEY (id);

ALTER TABLE ONLY public.maintenance_logs
    ADD CONSTRAINT fk_maintenance_logs__maintenance_schedules_maintenance_schedule FOREIGN KEY (maintenance_schedule_id) REFERENCES public.maintenance_schedules(id) ON DELETE CASCADE;
