CREATE TABLE public.master_schedule_lines (
    id integer NOT NULL,
    master_schedule_id integer NOT NULL,
    part_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    due_date timestamp with time zone NOT NULL,
    notes character varying(1000)
);

ALTER TABLE public.master_schedule_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_schedule_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.master_schedule_lines
    ADD CONSTRAINT pk_master_schedule_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.master_schedule_lines
    ADD CONSTRAINT fk_master_schedule_lines__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.master_schedule_lines
    ADD CONSTRAINT fk_master_schedule_lines_master_schedules_master_schedule_id FOREIGN KEY (master_schedule_id) REFERENCES public.master_schedules(id) ON DELETE CASCADE;
