CREATE TABLE public.material_issues (
    id integer NOT NULL,
    job_id integer NOT NULL,
    part_id integer NOT NULL,
    operation_id integer,
    quantity numeric(18,4) NOT NULL,
    unit_cost numeric(18,4) NOT NULL,
    issued_by_id integer NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    bin_content_id integer,
    storage_location_id integer,
    lot_number character varying(100),
    issue_type integer NOT NULL,
    return_reason_id integer,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.material_issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT pk_material_issues PRIMARY KEY (id);

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fk_material_issues__asp_net_users_issued_by_id FOREIGN KEY (issued_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fk_material_issues__operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fk_material_issues__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fk_material_issues__storage_locations_storage_location_id FOREIGN KEY (storage_location_id) REFERENCES public.storage_locations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fk_material_issues_bin_contents_bin_content_id FOREIGN KEY (bin_content_id) REFERENCES public.bin_contents(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fk_material_issues_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;
