CREATE TABLE public.mfa_recovery_codes (
    id integer NOT NULL,
    user_id integer NOT NULL,
    code_hash character varying(256) NOT NULL,
    is_used boolean NOT NULL,
    used_at timestamp with time zone,
    used_from_ip character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.mfa_recovery_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mfa_recovery_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.mfa_recovery_codes
    ADD CONSTRAINT pk_mfa_recovery_codes PRIMARY KEY (id);
