CREATE TABLE public.minimum_wage_rates (
    id integer NOT NULL,
    state_code character varying(2),
    rate_per_hour numeric(18,2) NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    description character varying(256),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.minimum_wage_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.minimum_wage_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.minimum_wage_rates
    ADD CONSTRAINT pk_minimum_wage_rates PRIMARY KEY (id);

CREATE INDEX ix_minimum_wage_rates_state_code ON public.minimum_wage_rates USING btree (state_code);
