CREATE TABLE public.ml_models (
    id integer NOT NULL,
    model_id character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    model_type character varying(50) NOT NULL,
    version character varying(50) NOT NULL,
    status integer NOT NULL,
    trained_at timestamp with time zone NOT NULL,
    training_sample_count integer NOT NULL,
    accuracy numeric(5,4),
    "precision" numeric(5,4),
    recall numeric(5,4),
    f1_score numeric(5,4),
    hyperparameters_json jsonb,
    feature_list_json jsonb,
    model_artifact_path character varying(500),
    work_center_id integer,
    prediction_type character varying(100) NOT NULL
);

ALTER TABLE public.ml_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ml_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ml_models
    ADD CONSTRAINT pk_ml_models PRIMARY KEY (id);

ALTER TABLE ONLY public.ml_models
    ADD CONSTRAINT fk_ml_models__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;
