CREATE TABLE public.mrp_runs (
    id integer NOT NULL,
    run_number character varying(20) NOT NULL,
    run_type integer NOT NULL,
    status integer NOT NULL,
    is_simulation boolean NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    planning_horizon_days integer NOT NULL,
    total_demand_count integer NOT NULL,
    total_supply_count integer NOT NULL,
    planned_order_count integer NOT NULL,
    exception_count integer NOT NULL,
    error_message character varying(2000),
    initiated_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.mrp_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mrp_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.mrp_runs
    ADD CONSTRAINT pk_mrp_runs PRIMARY KEY (id);
