CREATE TABLE public.mrp_exceptions (
    id integer NOT NULL,
    mrp_run_id integer NOT NULL,
    part_id integer NOT NULL,
    exception_type integer NOT NULL,
    message character varying(1000) NOT NULL,
    suggested_action character varying(1000),
    is_resolved boolean NOT NULL,
    resolved_by_user_id integer,
    resolved_at timestamp with time zone,
    resolution_notes character varying(2000)
);

ALTER TABLE public.mrp_exceptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mrp_exceptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.mrp_exceptions
    ADD CONSTRAINT pk_mrp_exceptions PRIMARY KEY (id);

ALTER TABLE ONLY public.mrp_exceptions
    ADD CONSTRAINT fk_mrp_exceptions__mrp_runs_mrp_run_id FOREIGN KEY (mrp_run_id) REFERENCES public.mrp_runs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mrp_exceptions
    ADD CONSTRAINT fk_mrp_exceptions__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
