CREATE TABLE public.mrp_supplies (
    id integer NOT NULL,
    mrp_run_id integer NOT NULL,
    part_id integer NOT NULL,
    source integer NOT NULL,
    source_entity_id integer,
    quantity numeric(18,4) NOT NULL,
    available_date timestamp with time zone NOT NULL,
    allocated_quantity numeric(18,4) NOT NULL
);

ALTER TABLE public.mrp_supplies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mrp_supplies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.mrp_supplies
    ADD CONSTRAINT pk_mrp_supplies PRIMARY KEY (id);

ALTER TABLE ONLY public.mrp_supplies
    ADD CONSTRAINT fk_mrp_supplies__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.mrp_supplies
    ADD CONSTRAINT fk_mrp_supplies_mrp_runs_mrp_run_id FOREIGN KEY (mrp_run_id) REFERENCES public.mrp_runs(id) ON DELETE CASCADE;
