CREATE TABLE public.mrp_demands (
    id integer NOT NULL,
    mrp_run_id integer NOT NULL,
    part_id integer NOT NULL,
    source integer NOT NULL,
    source_entity_id integer,
    quantity numeric(18,4) NOT NULL,
    required_date timestamp with time zone NOT NULL,
    is_dependent boolean NOT NULL,
    parent_planned_order_id integer,
    bom_level integer NOT NULL
);

ALTER TABLE public.mrp_demands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mrp_demands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.mrp_demands
    ADD CONSTRAINT pk_mrp_demands PRIMARY KEY (id);

ALTER TABLE ONLY public.mrp_demands
    ADD CONSTRAINT fk_mrp_demands__mrp_planned_orders_parent_planned_order_id FOREIGN KEY (parent_planned_order_id) REFERENCES public.mrp_planned_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.mrp_demands
    ADD CONSTRAINT fk_mrp_demands__mrp_runs_mrp_run_id FOREIGN KEY (mrp_run_id) REFERENCES public.mrp_runs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mrp_demands
    ADD CONSTRAINT fk_mrp_demands__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
