CREATE TABLE public.mrp_planned_orders (
    id integer NOT NULL,
    mrp_run_id integer NOT NULL,
    part_id integer NOT NULL,
    order_type integer NOT NULL,
    status integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    start_date timestamp with time zone NOT NULL,
    due_date timestamp with time zone NOT NULL,
    is_firmed boolean NOT NULL,
    released_purchase_order_id integer,
    released_job_id integer,
    parent_planned_order_id integer,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.mrp_planned_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mrp_planned_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.mrp_planned_orders
    ADD CONSTRAINT pk_mrp_planned_orders PRIMARY KEY (id);

ALTER TABLE ONLY public.mrp_planned_orders
    ADD CONSTRAINT fk_mrp_planned_orders__mrp_runs_mrp_run_id FOREIGN KEY (mrp_run_id) REFERENCES public.mrp_runs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.mrp_planned_orders
    ADD CONSTRAINT fk_mrp_planned_orders__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.mrp_planned_orders
    ADD CONSTRAINT fk_mrp_planned_orders__purchase_orders_released_purchase_order_ FOREIGN KEY (released_purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.mrp_planned_orders
    ADD CONSTRAINT fk_mrp_planned_orders_jobs_released_job_id FOREIGN KEY (released_job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.mrp_planned_orders
    ADD CONSTRAINT "fk_mrp_planned_orders_mrp_planned_orders_parent_planned_order_~" FOREIGN KEY (parent_planned_order_id) REFERENCES public.mrp_planned_orders(id) ON DELETE SET NULL;
