CREATE TABLE public.non_conformances (
    id integer NOT NULL,
    ncr_number character varying(20) NOT NULL,
    type integer NOT NULL,
    part_id integer NOT NULL,
    job_id integer,
    production_run_id integer,
    lot_number character varying(100),
    sales_order_line_id integer,
    purchase_order_line_id integer,
    qc_inspection_id integer,
    detected_by_id integer NOT NULL,
    detected_at timestamp with time zone NOT NULL,
    detected_at_stage integer NOT NULL,
    description character varying(4000) NOT NULL,
    affected_quantity numeric(18,4) NOT NULL,
    defective_quantity numeric(18,4),
    containment_actions character varying(4000),
    containment_by_id integer,
    containment_at timestamp with time zone,
    disposition_code integer,
    disposition_by_id integer,
    disposition_at timestamp with time zone,
    disposition_notes character varying(4000),
    rework_instructions character varying(4000),
    material_cost numeric(18,2),
    labor_cost numeric(18,2),
    total_cost_impact numeric(18,2),
    status integer NOT NULL,
    capa_id integer,
    customer_id integer,
    vendor_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.non_conformances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.non_conformances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT pk_non_conformances PRIMARY KEY (id);

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances__asp_net_users_containment_by_id FOREIGN KEY (containment_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances__asp_net_users_detected_by_id FOREIGN KEY (detected_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances__asp_net_users_disposition_by_id FOREIGN KEY (disposition_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances_corrective_actions_capa_id FOREIGN KEY (capa_id) REFERENCES public.corrective_actions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.non_conformances
    ADD CONSTRAINT fk_non_conformances_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;
