CREATE TABLE public.notifications (
    id integer NOT NULL,
    user_id integer NOT NULL,
    type character varying(50) NOT NULL,
    severity character varying(20) NOT NULL,
    source character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    message character varying(2000) NOT NULL,
    is_read boolean NOT NULL,
    is_pinned boolean NOT NULL,
    is_dismissed boolean NOT NULL,
    entity_type character varying(50),
    entity_id integer,
    sender_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT pk_notifications PRIMARY KEY (id);
