CREATE TABLE public.oauth_state_tokens (
    id integer NOT NULL,
    token character varying(128) NOT NULL,
    user_id integer NOT NULL,
    provider_key character varying(32) NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

ALTER TABLE public.oauth_state_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth_state_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.oauth_state_tokens
    ADD CONSTRAINT pk_oauth_state_tokens PRIMARY KEY (id);
