CREATE TABLE public.operation_materials (
    id integer NOT NULL,
    operation_id integer NOT NULL,
    bom_line_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.operation_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.operation_materials
    ADD CONSTRAINT pk_operation_materials PRIMARY KEY (id);

ALTER TABLE ONLY public.operation_materials
    ADD CONSTRAINT fk_operation_materials_bomlines_bom_line_id FOREIGN KEY (bom_line_id) REFERENCES public.bomlines(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.operation_materials
    ADD CONSTRAINT fk_operation_materials_operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE CASCADE;
