CREATE TABLE public.operations (
    id integer NOT NULL,
    part_id integer NOT NULL,
    step_number integer NOT NULL,
    title character varying(200) NOT NULL,
    instructions character varying(4000),
    work_center_id integer,
    asset_id integer,
    estimated_minutes integer,
    is_qc_checkpoint boolean NOT NULL,
    qc_criteria character varying(1000),
    referenced_operation_id integer,
    setup_minutes numeric(10,2) DEFAULT 0.0 NOT NULL,
    run_minutes_each numeric(10,2) DEFAULT 0.0 NOT NULL,
    run_minutes_lot numeric(10,2) DEFAULT 0.0 NOT NULL,
    overlap_percent numeric(5,2) DEFAULT 0.0 NOT NULL,
    scrap_factor numeric(5,4) DEFAULT 0.0 NOT NULL,
    is_subcontract boolean DEFAULT false NOT NULL,
    subcontract_vendor_id integer,
    subcontract_cost numeric(18,4),
    subcontract_lead_time_days integer,
    subcontract_instructions text,
    subcontract_turn_time_days numeric(5,1),
    labor_rate numeric(18,4) DEFAULT 0.0 NOT NULL,
    burden_rate numeric(18,4) DEFAULT 0.0 NOT NULL,
    estimated_labor_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    estimated_burden_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.operations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT pk_operations PRIMARY KEY (id);

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT fk_operations__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT fk_operations__vendors_subcontract_vendor_id FOREIGN KEY (subcontract_vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT fk_operations__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT fk_operations_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT fk_operations_operations_referenced_operation_id FOREIGN KEY (referenced_operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;
