CREATE TABLE public.order_ship_tos (
    id integer NOT NULL,
    sales_order_id integer NOT NULL,
    name character varying(200) NOT NULL,
    company character varying(200),
    line1 character varying(200) NOT NULL,
    line2 character varying(200),
    city character varying(100) NOT NULL,
    state character varying(100) NOT NULL,
    postal_code character varying(20) NOT NULL,
    country character varying(10) NOT NULL,
    phone character varying(50),
    is_validated boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.order_ship_tos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_ship_tos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.order_ship_tos
    ADD CONSTRAINT pk_order_ship_tos PRIMARY KEY (id);

ALTER TABLE ONLY public.order_ship_tos
    ADD CONSTRAINT fk_order_ship_tos__sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE CASCADE;
