CREATE TABLE public.outreach_campaigns (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    strategy character varying(50) NOT NULL,
    default_cooldown_days integer,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    is_active boolean NOT NULL,
    owner_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.outreach_campaigns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outreach_campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.outreach_campaigns
    ADD CONSTRAINT pk_outreach_campaigns PRIMARY KEY (id);
