CREATE TABLE public.overtime_rules (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    daily_threshold_hours numeric(8,2) NOT NULL,
    weekly_threshold_hours numeric(8,2) NOT NULL,
    overtime_multiplier numeric(6,3) NOT NULL,
    doubletime_threshold_daily_hours numeric(8,2),
    doubletime_threshold_weekly_hours numeric(8,2),
    doubletime_multiplier numeric(6,3) NOT NULL,
    is_default boolean NOT NULL,
    apply_daily_before_weekly boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.overtime_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.overtime_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.overtime_rules
    ADD CONSTRAINT pk_overtime_rules PRIMARY KEY (id);
