CREATE TABLE public.overhead_cost_pools (
    id integer NOT NULL,
    costing_cost_center_id integer NOT NULL,
    work_center_id integer,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    behavior integer NOT NULL,
    fixed_portion numeric(18,6),
    driver integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.overhead_cost_pools ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.overhead_cost_pools_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.overhead_cost_pools
    ADD CONSTRAINT pk_overhead_cost_pools PRIMARY KEY (id);

ALTER TABLE ONLY public.overhead_cost_pools
    ADD CONSTRAINT fk_overhead_cost_pools__costing_cost_centers_costing_cost_center_id FOREIGN KEY (costing_cost_center_id) REFERENCES public.costing_cost_centers(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.overhead_cost_pools
    ADD CONSTRAINT fk_overhead_cost_pools__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;

CREATE INDEX ix_overhead_cost_pools_costing_cost_center_id ON public.overhead_cost_pools (costing_cost_center_id);
CREATE INDEX ix_overhead_cost_pools_work_center_id ON public.overhead_cost_pools (work_center_id);
