CREATE TABLE public.overhead_pool_budgets (
    id integer NOT NULL,
    overhead_cost_pool_id integer NOT NULL,
    costing_period_id integer NOT NULL,
    budget_amount numeric(18,2) NOT NULL,
    budget_driver_qty numeric(18,4) NOT NULL,
    derived_rate numeric(18,6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.overhead_pool_budgets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.overhead_pool_budgets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.overhead_pool_budgets
    ADD CONSTRAINT pk_overhead_pool_budgets PRIMARY KEY (id);

ALTER TABLE ONLY public.overhead_pool_budgets
    ADD CONSTRAINT fk_overhead_pool_budgets__overhead_cost_pools_overhead_cost_pool_id FOREIGN KEY (overhead_cost_pool_id) REFERENCES public.overhead_cost_pools(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.overhead_pool_budgets
    ADD CONSTRAINT fk_overhead_pool_budgets__costing_periods_costing_period_id FOREIGN KEY (costing_period_id) REFERENCES public.costing_periods(id) ON DELETE CASCADE;

CREATE INDEX ix_overhead_pool_budgets_overhead_cost_pool_id ON public.overhead_pool_budgets (overhead_cost_pool_id);
CREATE INDEX ix_overhead_pool_budgets_costing_period_id ON public.overhead_pool_budgets (costing_period_id);
