CREATE TABLE public.part_safety_data_sheets (
    id integer NOT NULL,
    part_id integer NOT NULL,
    document_set_id integer NOT NULL,
    sds_type character varying(20) NOT NULL,
    supplier character varying(200),
    revision_date timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.part_safety_data_sheets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.part_safety_data_sheets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.part_safety_data_sheets
    ADD CONSTRAINT pk_part_safety_data_sheets PRIMARY KEY (id);

ALTER TABLE ONLY public.part_safety_data_sheets
    ADD CONSTRAINT fk_part_safety_data_sheets__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.part_safety_data_sheets
    ADD CONSTRAINT fk_part_safety_data_sheets__document_sets_document_set_id FOREIGN KEY (document_set_id) REFERENCES public.document_sets(id) ON DELETE CASCADE;
