CREATE TABLE public.part_prices (
    id integer NOT NULL,
    part_id integer NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    notes character varying(500),
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE public.part_prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.part_prices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.part_prices
    ADD CONSTRAINT pk_part_prices PRIMARY KEY (id);

ALTER TABLE ONLY public.part_prices
    ADD CONSTRAINT fk_part_prices_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;
