CREATE TABLE public.part_revisions (
    id integer NOT NULL,
    part_id integer NOT NULL,
    revision character varying(20) NOT NULL,
    change_description character varying(500),
    change_reason character varying(500),
    effective_date timestamp with time zone NOT NULL,
    is_current boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.part_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.part_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.part_revisions
    ADD CONSTRAINT pk_part_revisions PRIMARY KEY (id);

ALTER TABLE ONLY public.part_revisions
    ADD CONSTRAINT fk_part_revisions_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;
