CREATE TABLE public.part_alternates (
    id integer NOT NULL,
    part_id integer NOT NULL,
    alternate_part_id integer NOT NULL,
    priority integer NOT NULL,
    type integer NOT NULL,
    conversion_factor numeric(18,6),
    is_approved boolean NOT NULL,
    approved_by_id integer,
    approved_at timestamp with time zone,
    notes character varying(500),
    is_bidirectional boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.part_alternates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.part_alternates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.part_alternates
    ADD CONSTRAINT pk_part_alternates PRIMARY KEY (id);

ALTER TABLE ONLY public.part_alternates
    ADD CONSTRAINT fk_part_alternates_parts_alternate_part_id FOREIGN KEY (alternate_part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.part_alternates
    ADD CONSTRAINT fk_part_alternates_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;
