CREATE TABLE public.part_purchase_units (
    id integer NOT NULL,
    part_id integer NOT NULL,
    label character varying(200) NOT NULL,
    content_quantity numeric(18,4) NOT NULL,
    content_uom_id integer,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.part_purchase_units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.part_purchase_units_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.part_purchase_units
    ADD CONSTRAINT pk_part_purchase_units PRIMARY KEY (id);

ALTER TABLE ONLY public.part_purchase_units
    ADD CONSTRAINT fk_part_purchase_units__units_of_measure_content_uom_id FOREIGN KEY (content_uom_id) REFERENCES public.units_of_measure(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.part_purchase_units
    ADD CONSTRAINT fk_part_purchase_units_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;
