CREATE TABLE public.parts (
    id integer NOT NULL,
    part_number character varying(50) NOT NULL,
    name character varying(256) DEFAULT ''::character varying NOT NULL,
    description character varying(2000),
    revision character varying(10) NOT NULL,
    status integer NOT NULL,
    procurement_source character varying(32) DEFAULT 'Buy'::character varying NOT NULL,
    inventory_class character varying(32) DEFAULT 'Component'::character varying NOT NULL,
    item_kind_id integer,
    traceability_type character varying(16) DEFAULT 'None'::character varying NOT NULL,
    abc_class character varying(2),
    material_spec_id integer,
    weight_each numeric(18,4),
    weight_display_unit character varying(8),
    length_mm numeric(18,4),
    width_mm numeric(18,4),
    height_mm numeric(18,4),
    dimension_display_unit character varying(8),
    volume_ml numeric(18,4),
    volume_display_unit character varying(8),
    valuation_class_id integer,
    hts_code character varying(20),
    hazmat_class character varying(20),
    shelf_life_days integer,
    backflush_policy character varying(16),
    is_kit boolean DEFAULT false NOT NULL,
    is_configurable boolean DEFAULT false NOT NULL,
    default_bin_id integer,
    source_part_id integer,
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    preferred_vendor_id integer,
    safety_stock_qty integer DEFAULT 0 NOT NULL,
    exclude_from_auto_po boolean DEFAULT false NOT NULL,
    min_stock_threshold numeric,
    reorder_point numeric,
    reorder_quantity numeric,
    safety_stock_days integer,
    lot_sizing_rule integer,
    fixed_order_quantity numeric(18,4),
    minimum_order_quantity numeric(18,4),
    order_multiple numeric(18,4),
    planning_fence_days integer,
    demand_fence_days integer,
    is_mrp_planned boolean DEFAULT false NOT NULL,
    requires_receiving_inspection boolean DEFAULT false NOT NULL,
    receiving_inspection_template_id integer,
    inspection_frequency integer DEFAULT 0 NOT NULL,
    inspection_skip_after_n integer,
    custom_field_values jsonb,
    stock_uom_id integer,
    purchase_uom_id integer,
    sales_uom_id integer,
    tooling_asset_id integer,
    manual_cost_override numeric(18,4),
    current_cost_calculation_id integer,
    current_bom_revision_id integer,
    is_license boolean DEFAULT false NOT NULL,
    license_expires_at timestamp with time zone,
    license_renewal_lead_days integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT pk_parts PRIMARY KEY (id);

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__reference_data_item_kind_id FOREIGN KEY (item_kind_id) REFERENCES public.reference_data(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__reference_data_material_spec_id FOREIGN KEY (material_spec_id) REFERENCES public.reference_data(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__reference_data_valuation_class_id FOREIGN KEY (valuation_class_id) REFERENCES public.reference_data(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__storage_locations_default_bin_id FOREIGN KEY (default_bin_id) REFERENCES public.storage_locations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__units_of_measure_purchase_uom_id FOREIGN KEY (purchase_uom_id) REFERENCES public.units_of_measure(id);

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__units_of_measure_sales_uom_id FOREIGN KEY (sales_uom_id) REFERENCES public.units_of_measure(id);

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__units_of_measure_stock_uom_id FOREIGN KEY (stock_uom_id) REFERENCES public.units_of_measure(id);

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts__vendors_preferred_vendor_id FOREIGN KEY (preferred_vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts_assets_tooling_asset_id FOREIGN KEY (tooling_asset_id) REFERENCES public.assets(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts_bom_revisions_current_bom_revision_id FOREIGN KEY (current_bom_revision_id) REFERENCES public.bom_revisions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts_cost_calculations_current_cost_calculation_id FOREIGN KEY (current_cost_calculation_id) REFERENCES public.cost_calculations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT fk_parts_parts_source_part_id FOREIGN KEY (source_part_id) REFERENCES public.parts(id) ON DELETE SET NULL;
