CREATE TABLE public.pay_stub_deductions (
    id integer NOT NULL,
    pay_stub_id integer NOT NULL,
    category integer NOT NULL,
    description character varying(200) NOT NULL,
    amount numeric(18,2) NOT NULL
);

ALTER TABLE public.pay_stub_deductions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pay_stub_deductions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.pay_stub_deductions
    ADD CONSTRAINT pk_pay_stub_deductions PRIMARY KEY (id);

ALTER TABLE ONLY public.pay_stub_deductions
    ADD CONSTRAINT fk_pay_stub_deductions_pay_stubs_pay_stub_id FOREIGN KEY (pay_stub_id) REFERENCES public.pay_stubs(id) ON DELETE CASCADE;
