CREATE TABLE public.pay_stubs (
    id integer NOT NULL,
    user_id integer NOT NULL,
    pay_period_start timestamp with time zone NOT NULL,
    pay_period_end timestamp with time zone NOT NULL,
    pay_date timestamp with time zone NOT NULL,
    gross_pay numeric(18,2) NOT NULL,
    net_pay numeric(18,2) NOT NULL,
    total_deductions numeric(18,2) NOT NULL,
    total_taxes numeric(18,2) NOT NULL,
    file_attachment_id integer,
    source integer NOT NULL,
    external_id character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.pay_stubs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pay_stubs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.pay_stubs
    ADD CONSTRAINT pk_pay_stubs PRIMARY KEY (id);

ALTER TABLE ONLY public.pay_stubs
    ADD CONSTRAINT fk_pay_stubs_file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;
