CREATE TABLE public.payment_batches (
    id integer NOT NULL,
    batch_number character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    is_prenote boolean NOT NULL,
    effective_entry_date date NOT NULL,
    file_contents text,
    generated_at timestamp with time zone,
    created_by_user_id integer NOT NULL,
    released_by_user_id integer,
    released_at timestamp with time zone,
    total_amount numeric(18,4) NOT NULL,
    entry_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.payment_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment_batches
    ADD CONSTRAINT pk_payment_batches PRIMARY KEY (id);
