CREATE TABLE public.payments (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    payment_number character varying(20) NOT NULL,
    customer_id integer NOT NULL,
    method integer NOT NULL,
    amount numeric(18,4) NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    reference_number character varying(50),
    notes character varying(2000),
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT pk_payments PRIMARY KEY (id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk_payments_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;
