CREATE TABLE public.payment_applications (
    id integer NOT NULL,
    payment_id integer NOT NULL,
    invoice_id integer NOT NULL,
    amount numeric(18,4) NOT NULL,
    settlement_fx_rate numeric(18,8) DEFAULT 1.0 NOT NULL
);

ALTER TABLE public.payment_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment_applications
    ADD CONSTRAINT pk_payment_applications PRIMARY KEY (id);

ALTER TABLE ONLY public.payment_applications
    ADD CONSTRAINT fk_payment_applications_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.payment_applications
    ADD CONSTRAINT fk_payment_applications_payments_payment_id FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE CASCADE;
