CREATE TABLE public.payment_transmissions (
    id integer NOT NULL,
    source_type character varying(50) NOT NULL,
    source_id integer NOT NULL,
    status character varying(30) NOT NULL,
    attempt_count integer NOT NULL,
    last_attempt_at timestamp with time zone,
    next_attempt_at timestamp with time zone,
    last_error character varying(4000),
    submission_ref character varying(200),
    amount numeric(18,2) NOT NULL,
    method character varying(30) NOT NULL,
    created_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.payment_transmissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_transmissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment_transmissions
    ADD CONSTRAINT pk_payment_transmissions PRIMARY KEY (id);
