CREATE TABLE public.payment_milestones (
    id integer NOT NULL,
    payment_schedule_id integer NOT NULL,
    sequence integer NOT NULL,
    name character varying(200) NOT NULL,
    percentage numeric(7,4) NOT NULL,
    due_trigger character varying(30) NOT NULL,
    due_date timestamp with time zone,
    net_days integer,
    status character varying(20) DEFAULT 'Pending'::character varying NOT NULL,
    amount_locked numeric(18,2),
    invoice_id integer,
    paid_amount numeric(18,2),
    paid_at timestamp with time zone,
    paid_reference character varying(200),
    notes character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.payment_milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment_milestones
    ADD CONSTRAINT pk_payment_milestones PRIMARY KEY (id);

ALTER TABLE ONLY public.payment_milestones
    ADD CONSTRAINT fk_payment_milestones_payment_schedules_payment_schedule_id FOREIGN KEY (payment_schedule_id) REFERENCES public.payment_schedules(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.payment_milestones
    ADD CONSTRAINT fk_payment_milestones_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;
