CREATE TABLE public.payment_schedules (
    id integer NOT NULL,
    quote_id integer,
    sales_order_id integer,
    status character varying(20) DEFAULT 'Draft'::character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.payment_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment_schedules
    ADD CONSTRAINT pk_payment_schedules PRIMARY KEY (id);

ALTER TABLE ONLY public.payment_schedules
    ADD CONSTRAINT fk_payment_schedules_quotes_quote_id FOREIGN KEY (quote_id) REFERENCES public.quotes(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.payment_schedules
    ADD CONSTRAINT fk_payment_schedules_sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE SET NULL;
