CREATE TABLE public.payment_batch_items (
    id integer NOT NULL,
    payment_batch_id integer NOT NULL,
    vendor_payment_id integer,
    vendor_bank_account_id integer NOT NULL,
    amount numeric(18,4) NOT NULL,
    trace_number character varying(15)
);

ALTER TABLE public.payment_batch_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_batch_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment_batch_items
    ADD CONSTRAINT pk_payment_batch_items PRIMARY KEY (id);

ALTER TABLE ONLY public.payment_batch_items
    ADD CONSTRAINT fk_payment_batch_items_account FOREIGN KEY (vendor_bank_account_id) REFERENCES public.vendor_bank_accounts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.payment_batch_items
    ADD CONSTRAINT fk_payment_batch_items_batch FOREIGN KEY (payment_batch_id) REFERENCES public.payment_batches(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.payment_batch_items
    ADD CONSTRAINT fk_payment_batch_items_payment FOREIGN KEY (vendor_payment_id) REFERENCES public.vendor_payments(id) ON DELETE RESTRICT;
