CREATE TABLE public.performance_reviews (
    id integer NOT NULL,
    cycle_id integer NOT NULL,
    employee_id integer NOT NULL,
    reviewer_id integer NOT NULL,
    status integer NOT NULL,
    overall_rating numeric(3,1),
    goals_json text,
    competencies_json text,
    strengths_comments character varying(5000),
    improvement_comments character varying(5000),
    employee_self_assessment character varying(5000),
    completed_at timestamp with time zone,
    acknowledged_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.performance_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.performance_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.performance_reviews
    ADD CONSTRAINT pk_performance_reviews PRIMARY KEY (id);

ALTER TABLE ONLY public.performance_reviews
    ADD CONSTRAINT fk_performance_reviews__review_cycles_cycle_id FOREIGN KEY (cycle_id) REFERENCES public.review_cycles(id) ON DELETE CASCADE;
