CREATE TABLE public.pick_lines (
    id integer NOT NULL,
    wave_id integer NOT NULL,
    shipment_line_id integer NOT NULL,
    part_id integer NOT NULL,
    from_location_id integer NOT NULL,
    from_bin_id integer,
    bin_path character varying(500),
    requested_quantity numeric(18,4) NOT NULL,
    picked_quantity numeric(18,4) NOT NULL,
    status integer NOT NULL,
    sort_order integer NOT NULL,
    picked_by_user_id integer,
    picked_at timestamp with time zone,
    short_notes character varying(500)
);

ALTER TABLE public.pick_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pick_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.pick_lines
    ADD CONSTRAINT pk_pick_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.pick_lines
    ADD CONSTRAINT fk_pick_lines__pick_waves_wave_id FOREIGN KEY (wave_id) REFERENCES public.pick_waves(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.pick_lines
    ADD CONSTRAINT fk_pick_lines__shipment_lines_shipment_line_id FOREIGN KEY (shipment_line_id) REFERENCES public.shipment_lines(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.pick_lines
    ADD CONSTRAINT fk_pick_lines__storage_locations_from_location_id FOREIGN KEY (from_location_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.pick_lines
    ADD CONSTRAINT fk_pick_lines_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
