CREATE TABLE public.pick_waves (
    id integer NOT NULL,
    wave_number character varying(20) NOT NULL,
    status integer NOT NULL,
    released_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    assigned_to_id integer,
    strategy integer NOT NULL,
    total_lines integer NOT NULL,
    picked_lines integer NOT NULL,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.pick_waves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pick_waves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.pick_waves
    ADD CONSTRAINT pk_pick_waves PRIMARY KEY (id);
