CREATE TABLE public.piece_rates (
    id integer NOT NULL,
    part_id integer NOT NULL,
    operation_id integer,
    rate_per_piece numeric(18,4) NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    notes character varying(512),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.piece_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piece_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.piece_rates
    ADD CONSTRAINT pk_piece_rates PRIMARY KEY (id);

ALTER TABLE ONLY public.piece_rates
    ADD CONSTRAINT fk_piece_rates__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.piece_rates
    ADD CONSTRAINT fk_piece_rates__operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;

CREATE INDEX ix_piece_rates_part_id_effective_from ON public.piece_rates USING btree (part_id, effective_from);

-- One ACTIVE (open-ended) rate per scope. Part-level and per-operation rates are
-- separate scopes; two partial indexes because NULL operation_id rows would
-- otherwise never collide with each other.
CREATE UNIQUE INDEX ux_piece_rates_active_part ON public.piece_rates USING btree (part_id) WHERE (operation_id IS NULL AND effective_to IS NULL AND deleted_at IS NULL);
CREATE UNIQUE INDEX ux_piece_rates_active_part_operation ON public.piece_rates USING btree (part_id, operation_id) WHERE (operation_id IS NOT NULL AND effective_to IS NULL AND deleted_at IS NULL);
