CREATE TABLE public.piece_work_entries (
    id integer NOT NULL,
    user_id integer NOT NULL,
    part_id integer NOT NULL,
    operation_id integer,
    piece_rate_id integer NOT NULL,
    work_date date NOT NULL,
    quantity numeric(18,2) NOT NULL,
    rate_snapshot numeric(18,4) NOT NULL,
    earnings numeric(18,2) NOT NULL,
    notes character varying(512),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.piece_work_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piece_work_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.piece_work_entries
    ADD CONSTRAINT pk_piece_work_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.piece_work_entries
    ADD CONSTRAINT fk_piece_work_entries__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.piece_work_entries
    ADD CONSTRAINT fk_piece_work_entries__parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.piece_work_entries
    ADD CONSTRAINT fk_piece_work_entries__piece_rates_piece_rate_id FOREIGN KEY (piece_rate_id) REFERENCES public.piece_rates(id) ON DELETE RESTRICT;

CREATE INDEX ix_piece_work_entries_user_id_work_date ON public.piece_work_entries USING btree (user_id, work_date);
CREATE INDEX ix_piece_work_entries_part_id ON public.piece_work_entries USING btree (part_id);
CREATE INDEX ix_piece_work_entries_piece_rate_id ON public.piece_work_entries USING btree (piece_rate_id);
