CREATE TABLE public.planning_cycle_entries (
    id integer NOT NULL,
    planning_cycle_id integer NOT NULL,
    job_id integer NOT NULL,
    committed_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    is_rolled_over boolean NOT NULL,
    sort_order integer NOT NULL
);

ALTER TABLE public.planning_cycle_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.planning_cycle_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.planning_cycle_entries
    ADD CONSTRAINT pk_planning_cycle_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.planning_cycle_entries
    ADD CONSTRAINT fk_planning_cycle_entries_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.planning_cycle_entries
    ADD CONSTRAINT fk_planning_cycle_entries_planning_cycles_planning_cycle_id FOREIGN KEY (planning_cycle_id) REFERENCES public.planning_cycles(id) ON DELETE CASCADE;
