CREATE TABLE public.plants (
    id integer NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    company_location_id integer NOT NULL,
    time_zone character varying(100),
    currency_code character varying(10),
    is_active boolean NOT NULL,
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.plants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT pk_plants PRIMARY KEY (id);

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT fk_plants_company_locations_company_location_id FOREIGN KEY (company_location_id) REFERENCES public.company_locations(id) ON DELETE RESTRICT;
