CREATE TABLE public.ppap_elements (
    id integer NOT NULL,
    submission_id integer NOT NULL,
    element_number integer NOT NULL,
    element_name character varying(200) NOT NULL,
    status integer NOT NULL,
    is_required boolean NOT NULL,
    notes character varying(4000),
    assigned_to_user_id integer,
    completed_at timestamp with time zone
);

ALTER TABLE public.ppap_elements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ppap_elements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ppap_elements
    ADD CONSTRAINT pk_ppap_elements PRIMARY KEY (id);

ALTER TABLE ONLY public.ppap_elements
    ADD CONSTRAINT fk_ppap_elements__asp_net_users_assigned_to_user_id FOREIGN KEY (assigned_to_user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.ppap_elements
    ADD CONSTRAINT fk_ppap_elements__ppap_submissions_submission_id FOREIGN KEY (submission_id) REFERENCES public.ppap_submissions(id) ON DELETE CASCADE;
