CREATE TABLE public.ppap_submissions (
    id integer NOT NULL,
    submission_number character varying(20) NOT NULL,
    part_id integer NOT NULL,
    customer_id integer NOT NULL,
    ppap_level integer NOT NULL,
    status integer NOT NULL,
    reason integer NOT NULL,
    part_revision character varying(50),
    submitted_at timestamp with time zone,
    approved_at timestamp with time zone,
    due_date timestamp with time zone,
    customer_contact_name character varying(200),
    customer_response_notes character varying(4000),
    internal_notes character varying(4000),
    psw_signed_by_user_id integer,
    psw_signed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.ppap_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ppap_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ppap_submissions
    ADD CONSTRAINT pk_ppap_submissions PRIMARY KEY (id);

ALTER TABLE ONLY public.ppap_submissions
    ADD CONSTRAINT fk_ppap_submissions__asp_net_users_psw_signed_by_user_id FOREIGN KEY (psw_signed_by_user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.ppap_submissions
    ADD CONSTRAINT fk_ppap_submissions_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.ppap_submissions
    ADD CONSTRAINT fk_ppap_submissions_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
