CREATE TABLE public.price_list_entries (
    id integer NOT NULL,
    price_list_id integer NOT NULL,
    part_id integer NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    min_quantity integer NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.price_list_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_list_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.price_list_entries
    ADD CONSTRAINT pk_price_list_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.price_list_entries
    ADD CONSTRAINT fk_price_list_entries_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.price_list_entries
    ADD CONSTRAINT fk_price_list_entries_price_lists_price_list_id FOREIGN KEY (price_list_id) REFERENCES public.price_lists(id) ON DELETE CASCADE;
