CREATE TABLE public.price_lists (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    customer_id integer,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    effective_from timestamp with time zone,
    effective_to timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.price_lists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_lists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.price_lists
    ADD CONSTRAINT pk_price_lists PRIMARY KEY (id);

ALTER TABLE ONLY public.price_lists
    ADD CONSTRAINT fk_price_lists_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
