CREATE TABLE public.product_configurators (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    base_part_id integer NOT NULL,
    is_active boolean NOT NULL,
    validation_rules_json text,
    base_price numeric(18,4),
    pricing_formula_json text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.product_configurators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_configurators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.product_configurators
    ADD CONSTRAINT pk_product_configurators PRIMARY KEY (id);

ALTER TABLE ONLY public.product_configurators
    ADD CONSTRAINT fk_product_configurators_parts_base_part_id FOREIGN KEY (base_part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
