CREATE TABLE public.production_runs (
    id integer NOT NULL,
    job_id integer NOT NULL,
    part_id integer NOT NULL,
    operator_id integer,
    work_center_id integer,
    run_number character varying(50) NOT NULL,
    target_quantity integer NOT NULL,
    completed_quantity integer NOT NULL,
    scrap_quantity integer NOT NULL,
    rework_quantity integer DEFAULT 0 NOT NULL,
    status integer NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    received_to_stock_at timestamp with time zone,
    received_quantity integer DEFAULT 0 NOT NULL,
    notes character varying(2000),
    setup_time_minutes numeric(10,2),
    run_time_minutes numeric(10,2),
    ideal_cycle_time_seconds numeric(10,2),
    actual_cycle_time_seconds numeric(10,2),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.production_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.production_runs
    ADD CONSTRAINT pk_production_runs PRIMARY KEY (id);

ALTER TABLE ONLY public.production_runs
    ADD CONSTRAINT fk_production_runs__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.production_runs
    ADD CONSTRAINT fk_production_runs_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.production_runs
    ADD CONSTRAINT fk_production_runs_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;
