CREATE TABLE public.product_configurations (
    id integer NOT NULL,
    configurator_id integer NOT NULL,
    configuration_code character varying(50) NOT NULL,
    selections_json text NOT NULL,
    computed_price numeric(18,4) NOT NULL,
    generated_bom_json text,
    generated_routing_json text,
    quote_id integer,
    part_id integer,
    status integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.product_configurations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.product_configurations
    ADD CONSTRAINT pk_product_configurations PRIMARY KEY (id);

ALTER TABLE ONLY public.product_configurations
    ADD CONSTRAINT fk_product_configurations__product_configurators_configurator_i FOREIGN KEY (configurator_id) REFERENCES public.product_configurators(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.product_configurations
    ADD CONSTRAINT fk_product_configurations__quotes_quote_id FOREIGN KEY (quote_id) REFERENCES public.quotes(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.product_configurations
    ADD CONSTRAINT fk_product_configurations_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE SET NULL;
