CREATE TABLE public.projects (
    id integer NOT NULL,
    project_number character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(2000),
    customer_id integer,
    sales_order_id integer,
    budget_total numeric(18,2) NOT NULL,
    actual_total numeric(18,2) NOT NULL,
    committed_total numeric(18,2) NOT NULL,
    estimate_at_completion_total numeric(18,2) NOT NULL,
    status integer NOT NULL,
    planned_start_date date,
    planned_end_date date,
    actual_start_date date,
    actual_end_date date,
    revenue_recognized numeric(18,2),
    percent_complete numeric(5,2),
    notes character varying(4000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT pk_projects PRIMARY KEY (id);

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fk_projects__sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fk_projects_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
