CREATE TABLE public.purchase_order_lines (
    id integer NOT NULL,
    purchase_order_id integer NOT NULL,
    part_id integer NOT NULL,
    description character varying(500) NOT NULL,
    ordered_quantity numeric(18,4) NOT NULL,
    received_quantity numeric(18,4) NOT NULL,
    cancelled_short_close_quantity numeric(18,4) DEFAULT 0.0 NOT NULL,
    billed_quantity numeric(18,4) DEFAULT 0.0 NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    notes character varying(1000),
    mrp_planned_order_id integer,
    uom_id integer,
    purchase_unit_id integer,
    manual_override_reason character varying(500)
);

ALTER TABLE public.purchase_order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.purchase_order_lines
    ADD CONSTRAINT pk_purchase_order_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.purchase_order_lines
    ADD CONSTRAINT fk_purchase_order_lines__units_of_measure_uom_id FOREIGN KEY (uom_id) REFERENCES public.units_of_measure(id);

ALTER TABLE ONLY public.purchase_order_lines
    ADD CONSTRAINT fk_purchase_order_lines_mrp_planned_orders_mrp_planned_order_id FOREIGN KEY (mrp_planned_order_id) REFERENCES public.mrp_planned_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.purchase_order_lines
    ADD CONSTRAINT fk_purchase_order_lines_part_purchase_units_purchase_unit_id FOREIGN KEY (purchase_unit_id) REFERENCES public.part_purchase_units(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.purchase_order_lines
    ADD CONSTRAINT fk_purchase_order_lines_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.purchase_order_lines
    ADD CONSTRAINT fk_purchase_order_lines_purchase_orders_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE CASCADE;
