CREATE TABLE public.purchase_order_releases (
    id integer NOT NULL,
    purchase_order_id integer NOT NULL,
    release_number integer NOT NULL,
    purchase_order_line_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    requested_delivery_date timestamp with time zone NOT NULL,
    actual_delivery_date timestamp with time zone,
    status integer NOT NULL,
    receiving_record_id integer,
    notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.purchase_order_releases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_releases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.purchase_order_releases
    ADD CONSTRAINT pk_purchase_order_releases PRIMARY KEY (id);

ALTER TABLE ONLY public.purchase_order_releases
    ADD CONSTRAINT fk_purchase_order_releases__receiving_records_receiving_record_ FOREIGN KEY (receiving_record_id) REFERENCES public.receiving_records(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.purchase_order_releases
    ADD CONSTRAINT "fk_purchase_order_releases_purchase_order_lines_purchase_order~" FOREIGN KEY (purchase_order_line_id) REFERENCES public.purchase_order_lines(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.purchase_order_releases
    ADD CONSTRAINT fk_purchase_order_releases_purchase_orders_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE CASCADE;
