CREATE TABLE public.purchase_orders (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    ponumber character varying(20) NOT NULL,
    vendor_id integer NOT NULL,
    job_id integer,
    status integer NOT NULL,
    submitted_date timestamp with time zone,
    acknowledged_date timestamp with time zone,
    expected_delivery_date timestamp with time zone,
    received_date timestamp with time zone,
    notes character varying(2000),
    short_close_reason character varying(2000),
    short_closed_at timestamp with time zone,
    is_blanket boolean DEFAULT false NOT NULL,
    blanket_total_quantity numeric(18,4),
    blanket_released_quantity numeric(18,4),
    blanket_expiration_date timestamp with time zone,
    agreed_unit_price numeric(18,4),
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    incoterm integer DEFAULT 0 NOT NULL,
    estimated_freight numeric(18,4),
    quote_currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    fx_rate numeric(18,8),
    fx_rate_source character varying(200),
    origin_source character varying(30) DEFAULT 'Manual'::character varying NOT NULL,
    origin_user_id integer,
    origin_reference character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT pk_purchase_orders PRIMARY KEY (id);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk_purchase_orders__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk_purchase_orders_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk_purchase_orders__asp_net_users_origin_user_id FOREIGN KEY (origin_user_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;
