CREATE TABLE public.qc_checklist_templates (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(500),
    part_id integer,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.qc_checklist_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qc_checklist_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.qc_checklist_templates
    ADD CONSTRAINT pk_qc_checklist_templates PRIMARY KEY (id);

ALTER TABLE ONLY public.qc_checklist_templates
    ADD CONSTRAINT fk_qc_checklist_templates_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
