CREATE TABLE public.qc_checklist_items (
    id integer NOT NULL,
    template_id integer NOT NULL,
    description character varying(200) NOT NULL,
    specification character varying(500),
    sort_order integer NOT NULL,
    is_required boolean NOT NULL
);

ALTER TABLE public.qc_checklist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qc_checklist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.qc_checklist_items
    ADD CONSTRAINT pk_qc_checklist_items PRIMARY KEY (id);

ALTER TABLE ONLY public.qc_checklist_items
    ADD CONSTRAINT fk_qc_checklist_items__qc_checklist_templates_template_id FOREIGN KEY (template_id) REFERENCES public.qc_checklist_templates(id) ON DELETE CASCADE;
