CREATE TABLE public.qc_inspections (
    id integer NOT NULL,
    job_id integer,
    production_run_id integer,
    template_id integer,
    inspector_id integer NOT NULL,
    lot_number character varying(100),
    status character varying(50) NOT NULL,
    notes character varying(2000),
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.qc_inspections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qc_inspections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.qc_inspections
    ADD CONSTRAINT pk_qc_inspections PRIMARY KEY (id);

ALTER TABLE ONLY public.qc_inspections
    ADD CONSTRAINT fk_qc_inspections_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.qc_inspections
    ADD CONSTRAINT fk_qc_inspections_production_runs_production_run_id FOREIGN KEY (production_run_id) REFERENCES public.production_runs(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.qc_inspections
    ADD CONSTRAINT fk_qc_inspections_qc_checklist_templates_template_id FOREIGN KEY (template_id) REFERENCES public.qc_checklist_templates(id) ON DELETE RESTRICT;
