CREATE TABLE public.quote_terms_snapshots (
    id integer NOT NULL,
    quote_id integer NOT NULL,
    compiled_html text NOT NULL,
    compiled_source jsonb,
    access_token character varying(64) NOT NULL,
    sent_to character varying(320),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.quote_terms_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quote_terms_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.quote_terms_snapshots
    ADD CONSTRAINT pk_quote_terms_snapshots PRIMARY KEY (id);

ALTER TABLE ONLY public.quote_terms_snapshots
    ADD CONSTRAINT fk_quote_terms_snapshots_quotes_quote_id FOREIGN KEY (quote_id) REFERENCES public.quotes(id) ON DELETE CASCADE;
