CREATE TABLE public.quotes (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    type character varying(20) NOT NULL,
    customer_id integer NOT NULL,
    status character varying(30) NOT NULL,
    expiration_date timestamp with time zone,
    notes character varying(2000),
    assigned_to_id integer,
    title character varying(300),
    description character varying(2000),
    estimated_amount numeric(18,2),
    quote_number character varying(20),
    shipping_address_id integer,
    sent_date timestamp with time zone,
    accepted_date timestamp with time zone,
    tax_rate numeric(8,6) NOT NULL,
    customer_po character varying(50),
    source_estimate_id integer,
    converted_at timestamp with time zone,
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.quotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT pk_quotes PRIMARY KEY (id);

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT fk_quotes__asp_net_users_assigned_to_id FOREIGN KEY (assigned_to_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT fk_quotes_customer_addresses_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES public.customer_addresses(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT fk_quotes_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT fk_quotes_quotes_source_estimate_id FOREIGN KEY (source_estimate_id) REFERENCES public.quotes(id) ON DELETE SET NULL;
