CREATE TABLE public.quote_lines (
    id integer NOT NULL,
    quote_id integer NOT NULL,
    part_id integer,
    description character varying(500) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    line_number integer NOT NULL,
    notes character varying(1000)
);

ALTER TABLE public.quote_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quote_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.quote_lines
    ADD CONSTRAINT pk_quote_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.quote_lines
    ADD CONSTRAINT fk_quote_lines_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.quote_lines
    ADD CONSTRAINT fk_quote_lines_quotes_quote_id FOREIGN KEY (quote_id) REFERENCES public.quotes(id) ON DELETE CASCADE;
