CREATE TABLE public.recalls (
    id integer NOT NULL,
    initiated_by_user_id integer NOT NULL,
    initiated_lot_id integer NOT NULL,
    reason character varying(2000) NOT NULL,
    recall_date timestamp with time zone NOT NULL,
    status integer NOT NULL,
    affected_lots_count integer NOT NULL,
    affected_shipments_count integer NOT NULL,
    total_quarantined_quantity numeric(18,4) NOT NULL,
    resolved_at timestamp with time zone,
    resolution_notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.recalls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recalls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.recalls
    ADD CONSTRAINT pk_recalls PRIMARY KEY (id);

ALTER TABLE ONLY public.recalls
    ADD CONSTRAINT fk_recalls__lot_records_initiated_lot_id FOREIGN KEY (initiated_lot_id) REFERENCES public.lot_records(id) ON DELETE RESTRICT;
