CREATE TABLE public.recall_affected_shipments (
    id integer NOT NULL,
    recall_id integer NOT NULL,
    shipment_id integer NOT NULL,
    customer_id integer NOT NULL,
    affected_quantity numeric(18,4) NOT NULL,
    shipped_date timestamp with time zone,
    tracking_number character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.recall_affected_shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recall_affected_shipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.recall_affected_shipments
    ADD CONSTRAINT pk_recall_affected_shipments PRIMARY KEY (id);

ALTER TABLE ONLY public.recall_affected_shipments
    ADD CONSTRAINT fk_recall_affected_shipments__recalls_recall_id FOREIGN KEY (recall_id) REFERENCES public.recalls(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.recall_affected_shipments
    ADD CONSTRAINT fk_recall_affected_shipments__shipments_shipment_id FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.recall_affected_shipments
    ADD CONSTRAINT fk_recall_affected_shipments__customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;
