CREATE TABLE public.recall_affected_lots (
    id integer NOT NULL,
    recall_id integer NOT NULL,
    lot_id integer NOT NULL,
    consumed_quantity numeric(18,6) NOT NULL,
    job_id integer,
    production_run_id integer,
    on_hand_quantity numeric(18,4) NOT NULL,
    quarantined_quantity numeric(18,4) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.recall_affected_lots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recall_affected_lots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.recall_affected_lots
    ADD CONSTRAINT pk_recall_affected_lots PRIMARY KEY (id);

ALTER TABLE ONLY public.recall_affected_lots
    ADD CONSTRAINT fk_recall_affected_lots__recalls_recall_id FOREIGN KEY (recall_id) REFERENCES public.recalls(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.recall_affected_lots
    ADD CONSTRAINT fk_recall_affected_lots__lot_records_lot_id FOREIGN KEY (lot_id) REFERENCES public.lot_records(id) ON DELETE RESTRICT;
