CREATE TABLE public.receiving_records (
    id integer NOT NULL,
    purchase_order_line_id integer NOT NULL,
    quantity_received numeric(18,4) NOT NULL,
    received_by character varying(200),
    storage_location_id integer,
    notes character varying(1000),
    inspection_status integer DEFAULT 0 NOT NULL,
    inspected_by_id integer,
    inspected_at timestamp with time zone,
    inspection_notes text,
    inspected_quantity_accepted numeric,
    inspected_quantity_rejected numeric,
    qc_inspection_id integer,
    receipt_number character varying(40),
    actual_freight numeric(18,4),
    freight_allocation_method integer DEFAULT 0 NOT NULL,
    allocated_freight numeric(18,4),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.receiving_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receiving_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.receiving_records
    ADD CONSTRAINT pk_receiving_records PRIMARY KEY (id);

ALTER TABLE ONLY public.receiving_records
    ADD CONSTRAINT fk_receiving_records__storage_locations_storage_location_id FOREIGN KEY (storage_location_id) REFERENCES public.storage_locations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.receiving_records
    ADD CONSTRAINT "fk_receiving_records_purchase_order_lines_purchase_order_line_~" FOREIGN KEY (purchase_order_line_id) REFERENCES public.purchase_order_lines(id) ON DELETE CASCADE;
