CREATE TABLE public.receiving_inspections (
    id integer NOT NULL,
    receiving_record_id integer NOT NULL,
    qc_inspection_id integer,
    result integer NOT NULL,
    accepted_quantity numeric(18,4),
    rejected_quantity numeric(18,4),
    notes character varying(2000),
    inspected_by_id integer NOT NULL,
    inspected_at timestamp with time zone NOT NULL,
    ncr_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.receiving_inspections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receiving_inspections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.receiving_inspections
    ADD CONSTRAINT pk_receiving_inspections PRIMARY KEY (id);

ALTER TABLE ONLY public.receiving_inspections
    ADD CONSTRAINT fk_receiving_inspections__receiving_records_receiving_record_id FOREIGN KEY (receiving_record_id) REFERENCES public.receiving_records(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.receiving_inspections
    ADD CONSTRAINT fk_receiving_inspections_qc_inspections_qc_inspection_id FOREIGN KEY (qc_inspection_id) REFERENCES public.qc_inspections(id) ON DELETE SET NULL;
