CREATE TABLE public.recurring_orders (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    customer_id integer NOT NULL,
    shipping_address_id integer,
    interval_days integer NOT NULL,
    next_generation_date timestamp with time zone NOT NULL,
    last_generated_date timestamp with time zone,
    is_active boolean NOT NULL,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.recurring_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurring_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.recurring_orders
    ADD CONSTRAINT pk_recurring_orders PRIMARY KEY (id);

ALTER TABLE ONLY public.recurring_orders
    ADD CONSTRAINT fk_recurring_orders_customer_addresses_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES public.customer_addresses(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.recurring_orders
    ADD CONSTRAINT fk_recurring_orders_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;
