CREATE TABLE public.recurring_order_lines (
    id integer NOT NULL,
    recurring_order_id integer NOT NULL,
    part_id integer NOT NULL,
    description character varying(500) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    line_number integer NOT NULL
);

ALTER TABLE public.recurring_order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurring_order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.recurring_order_lines
    ADD CONSTRAINT pk_recurring_order_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.recurring_order_lines
    ADD CONSTRAINT fk_recurring_order_lines_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.recurring_order_lines
    ADD CONSTRAINT fk_recurring_order_lines_recurring_orders_recurring_order_id FOREIGN KEY (recurring_order_id) REFERENCES public.recurring_orders(id) ON DELETE CASCADE;
