CREATE TABLE public.recurring_expenses (
    id integer NOT NULL,
    user_id integer NOT NULL,
    amount numeric(18,2) NOT NULL,
    category character varying(100) NOT NULL,
    classification character varying(100) NOT NULL,
    description character varying(1000) NOT NULL,
    vendor character varying(200),
    frequency integer NOT NULL,
    next_occurrence_date timestamp with time zone NOT NULL,
    last_generated_date timestamp with time zone,
    end_date timestamp with time zone,
    is_active boolean NOT NULL,
    auto_approve boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.recurring_expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurring_expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.recurring_expenses
    ADD CONSTRAINT pk_recurring_expenses PRIMARY KEY (id);
