CREATE TABLE public.reference_data (
    id integer NOT NULL,
    group_code character varying(50) NOT NULL,
    code character varying(50) NOT NULL,
    label character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    is_seed_data boolean DEFAULT false NOT NULL,
    effective_from timestamp with time zone,
    effective_to timestamp with time zone,
    parent_id integer,
    metadata jsonb
);

ALTER TABLE public.reference_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reference_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.reference_data
    ADD CONSTRAINT pk_reference_data PRIMARY KEY (id);

ALTER TABLE ONLY public.reference_data
    ADD CONSTRAINT fk_reference_data_reference_data_parent_id FOREIGN KEY (parent_id) REFERENCES public.reference_data(id) ON DELETE RESTRICT;
