CREATE TABLE public.regulatory_sources (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    issuing_body character varying(200),
    domain character varying(60),
    url character varying(1000) NOT NULL,
    feed_type character varying(20) NOT NULL,
    industry_gate character varying(40),
    is_active boolean NOT NULL,
    last_polled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.regulatory_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regulatory_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.regulatory_sources
    ADD CONSTRAINT pk_regulatory_sources PRIMARY KEY (id);
