CREATE TABLE public.regulatory_change_proposals (
    id integer NOT NULL,
    regulatory_source_id integer NOT NULL,
    title character varying(300) NOT NULL,
    summary_url character varying(1000),
    details character varying(4000),
    status character varying(20) NOT NULL,
    target_event_type_id integer,
    reviewed_by_user_id integer,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.regulatory_change_proposals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regulatory_change_proposals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.regulatory_change_proposals
    ADD CONSTRAINT pk_regulatory_change_proposals PRIMARY KEY (id);

ALTER TABLE ONLY public.regulatory_change_proposals
    ADD CONSTRAINT fk_regulatory_change_proposals__regulatory_sources_regulatory_source_id FOREIGN KEY (regulatory_source_id) REFERENCES public.regulatory_sources(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.regulatory_change_proposals
    ADD CONSTRAINT fk_regulatory_change_proposals__calendar_event_types_target_event_type_id FOREIGN KEY (target_event_type_id) REFERENCES public.calendar_event_types(id) ON DELETE SET NULL;
