CREATE TABLE public.reorder_suggestions (
    id integer NOT NULL,
    part_id integer NOT NULL,
    vendor_id integer,
    current_stock numeric(18,4) NOT NULL,
    available_stock numeric(18,4) NOT NULL,
    burn_rate_daily_avg numeric(18,6) NOT NULL,
    burn_rate_window_days integer NOT NULL,
    days_of_stock_remaining integer,
    projected_stockout_date timestamp with time zone,
    incoming_po_quantity numeric(18,4) NOT NULL,
    earliest_po_arrival timestamp with time zone,
    suggested_quantity numeric(18,4) NOT NULL,
    status integer NOT NULL,
    approved_by_user_id integer,
    approved_at timestamp with time zone,
    resulting_purchase_order_id integer,
    dismissed_by_user_id integer,
    dismissed_at timestamp with time zone,
    dismiss_reason character varying(500),
    notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.reorder_suggestions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reorder_suggestions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.reorder_suggestions
    ADD CONSTRAINT pk_reorder_suggestions PRIMARY KEY (id);

ALTER TABLE ONLY public.reorder_suggestions
    ADD CONSTRAINT fk_reorder_suggestions__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.reorder_suggestions
    ADD CONSTRAINT fk_reorder_suggestions_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.reorder_suggestions
    ADD CONSTRAINT "fk_reorder_suggestions_purchase_orders_resulting_purchase_orde~" FOREIGN KEY (resulting_purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;
