CREATE TABLE public.report_schedules (
    id integer NOT NULL,
    saved_report_id integer NOT NULL,
    cron_expression character varying(100) NOT NULL,
    recipient_emails_json text NOT NULL,
    format integer NOT NULL,
    is_active boolean NOT NULL,
    last_sent_at timestamp with time zone,
    next_run_at timestamp with time zone,
    subject_template character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.report_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.report_schedules
    ADD CONSTRAINT pk_report_schedules PRIMARY KEY (id);

ALTER TABLE ONLY public.report_schedules
    ADD CONSTRAINT fk_report_schedules__saved_reports_saved_report_id FOREIGN KEY (saved_report_id) REFERENCES public.saved_reports(id) ON DELETE CASCADE;
