CREATE TABLE public.request_for_quotes (
    id integer NOT NULL,
    rfq_number character varying(20) NOT NULL,
    part_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    required_date timestamp with time zone NOT NULL,
    status integer NOT NULL,
    description character varying(2000),
    special_instructions character varying(4000),
    response_deadline timestamp with time zone,
    sent_at timestamp with time zone,
    awarded_at timestamp with time zone,
    awarded_vendor_response_id integer,
    generated_purchase_order_id integer,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.request_for_quotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_for_quotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.request_for_quotes
    ADD CONSTRAINT pk_request_for_quotes PRIMARY KEY (id);

ALTER TABLE ONLY public.request_for_quotes
    ADD CONSTRAINT fk_request_for_quotes_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
