CREATE TABLE public.reservations (
    id integer NOT NULL,
    part_id integer NOT NULL,
    bin_content_id integer NOT NULL,
    job_id integer,
    sales_order_line_id integer,
    quantity numeric(18,4) NOT NULL,
    notes character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT pk_reservations PRIMARY KEY (id);

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_reservations__sales_order_lines_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES public.sales_order_lines(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_reservations_bin_contents_bin_content_id FOREIGN KEY (bin_content_id) REFERENCES public.bin_contents(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_reservations_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_reservations_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
