CREATE TABLE public.retail_buyers (
    id integer NOT NULL,
    channel_id integer NOT NULL,
    external_buyer_id character varying(200) NOT NULL,
    display_name character varying(200) NOT NULL,
    contact_email character varying(200),
    phone character varying(50),
    marketing_consent boolean NOT NULL,
    first_order_at timestamp with time zone,
    last_order_at timestamp with time zone,
    order_count integer NOT NULL,
    purge_after timestamp with time zone,
    purged_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.retail_buyers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retail_buyers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.retail_buyers
    ADD CONSTRAINT pk_retail_buyers PRIMARY KEY (id);

ALTER TABLE ONLY public.retail_buyers
    ADD CONSTRAINT fk_retail_buyers__sales_channels_channel_id FOREIGN KEY (channel_id) REFERENCES public.sales_channels(id) ON DELETE RESTRICT;
