CREATE TABLE public.rfq_vendor_responses (
    id integer NOT NULL,
    rfq_id integer NOT NULL,
    vendor_id integer NOT NULL,
    response_status integer NOT NULL,
    unit_price numeric(18,4),
    lead_time_days integer,
    minimum_order_quantity numeric(18,4),
    tooling_cost numeric(18,4),
    quote_valid_until timestamp with time zone,
    notes character varying(2000),
    invited_at timestamp with time zone,
    responded_at timestamp with time zone,
    is_awarded boolean NOT NULL,
    decline_reason character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.rfq_vendor_responses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rfq_vendor_responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.rfq_vendor_responses
    ADD CONSTRAINT pk_rfq_vendor_responses PRIMARY KEY (id);

ALTER TABLE ONLY public.rfq_vendor_responses
    ADD CONSTRAINT fk_rfq_vendor_responses__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.rfq_vendor_responses
    ADD CONSTRAINT fk_rfq_vendor_responses_request_for_quotes_rfq_id FOREIGN KEY (rfq_id) REFERENCES public.request_for_quotes(id) ON DELETE CASCADE;
