CREATE TABLE public.role_templates (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    is_system_default boolean NOT NULL,
    included_role_names_json character varying(2000) NOT NULL,
    deactivated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.role_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.role_templates
    ADD CONSTRAINT pk_role_templates PRIMARY KEY (id);
