CREATE TABLE public.sales_order_stage_lines (
    id integer NOT NULL,
    sales_order_stage_id integer NOT NULL,
    sales_order_line_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sales_order_stage_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_order_stage_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sales_order_stage_lines
    ADD CONSTRAINT pk_sales_order_stage_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.sales_order_stage_lines
    ADD CONSTRAINT fk_sales_order_stage_lines_sales_order_stages_sales_order_stage_id FOREIGN KEY (sales_order_stage_id) REFERENCES public.sales_order_stages(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.sales_order_stage_lines
    ADD CONSTRAINT fk_sales_order_stage_lines_sales_order_lines_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES public.sales_order_lines(id) ON DELETE CASCADE;
