CREATE TABLE public.sales_orders (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    order_number character varying(20) NOT NULL,
    customer_id integer NOT NULL,
    quote_id integer,
    shipping_address_id integer,
    billing_address_id integer,
    status integer NOT NULL,
    credit_terms integer,
    confirmed_date timestamp with time zone,
    requested_delivery_date timestamp with time zone,
    customer_po character varying(50),
    notes character varying(2000),
    tax_rate numeric(8,6) NOT NULL,
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sales_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT pk_sales_orders PRIMARY KEY (id);

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT fk_sales_orders_customer_addresses_billing_address_id FOREIGN KEY (billing_address_id) REFERENCES public.customer_addresses(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT fk_sales_orders_customer_addresses_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES public.customer_addresses(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT fk_sales_orders_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT fk_sales_orders_quotes_quote_id FOREIGN KEY (quote_id) REFERENCES public.quotes(id) ON DELETE SET NULL;
