CREATE TABLE public.sales_tax_rates (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(20) NOT NULL,
    state_code character varying(2),
    rate numeric(8,6) NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    description character varying(500),
    exempt_flag boolean DEFAULT false NOT NULL,
    gl_posting_account character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sales_tax_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_tax_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sales_tax_rates
    ADD CONSTRAINT pk_sales_tax_rates PRIMARY KEY (id);
