-- Customer acceptance-of-terms proof for a Sales Order. One record per acceptance attempt across
-- ALL capture channels (manual upload / fax / email / verbal / quote-portal / public accept portal /
-- e-signature provider / customer external system). The production gate reads "does an Accepted row
-- exist for this SO"; the channel that produced it is irrelevant to the gate.
CREATE TABLE public.sales_order_acceptances (
    id integer NOT NULL,
    sales_order_id integer NOT NULL,
    -- Pending (request sent / awaiting) | Accepted | Declined | Revoked | Expired
    status character varying(20) DEFAULT 'Pending'::character varying NOT NULL,
    -- ManualUpload | Fax | Email | Verbal | QuotePortal | PublicPortal | ESignature | ExternalSystem
    method character varying(30) NOT NULL,
    -- Evidence document (signed PDF), when the channel produces one.
    file_attachment_id integer,
    -- Staff member who recorded an offline acceptance (upload/fax/email/verbal).
    recorded_by_user_id integer,
    -- Customer-side identity captured by portal / e-sign (typed name) and optional contact link.
    accepted_by_name character varying(200),
    accepted_by_contact_id integer,
    -- E-signature provider metadata (DocuSeal / DocuSign / …) and its submission/reference id.
    provider character varying(50),
    provider_reference character varying(200),
    -- Public accept portal: unguessable link token + a hash of the second key the customer must prove.
    access_token character varying(128),
    verification_key_hash character varying(200),
    sent_to character varying(320),
    ip_address character varying(64),
    note character varying(1000),
    -- Request expiry for portal / e-sign flows.
    expires_at timestamp with time zone,
    accepted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sales_order_acceptances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_order_acceptances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sales_order_acceptances
    ADD CONSTRAINT pk_sales_order_acceptances PRIMARY KEY (id);

ALTER TABLE ONLY public.sales_order_acceptances
    ADD CONSTRAINT fk_sales_order_acceptances_sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.sales_order_acceptances
    ADD CONSTRAINT fk_sales_order_acceptances_file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.sales_order_acceptances
    ADD CONSTRAINT fk_sales_order_acceptances__asp_net_users_recorded_by_user_id FOREIGN KEY (recorded_by_user_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.sales_order_acceptances
    ADD CONSTRAINT fk_sales_order_acceptances_contacts_accepted_by_contact_id FOREIGN KEY (accepted_by_contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
