CREATE TABLE public.sales_order_lines (
    id integer NOT NULL,
    sales_order_id integer NOT NULL,
    part_id integer,
    description character varying(500) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    line_number integer NOT NULL,
    shipped_quantity numeric(18,4) NOT NULL,
    notes character varying(1000),
    uom_id integer,
    tax_code text
);

ALTER TABLE public.sales_order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sales_order_lines
    ADD CONSTRAINT pk_sales_order_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.sales_order_lines
    ADD CONSTRAINT fk_sales_order_lines__units_of_measure_uom_id FOREIGN KEY (uom_id) REFERENCES public.units_of_measure(id);

ALTER TABLE ONLY public.sales_order_lines
    ADD CONSTRAINT fk_sales_order_lines_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.sales_order_lines
    ADD CONSTRAINT fk_sales_order_lines_sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE CASCADE;
