CREATE TABLE public.sales_channels (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    code character varying(40) NOT NULL,
    description character varying(1000),
    channel_type character varying(20) NOT NULL,
    sold_to_customer_id integer,
    tax_collected_by character varying(20) NOT NULL,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    order_number_prefix character varying(10),
    ecommerce_integration_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sales_channels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_channels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sales_channels
    ADD CONSTRAINT pk_sales_channels PRIMARY KEY (id);

ALTER TABLE ONLY public.sales_channels
    ADD CONSTRAINT fk_sales_channels_customers_sold_to_customer_id FOREIGN KEY (sold_to_customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.sales_channels
    ADD CONSTRAINT "fk_sales_channels_ecommerce_integrations_ecommerce_integration~" FOREIGN KEY (ecommerce_integration_id) REFERENCES public.ecommerce_integrations(id) ON DELETE SET NULL;
