CREATE TABLE public.sales_order_stages (
    id integer NOT NULL,
    sales_order_id integer NOT NULL,
    sequence integer NOT NULL,
    name character varying(200) NOT NULL,
    status character varying(20) DEFAULT 'Planned'::character varying NOT NULL,
    planned_production_complete timestamp with time zone,
    planned_ship_date timestamp with time zone,
    actual_ship_date timestamp with time zone,
    shipment_id integer,
    payment_milestone_id integer,
    notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sales_order_stages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_order_stages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sales_order_stages
    ADD CONSTRAINT pk_sales_order_stages PRIMARY KEY (id);

ALTER TABLE ONLY public.sales_order_stages
    ADD CONSTRAINT fk_sales_order_stages_sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.sales_order_stages
    ADD CONSTRAINT fk_sales_order_stages_shipments_shipment_id FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.sales_order_stages
    ADD CONSTRAINT fk_sales_order_stages_payment_milestones_payment_milestone_id FOREIGN KEY (payment_milestone_id) REFERENCES public.payment_milestones(id) ON DELETE SET NULL;
