CREATE TABLE public.sample_shipments (
    id integer NOT NULL,
    lead_id integer NOT NULL,
    part_id integer,
    part_description character varying(500),
    quantity integer NOT NULL,
    status character varying(40) NOT NULL,
    requested_at timestamp with time zone,
    shipped_at timestamp with time zone,
    delivered_at timestamp with time zone,
    cost_to_us numeric(18,4),
    charged_amount numeric(18,4),
    tracking_number character varying(100),
    carrier character varying(50),
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sample_shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sample_shipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sample_shipments
    ADD CONSTRAINT pk_sample_shipments PRIMARY KEY (id);

ALTER TABLE ONLY public.sample_shipments
    ADD CONSTRAINT fk_sample_shipments_leads_lead_id FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE;
