CREATE TABLE public.saved_reports (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(500),
    entity_source character varying(50) NOT NULL,
    columns_json jsonb NOT NULL,
    filters_json jsonb,
    group_by_field character varying(100),
    sort_field character varying(100),
    sort_direction character varying(10),
    chart_type character varying(20),
    chart_label_field character varying(100),
    chart_value_field character varying(100),
    is_shared boolean NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.saved_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.saved_reports
    ADD CONSTRAINT pk_saved_reports PRIMARY KEY (id);

ALTER TABLE ONLY public.saved_reports
    ADD CONSTRAINT fk_saved_reports__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;
