CREATE TABLE public.scan_action_logs (
    id integer NOT NULL,
    user_id integer NOT NULL,
    action_type character varying(20) NOT NULL,
    part_id integer,
    part_number character varying(100),
    from_location_id integer,
    to_location_id integer,
    quantity numeric(18,4) NOT NULL,
    related_entity_id integer,
    related_entity_type character varying(50),
    reversed_by_log_id integer,
    reverses_log_id integer,
    is_reversed boolean NOT NULL,
    is_training_mode boolean NOT NULL,
    kiosk_id character varying(100),
    device_id character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.scan_action_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scan_action_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.scan_action_logs
    ADD CONSTRAINT pk_scan_action_logs PRIMARY KEY (id);

ALTER TABLE ONLY public.scan_action_logs
    ADD CONSTRAINT fk_scan_action_logs__storage_locations_from_location_id FOREIGN KEY (from_location_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.scan_action_logs
    ADD CONSTRAINT fk_scan_action_logs__storage_locations_to_location_id FOREIGN KEY (to_location_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.scan_action_logs
    ADD CONSTRAINT fk_scan_action_logs_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
