CREATE TABLE public.scheduled_tasks (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(2000),
    track_type_id integer NOT NULL,
    internal_project_type_id integer,
    assignee_id integer,
    cron_expression character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    last_run_at timestamp with time zone,
    next_run_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.scheduled_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduled_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.scheduled_tasks
    ADD CONSTRAINT pk_scheduled_tasks PRIMARY KEY (id);

ALTER TABLE ONLY public.scheduled_tasks
    ADD CONSTRAINT fk_scheduled_tasks__track_types_track_type_id FOREIGN KEY (track_type_id) REFERENCES public.track_types(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.scheduled_tasks
    ADD CONSTRAINT fk_scheduled_tasks_reference_data_internal_project_type_id FOREIGN KEY (internal_project_type_id) REFERENCES public.reference_data(id) ON DELETE SET NULL;
