CREATE TABLE public.schedule_runs (
    id integer NOT NULL,
    run_date timestamp with time zone NOT NULL,
    direction integer NOT NULL,
    status integer NOT NULL,
    parameters_json jsonb NOT NULL,
    operations_scheduled integer NOT NULL,
    conflicts_detected integer NOT NULL,
    completed_at timestamp with time zone,
    run_by_user_id integer NOT NULL,
    error_message character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.schedule_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.schedule_runs
    ADD CONSTRAINT pk_schedule_runs PRIMARY KEY (id);
