CREATE TABLE public.schedule_milestones (
    id integer NOT NULL,
    sales_order_line_id integer NOT NULL,
    job_id integer,
    milestone_type character varying(50) NOT NULL,
    target_date timestamp with time zone NOT NULL,
    actual_date timestamp with time zone,
    notes text
);

ALTER TABLE public.schedule_milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.schedule_milestones
    ADD CONSTRAINT pk_schedule_milestones PRIMARY KEY (id);

ALTER TABLE ONLY public.schedule_milestones
    ADD CONSTRAINT fk_schedule_milestones_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.schedule_milestones
    ADD CONSTRAINT fk_schedule_milestones_sales_order_lines_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES public.sales_order_lines(id) ON DELETE CASCADE;
