CREATE TABLE public.scheduled_operations (
    id integer NOT NULL,
    job_id integer NOT NULL,
    operation_id integer NOT NULL,
    work_center_id integer NOT NULL,
    scheduled_start timestamp with time zone NOT NULL,
    scheduled_end timestamp with time zone NOT NULL,
    setup_start timestamp with time zone,
    setup_end timestamp with time zone,
    run_start timestamp with time zone,
    run_end timestamp with time zone,
    setup_hours numeric(10,4) NOT NULL,
    run_hours numeric(10,4) NOT NULL,
    total_hours numeric(10,4) NOT NULL,
    status integer NOT NULL,
    sequence_number integer NOT NULL,
    is_locked boolean NOT NULL,
    schedule_run_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.scheduled_operations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduled_operations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.scheduled_operations
    ADD CONSTRAINT pk_scheduled_operations PRIMARY KEY (id);

ALTER TABLE ONLY public.scheduled_operations
    ADD CONSTRAINT fk_scheduled_operations__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.scheduled_operations
    ADD CONSTRAINT fk_scheduled_operations_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.scheduled_operations
    ADD CONSTRAINT fk_scheduled_operations_operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.scheduled_operations
    ADD CONSTRAINT fk_scheduled_operations_schedule_runs_schedule_run_id FOREIGN KEY (schedule_run_id) REFERENCES public.schedule_runs(id) ON DELETE SET NULL;
