CREATE TABLE public.sequence_definitions (
    id integer NOT NULL,
    -- Gated Sequence Engine (CAP-CROSS-SEQUENCES). Natural key (code, version); immutable once Published.
    code character varying(100) NOT NULL,
    version integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(2000),
    subject_entity_type character varying(50),
    -- 'Draft' | 'Published' | 'Retired'
    status character varying(20) NOT NULL,
    published_at timestamp with time zone,
    published_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sequence_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_definitions
    ADD CONSTRAINT pk_sequence_definitions PRIMARY KEY (id);

