CREATE TABLE public.sequence_step_definitions (
    id integer NOT NULL,
    definition_id integer NOT NULL,
    key character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(2000),
    sort_order integer NOT NULL,
    -- 'All' | 'Any'
    join_policy character varying(10) NOT NULL,
    max_dwell_minutes integer,
    -- 'Block' | 'Flag' | 'Escalate'
    dwell_expiry_action character varying(20) NOT NULL,
    escalate_role character varying(100)
);

ALTER TABLE public.sequence_step_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_step_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_step_definitions
    ADD CONSTRAINT pk_sequence_step_definitions PRIMARY KEY (id);

ALTER TABLE ONLY public.sequence_step_definitions
    ADD CONSTRAINT fk_sequence_step_definitions__sequence_definitions_definition_id FOREIGN KEY (definition_id) REFERENCES public.sequence_definitions(id) ON DELETE CASCADE;
