CREATE TABLE public.sequence_events (
    id integer NOT NULL,
    instance_id integer NOT NULL,
    -- append-only audit trail; SequenceEventType name
    type character varying(30) NOT NULL,
    step_key character varying(100),
    gate_key character varying(100),
    payload_json jsonb,
    occurred_at timestamp with time zone NOT NULL,
    actor_user_id integer
);

ALTER TABLE public.sequence_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_events
    ADD CONSTRAINT pk_sequence_events PRIMARY KEY (id);

ALTER TABLE ONLY public.sequence_events
    ADD CONSTRAINT fk_sequence_events__sequence_instances_instance_id FOREIGN KEY (instance_id) REFERENCES public.sequence_instances(id) ON DELETE CASCADE;
