CREATE TABLE public.sequence_gate_instances (
    id integer NOT NULL,
    instance_id integer NOT NULL,
    step_key character varying(100) NOT NULL,
    gate_key character varying(100) NOT NULL,
    -- 'Unknown' | 'Go' | 'NoGo'
    verdict character varying(10) NOT NULL,
    last_evaluated_at timestamp with time zone,
    reason character varying(2000),
    cleared_at timestamp with time zone,
    cleared_by_user_id integer,
    overridden_at timestamp with time zone,
    overridden_by_user_id integer,
    override_reason character varying(2000)
);

ALTER TABLE public.sequence_gate_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_gate_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_gate_instances
    ADD CONSTRAINT pk_sequence_gate_instances PRIMARY KEY (id);

ALTER TABLE ONLY public.sequence_gate_instances
    ADD CONSTRAINT fk_sequence_gate_instances__sequence_instances_instance_id FOREIGN KEY (instance_id) REFERENCES public.sequence_instances(id) ON DELETE CASCADE;
