CREATE TABLE public.sequence_resource_clocks (
    id integer NOT NULL,
    -- clock keyed by RESOURCE (polymorphic, no FK) so it travels with the resource between steps/instances
    resource_type character varying(50) NOT NULL,
    resource_id integer NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    -- 'Block' | 'Flag' | 'Escalate'
    expiry_action character varying(20) NOT NULL,
    escalate_role character varying(100),
    note character varying(2000),
    fired_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sequence_resource_clocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_resource_clocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_resource_clocks
    ADD CONSTRAINT pk_sequence_resource_clocks PRIMARY KEY (id);

