CREATE TABLE public.sequence_gate_definitions (
    id integer NOT NULL,
    definition_id integer NOT NULL,
    step_key character varying(100) NOT NULL,
    key character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    -- 'ManualClearance' | 'TimeWindow' | 'ResourceClock' | 'Approval' | 'Custom'
    source_type character varying(30) NOT NULL,
    config_json jsonb NOT NULL,
    -- 'Block' | 'Flag' | 'Escalate'
    expiry_action character varying(20) NOT NULL,
    escalate_role character varying(100)
);

ALTER TABLE public.sequence_gate_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_gate_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_gate_definitions
    ADD CONSTRAINT pk_sequence_gate_definitions PRIMARY KEY (id);

ALTER TABLE ONLY public.sequence_gate_definitions
    ADD CONSTRAINT fk_sequence_gate_definitions__sequence_definitions_definition_id FOREIGN KEY (definition_id) REFERENCES public.sequence_definitions(id) ON DELETE CASCADE;
