CREATE TABLE public.sequence_edge_definitions (
    id integer NOT NULL,
    definition_id integer NOT NULL,
    from_step_key character varying(100) NOT NULL,
    to_step_key character varying(100) NOT NULL,
    -- declared back-edge (rework loop); the only permitted cycles
    is_rework boolean NOT NULL
);

ALTER TABLE public.sequence_edge_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_edge_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_edge_definitions
    ADD CONSTRAINT pk_sequence_edge_definitions PRIMARY KEY (id);

ALTER TABLE ONLY public.sequence_edge_definitions
    ADD CONSTRAINT fk_sequence_edge_definitions__sequence_definitions_definition_id FOREIGN KEY (definition_id) REFERENCES public.sequence_definitions(id) ON DELETE CASCADE;
