CREATE TABLE public.sequence_step_instances (
    id integer NOT NULL,
    instance_id integer NOT NULL,
    step_key character varying(100) NOT NULL,
    -- 'Pending' | 'Ready' | 'InProgress' | 'Complete' | 'Skipped' (Blocked is derived, never stored)
    status character varying(20) NOT NULL,
    ready_at timestamp with time zone,
    started_at timestamp with time zone,
    started_by_user_id integer,
    completed_at timestamp with time zone,
    completed_by_user_id integer,
    skip_reason character varying(2000),
    dwell_expires_at timestamp with time zone,
    dwell_fired_at timestamp with time zone
);

ALTER TABLE public.sequence_step_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_step_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_step_instances
    ADD CONSTRAINT pk_sequence_step_instances PRIMARY KEY (id);

ALTER TABLE ONLY public.sequence_step_instances
    ADD CONSTRAINT fk_sequence_step_instances__sequence_instances_instance_id FOREIGN KEY (instance_id) REFERENCES public.sequence_instances(id) ON DELETE CASCADE;
