CREATE TABLE public.sequence_instances (
    id integer NOT NULL,
    definition_id integer NOT NULL,
    subject_entity_type character varying(50),
    subject_entity_id integer,
    -- 'Running' | 'Completed' | 'Cancelled'
    status character varying(20) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    started_by_user_id integer,
    completed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    cancelled_by_user_id integer,
    cancel_reason character varying(2000),
    version bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.sequence_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequence_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequence_instances
    ADD CONSTRAINT pk_sequence_instances PRIMARY KEY (id);

ALTER TABLE ONLY public.sequence_instances
    ADD CONSTRAINT fk_sequence_instances__sequence_definitions_definition_id FOREIGN KEY (definition_id) REFERENCES public.sequence_definitions(id) ON DELETE RESTRICT;
