CREATE TABLE public.serial_histories (
    id integer NOT NULL,
    serial_number_id integer NOT NULL,
    action character varying(50) NOT NULL,
    from_location_name character varying(200),
    to_location_name character varying(200),
    actor_id integer,
    details character varying(2000),
    occurred_at timestamp with time zone NOT NULL
);

ALTER TABLE public.serial_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.serial_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.serial_histories
    ADD CONSTRAINT pk_serial_histories PRIMARY KEY (id);

ALTER TABLE ONLY public.serial_histories
    ADD CONSTRAINT fk_serial_histories__serial_numbers_serial_number_id FOREIGN KEY (serial_number_id) REFERENCES public.serial_numbers(id) ON DELETE CASCADE;
