CREATE TABLE public.serial_numbers (
    id integer NOT NULL,
    part_id integer NOT NULL,
    serial_value character varying(100) NOT NULL,
    status integer NOT NULL,
    job_id integer,
    lot_record_id integer,
    current_location_id integer,
    shipment_line_id integer,
    customer_id integer,
    parent_serial_id integer,
    manufactured_at timestamp with time zone,
    shipped_at timestamp with time zone,
    scrapped_at timestamp with time zone,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.serial_numbers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.serial_numbers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.serial_numbers
    ADD CONSTRAINT pk_serial_numbers PRIMARY KEY (id);

ALTER TABLE ONLY public.serial_numbers
    ADD CONSTRAINT fk_serial_numbers__storage_locations_current_location_id FOREIGN KEY (current_location_id) REFERENCES public.storage_locations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.serial_numbers
    ADD CONSTRAINT fk_serial_numbers_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.serial_numbers
    ADD CONSTRAINT fk_serial_numbers_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.serial_numbers
    ADD CONSTRAINT fk_serial_numbers_serial_numbers_parent_serial_id FOREIGN KEY (parent_serial_id) REFERENCES public.serial_numbers(id) ON DELETE SET NULL;
