CREATE TABLE public.shift_assignments (
    id integer NOT NULL,
    user_id integer NOT NULL,
    shift_id integer NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    shift_differential_rate numeric(10,4),
    notes character varying(1000)
);

ALTER TABLE public.shift_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shift_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.shift_assignments
    ADD CONSTRAINT pk_shift_assignments PRIMARY KEY (id);

ALTER TABLE ONLY public.shift_assignments
    ADD CONSTRAINT fk_shift_assignments_shifts_shift_id FOREIGN KEY (shift_id) REFERENCES public.shifts(id) ON DELETE RESTRICT;
