CREATE TABLE public.shifts (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    break_minutes integer NOT NULL,
    net_hours numeric(8,2) NOT NULL,
    is_active boolean NOT NULL,
    working_calendar_id integer,
    days_of_week_mask integer,
    premium_multiplier numeric(5,2) DEFAULT 1.0 NOT NULL,
    capacity_hours numeric(8,2) DEFAULT 0.0 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.shifts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shifts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.shifts
    ADD CONSTRAINT pk_shifts PRIMARY KEY (id);

ALTER TABLE ONLY public.shifts
    ADD CONSTRAINT fk_shifts__working_calendars_working_calendar_id FOREIGN KEY (working_calendar_id) REFERENCES public.working_calendars(id) ON DELETE CASCADE;
