CREATE TABLE public.shipment_lines (
    id integer NOT NULL,
    shipment_id integer NOT NULL,
    sales_order_line_id integer,
    part_id integer,
    quantity numeric(18,4) NOT NULL,
    notes character varying(1000),
    description character varying(500),
    weight numeric(12,4),
    length numeric(12,4),
    width numeric(12,4),
    height numeric(12,4),
    is_hazmat boolean DEFAULT false NOT NULL,
    handling_instructions character varying(1000),
    serial_numbers character varying(2000),
    inventory_relieved_at timestamp with time zone
);

ALTER TABLE public.shipment_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT pk_shipment_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT fk_shipment_lines_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT fk_shipment_lines_sales_order_lines_sales_order_line_id FOREIGN KEY (sales_order_line_id) REFERENCES public.sales_order_lines(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT fk_shipment_lines_shipments_shipment_id FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE CASCADE;
