CREATE TABLE public.shipment_packages (
    id integer NOT NULL,
    shipment_id integer NOT NULL,
    tracking_number character varying(200),
    carrier character varying(100),
    weight numeric(10,2),
    length numeric(10,2),
    width numeric(10,2),
    height numeric(10,2),
    status character varying(50) NOT NULL
);

ALTER TABLE public.shipment_packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.shipment_packages
    ADD CONSTRAINT pk_shipment_packages PRIMARY KEY (id);

ALTER TABLE ONLY public.shipment_packages
    ADD CONSTRAINT fk_shipment_packages_shipments_shipment_id FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE CASCADE;
