CREATE TABLE public.shipments (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    shipment_number character varying(20) NOT NULL,
    sales_order_id integer NOT NULL,
    shipping_address_id integer,
    status integer NOT NULL,
    carrier character varying(100),
    tracking_number character varying(100),
    shipped_date timestamp with time zone,
    delivered_date timestamp with time zone,
    shipping_cost numeric(18,4),
    weight numeric(12,4),
    notes character varying(2000),
    service_type character varying(200),
    estimated_delivery_date timestamp with time zone,
    freight_class character varying(50),
    insured_value numeric(18,4),
    signature_required boolean DEFAULT false NOT NULL,
    bill_of_lading_number character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT pk_shipments PRIMARY KEY (id);

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT fk_shipments_customer_addresses_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES public.customer_addresses(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT fk_shipments_sales_orders_sales_order_id FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id) ON DELETE RESTRICT;
