CREATE TABLE public.spc_control_limits (
    id integer NOT NULL,
    characteristic_id integer NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    sample_count integer NOT NULL,
    from_subgroup integer NOT NULL,
    to_subgroup integer NOT NULL,
    xbar_ucl numeric(18,6) NOT NULL,
    xbar_lcl numeric(18,6) NOT NULL,
    xbar_center_line numeric(18,6) NOT NULL,
    range_ucl numeric(18,6) NOT NULL,
    range_lcl numeric(18,6) NOT NULL,
    range_center_line numeric(18,6) NOT NULL,
    sucl numeric(18,6),
    slcl numeric(18,6),
    scenter_line numeric(18,6),
    cp numeric(10,4) NOT NULL,
    cpk numeric(10,4) NOT NULL,
    pp numeric(10,4) NOT NULL,
    ppk numeric(10,4) NOT NULL,
    process_sigma numeric(18,6) NOT NULL,
    is_active boolean NOT NULL
);

ALTER TABLE public.spc_control_limits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spc_control_limits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.spc_control_limits
    ADD CONSTRAINT pk_spc_control_limits PRIMARY KEY (id);

ALTER TABLE ONLY public.spc_control_limits
    ADD CONSTRAINT fk_spc_control_limits_spc_characteristics_characteristic_id FOREIGN KEY (characteristic_id) REFERENCES public.spc_characteristics(id) ON DELETE CASCADE;
