CREATE TABLE public.spc_characteristics (
    id integer NOT NULL,
    part_id integer NOT NULL,
    operation_id integer,
    name character varying(200) NOT NULL,
    description character varying(1000),
    measurement_type integer NOT NULL,
    nominal_value numeric(18,6) NOT NULL,
    upper_spec_limit numeric(18,6) NOT NULL,
    lower_spec_limit numeric(18,6) NOT NULL,
    unit_of_measure character varying(50),
    decimal_places integer NOT NULL,
    sample_size integer NOT NULL,
    sample_frequency character varying(200),
    gage_id integer,
    is_active boolean NOT NULL,
    notify_on_ooc boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.spc_characteristics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spc_characteristics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.spc_characteristics
    ADD CONSTRAINT pk_spc_characteristics PRIMARY KEY (id);

ALTER TABLE ONLY public.spc_characteristics
    ADD CONSTRAINT fk_spc_characteristics_operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.spc_characteristics
    ADD CONSTRAINT fk_spc_characteristics_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE RESTRICT;
