CREATE TABLE public.spc_ooc_events (
    id integer NOT NULL,
    characteristic_id integer NOT NULL,
    measurement_id integer NOT NULL,
    detected_at timestamp with time zone NOT NULL,
    rule_name character varying(200) NOT NULL,
    description character varying(2000) NOT NULL,
    severity integer NOT NULL,
    status integer NOT NULL,
    acknowledged_by_id integer,
    acknowledged_at timestamp with time zone,
    acknowledgment_notes character varying(2000),
    capa_id integer
);

ALTER TABLE public.spc_ooc_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spc_ooc_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.spc_ooc_events
    ADD CONSTRAINT pk_spc_ooc_events PRIMARY KEY (id);

ALTER TABLE ONLY public.spc_ooc_events
    ADD CONSTRAINT fk_spc_ooc_events__asp_net_users_acknowledged_by_id FOREIGN KEY (acknowledged_by_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.spc_ooc_events
    ADD CONSTRAINT fk_spc_ooc_events_spc_characteristics_characteristic_id FOREIGN KEY (characteristic_id) REFERENCES public.spc_characteristics(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.spc_ooc_events
    ADD CONSTRAINT fk_spc_ooc_events_spc_measurements_measurement_id FOREIGN KEY (measurement_id) REFERENCES public.spc_measurements(id) ON DELETE RESTRICT;
