CREATE TABLE public.spc_measurements (
    id integer NOT NULL,
    characteristic_id integer NOT NULL,
    job_id integer,
    production_run_id integer,
    lot_number character varying(100),
    measured_by_id integer NOT NULL,
    measured_at timestamp with time zone NOT NULL,
    subgroup_number integer NOT NULL,
    values_json jsonb NOT NULL,
    mean numeric(18,6) NOT NULL,
    range numeric(18,6) NOT NULL,
    std_dev numeric(18,6) NOT NULL,
    median numeric(18,6) NOT NULL,
    is_out_of_spec boolean NOT NULL,
    is_out_of_control boolean NOT NULL,
    ooc_rule_violated character varying(200),
    notes character varying(2000)
);

ALTER TABLE public.spc_measurements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spc_measurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.spc_measurements
    ADD CONSTRAINT pk_spc_measurements PRIMARY KEY (id);

ALTER TABLE ONLY public.spc_measurements
    ADD CONSTRAINT fk_spc_measurements__asp_net_users_measured_by_id FOREIGN KEY (measured_by_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.spc_measurements
    ADD CONSTRAINT fk_spc_measurements_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.spc_measurements
    ADD CONSTRAINT fk_spc_measurements_spc_characteristics_characteristic_id FOREIGN KEY (characteristic_id) REFERENCES public.spc_characteristics(id) ON DELETE CASCADE;
