CREATE TABLE public.status_entries (
    id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    status_code character varying(50) NOT NULL,
    status_label character varying(200) NOT NULL,
    category character varying(20) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    notes character varying(2000),
    set_by_id integer,
    work_center_id integer,
    operation_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.status_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.status_entries
    ADD CONSTRAINT pk_status_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.status_entries
    ADD CONSTRAINT fk_status_entries__asp_net_users_set_by_id FOREIGN KEY (set_by_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.status_entries
    ADD CONSTRAINT fk_status_entries__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.status_entries
    ADD CONSTRAINT fk_status_entries_operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE RESTRICT;
