CREATE TABLE public.storage_locations (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    location_type integer NOT NULL,
    parent_id integer,
    barcode character varying(50),
    description character varying(500),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.storage_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.storage_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.storage_locations
    ADD CONSTRAINT pk_storage_locations PRIMARY KEY (id);

ALTER TABLE ONLY public.storage_locations
    ADD CONSTRAINT fk_storage_locations_storage_locations_parent_id FOREIGN KEY (parent_id) REFERENCES public.storage_locations(id) ON DELETE RESTRICT;
