CREATE TABLE public.subcontract_orders (
    id integer NOT NULL,
    job_id integer NOT NULL,
    operation_id integer NOT NULL,
    vendor_id integer NOT NULL,
    purchase_order_id integer,
    quantity numeric(18,4) NOT NULL,
    unit_cost numeric(18,4) NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    expected_return_date timestamp with time zone,
    received_at timestamp with time zone,
    received_by_id integer,
    received_quantity numeric(18,4),
    status character varying(50) NOT NULL,
    shipping_tracking_number character varying(200),
    return_tracking_number character varying(200),
    notes character varying(2000),
    ncr_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.subcontract_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subcontract_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.subcontract_orders
    ADD CONSTRAINT pk_subcontract_orders PRIMARY KEY (id);

ALTER TABLE ONLY public.subcontract_orders
    ADD CONSTRAINT fk_subcontract_orders__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.subcontract_orders
    ADD CONSTRAINT fk_subcontract_orders_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.subcontract_orders
    ADD CONSTRAINT fk_subcontract_orders_operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.subcontract_orders
    ADD CONSTRAINT fk_subcontract_orders_purchase_orders_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;
