CREATE TABLE public.supported_languages (
    id integer NOT NULL,
    code character varying(10) NOT NULL,
    name character varying(100) NOT NULL,
    native_name character varying(100) NOT NULL,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    completion_percent numeric(5,2) NOT NULL
);

ALTER TABLE public.supported_languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supported_languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.supported_languages
    ADD CONSTRAINT pk_supported_languages PRIMARY KEY (id);
