CREATE TABLE public.sync_queue_entries (
    id integer NOT NULL,
    entity_type character varying(100) NOT NULL,
    entity_id integer NOT NULL,
    operation character varying(100) NOT NULL,
    payload text,
    status integer NOT NULL,
    attempt_count integer NOT NULL,
    error_message character varying(2000),
    created_at timestamp with time zone NOT NULL,
    processed_at timestamp with time zone
);

ALTER TABLE public.sync_queue_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sync_queue_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sync_queue_entries
    ADD CONSTRAINT pk_sync_queue_entries PRIMARY KEY (id);
