CREATE TABLE public.system_api_keys (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    key_hash character varying(500) NOT NULL,
    key_prefix character varying(20) NOT NULL,
    user_id integer NOT NULL,
    is_active boolean NOT NULL,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    role_template_id integer,
    scopes_json jsonb,
    allowed_ips_json jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.system_api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.system_api_keys
    ADD CONSTRAINT pk_system_api_keys PRIMARY KEY (id);

ALTER TABLE ONLY public.system_api_keys
    ADD CONSTRAINT fk_system_api_keys__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.system_api_keys
    ADD CONSTRAINT fk_system_api_keys_role_templates_role_template_id FOREIGN KEY (role_template_id) REFERENCES public.role_templates(id) ON DELETE SET NULL;
