CREATE TABLE public.tariff_rates (
    id integer NOT NULL,
    hts_code character varying(20) NOT NULL,
    country_of_origin character varying(2) NOT NULL,
    rate_pct numeric(8,4) NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    source character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.tariff_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tariff_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tariff_rates
    ADD CONSTRAINT pk_tariff_rates PRIMARY KEY (id);
