CREATE TABLE public.tax_documents (
    id integer NOT NULL,
    user_id integer NOT NULL,
    document_type integer NOT NULL,
    tax_year integer NOT NULL,
    employer_name character varying(200),
    file_attachment_id integer,
    source integer NOT NULL,
    external_id character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.tax_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tax_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tax_documents
    ADD CONSTRAINT pk_tax_documents PRIMARY KEY (id);

ALTER TABLE ONLY public.tax_documents
    ADD CONSTRAINT fk_tax_documents_file_attachments_file_attachment_id FOREIGN KEY (file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;
