CREATE TABLE public.terminology_entries (
    id integer NOT NULL,
    key character varying(100) NOT NULL,
    label character varying(500) NOT NULL,
    is_admin_edited boolean DEFAULT false NOT NULL,
    source_preset_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.terminology_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terminology_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.terminology_entries
    ADD CONSTRAINT pk_terminology_entries PRIMARY KEY (id);
