CREATE TABLE public.terms_documents (
    id integer NOT NULL,
    scope character varying(20) NOT NULL,
    customer_id integer,
    part_id integer,
    title character varying(300) NOT NULL,
    summary character varying(1000),
    body_markdown text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    is_active boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    source_file_attachment_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.terms_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.terms_documents
    ADD CONSTRAINT pk_terms_documents PRIMARY KEY (id);

ALTER TABLE ONLY public.terms_documents
    ADD CONSTRAINT fk_terms_documents_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.terms_documents
    ADD CONSTRAINT fk_terms_documents_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.terms_documents
    ADD CONSTRAINT fk_terms_documents_file_attachments_source_file_attachment_id FOREIGN KEY (source_file_attachment_id) REFERENCES public.file_attachments(id) ON DELETE SET NULL;
