CREATE TABLE public.time_correction_logs (
    id integer NOT NULL,
    time_entry_id integer NOT NULL,
    corrected_by_user_id integer NOT NULL,
    reason character varying(500) NOT NULL,
    original_job_id integer,
    original_date date NOT NULL,
    original_duration_minutes integer NOT NULL,
    original_start_time timestamp with time zone,
    original_end_time timestamp with time zone,
    original_category character varying(100),
    original_notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.time_correction_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_correction_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.time_correction_logs
    ADD CONSTRAINT pk_time_correction_logs PRIMARY KEY (id);

ALTER TABLE ONLY public.time_correction_logs
    ADD CONSTRAINT fk_time_correction_logs__time_entries_time_entry_id FOREIGN KEY (time_entry_id) REFERENCES public.time_entries(id) ON DELETE CASCADE;
