CREATE TABLE public.time_entries (
    id integer NOT NULL,
    job_id integer,
    user_id integer NOT NULL,
    date date NOT NULL,
    duration_minutes integer NOT NULL,
    category text,
    notes text,
    timer_start timestamp with time zone,
    timer_stop timestamp with time zone,
    is_manual boolean NOT NULL,
    is_locked boolean NOT NULL,
    accounting_time_activity_id text,
    operation_id integer,
    entry_type integer DEFAULT 0 NOT NULL,
    work_center_id integer,
    labor_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    actual_labor_cost numeric DEFAULT 0.0 NOT NULL,
    burden_cost numeric(18,4) DEFAULT 0.0 NOT NULL,
    is_billable boolean DEFAULT true NOT NULL,
    bill_rate numeric(10,2),
    bill_rate_currency character varying(3),
    activity_type_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.time_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.time_entries
    ADD CONSTRAINT pk_time_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.time_entries
    ADD CONSTRAINT fk_time_entries__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.time_entries
    ADD CONSTRAINT fk_time_entries_jobs_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.time_entries
    ADD CONSTRAINT fk_time_entries_operations_operation_id FOREIGN KEY (operation_id) REFERENCES public.operations(id) ON DELETE SET NULL;
