CREATE TABLE public.track_types (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(500),
    is_default boolean NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    is_shop_floor boolean NOT NULL,
    custom_field_definitions jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.track_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.track_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.track_types
    ADD CONSTRAINT pk_track_types PRIMARY KEY (id);
