CREATE TABLE public.training_path_enrollments (
    id integer NOT NULL,
    user_id integer NOT NULL,
    path_id integer NOT NULL,
    completed_at timestamp with time zone,
    is_auto_assigned boolean NOT NULL,
    assigned_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.training_path_enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_path_enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_path_enrollments
    ADD CONSTRAINT pk_training_path_enrollments PRIMARY KEY (id);

ALTER TABLE ONLY public.training_path_enrollments
    ADD CONSTRAINT fk_training_path_enrollments__asp_net_users_assigned_by_user_id FOREIGN KEY (assigned_by_user_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.training_path_enrollments
    ADD CONSTRAINT fk_training_path_enrollments__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.training_path_enrollments
    ADD CONSTRAINT fk_training_path_enrollments_training_paths_path_id FOREIGN KEY (path_id) REFERENCES public.training_paths(id) ON DELETE CASCADE;
