CREATE TABLE public.training_paths (
    id integer NOT NULL,
    title character varying(300) NOT NULL,
    slug character varying(200) NOT NULL,
    description character varying(2000) NOT NULL,
    icon character varying(100) NOT NULL,
    allowed_roles jsonb,
    is_auto_assigned boolean NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.training_paths ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_paths_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_paths
    ADD CONSTRAINT pk_training_paths PRIMARY KEY (id);
