CREATE TABLE public.training_progress (
    id integer NOT NULL,
    user_id integer NOT NULL,
    module_id integer NOT NULL,
    status integer NOT NULL,
    quiz_score integer,
    quiz_attempts integer,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    time_spent_seconds integer NOT NULL,
    quiz_answers_json jsonb,
    quiz_session_json text,
    walkthrough_step_reached integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.training_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_progress
    ADD CONSTRAINT pk_training_progress PRIMARY KEY (id);

ALTER TABLE ONLY public.training_progress
    ADD CONSTRAINT fk_training_progress__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.training_progress
    ADD CONSTRAINT fk_training_progress_training_modules_module_id FOREIGN KEY (module_id) REFERENCES public.training_modules(id) ON DELETE CASCADE;
