CREATE TABLE public.training_scan_logs (
    id integer NOT NULL,
    user_id integer NOT NULL,
    action_type character varying(20) NOT NULL,
    part_id integer,
    from_location_id integer,
    to_location_id integer,
    quantity integer NOT NULL,
    job_id integer,
    purchase_order_id integer,
    shipment_id integer,
    scanned_at timestamp with time zone NOT NULL,
    was_successful boolean DEFAULT false NOT NULL,
    error_message character varying(500)
);

ALTER TABLE public.training_scan_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_scan_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_scan_logs
    ADD CONSTRAINT pk_training_scan_logs PRIMARY KEY (id);

ALTER TABLE ONLY public.training_scan_logs
    ADD CONSTRAINT fk_training_scan_logs__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT;
