CREATE TABLE public.training_path_translations (
    id integer NOT NULL,
    training_path_id integer NOT NULL,
    locale character varying(10) NOT NULL,
    title character varying(300) NOT NULL,
    description character varying(1000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.training_path_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_path_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_path_translations
    ADD CONSTRAINT pk_training_path_translations PRIMARY KEY (id);

ALTER TABLE ONLY public.training_path_translations
    ADD CONSTRAINT fk_training_path_translations_path FOREIGN KEY (training_path_id) REFERENCES public.training_paths(id) ON DELETE CASCADE;
