CREATE TABLE public.training_path_modules (
    id integer NOT NULL,
    path_id integer NOT NULL,
    module_id integer NOT NULL,
    "position" integer NOT NULL,
    is_required boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.training_path_modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_path_modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_path_modules
    ADD CONSTRAINT pk_training_path_modules PRIMARY KEY (id);

ALTER TABLE ONLY public.training_path_modules
    ADD CONSTRAINT fk_training_path_modules_training_modules_module_id FOREIGN KEY (module_id) REFERENCES public.training_modules(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.training_path_modules
    ADD CONSTRAINT fk_training_path_modules_training_paths_path_id FOREIGN KEY (path_id) REFERENCES public.training_paths(id) ON DELETE CASCADE;
