CREATE TABLE public.training_module_translations (
    id integer NOT NULL,
    training_module_id integer NOT NULL,
    locale character varying(10) NOT NULL,
    title character varying(300) NOT NULL,
    summary character varying(1000) NOT NULL,
    content_json jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.training_module_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_module_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_module_translations
    ADD CONSTRAINT pk_training_module_translations PRIMARY KEY (id);

ALTER TABLE ONLY public.training_module_translations
    ADD CONSTRAINT fk_training_module_translations_module FOREIGN KEY (training_module_id) REFERENCES public.training_modules(id) ON DELETE CASCADE;
