CREATE TABLE public.training_modules (
    id integer NOT NULL,
    title character varying(300) NOT NULL,
    slug character varying(200) NOT NULL,
    summary character varying(1000) NOT NULL,
    content_type integer NOT NULL,
    content_json jsonb NOT NULL,
    cover_image_url character varying(500),
    estimated_minutes integer NOT NULL,
    tags jsonb,
    app_routes jsonb,
    is_published boolean NOT NULL,
    is_onboarding_required boolean NOT NULL,
    sort_order integer NOT NULL,
    created_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.training_modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.training_modules
    ADD CONSTRAINT pk_training_modules PRIMARY KEY (id);

ALTER TABLE ONLY public.training_modules
    ADD CONSTRAINT fk_training_modules__asp_net_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES public.asp_net_users(id) ON DELETE SET NULL;
