CREATE TABLE public.translated_labels (
    id integer NOT NULL,
    key character varying(200) NOT NULL,
    language_code character varying(10) NOT NULL,
    value character varying(2000) NOT NULL,
    context character varying(100),
    is_approved boolean NOT NULL,
    translated_by_id integer,
    translated_at timestamp with time zone
);

ALTER TABLE public.translated_labels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.translated_labels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.translated_labels
    ADD CONSTRAINT pk_translated_labels PRIMARY KEY (id);
