CREATE TABLE public.units_of_measure (
    id integer NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    symbol character varying(20),
    category character varying(20) NOT NULL,
    decimal_places integer NOT NULL,
    is_base_unit boolean NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL
);

ALTER TABLE public.units_of_measure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.units_of_measure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.units_of_measure
    ADD CONSTRAINT pk_units_of_measure PRIMARY KEY (id);
