CREATE TABLE public.uom_conversions (
    id integer NOT NULL,
    from_uom_id integer NOT NULL,
    to_uom_id integer NOT NULL,
    conversion_factor numeric(18,8) NOT NULL,
    part_id integer,
    is_reversible boolean NOT NULL
);

ALTER TABLE public.uom_conversions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uom_conversions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.uom_conversions
    ADD CONSTRAINT pk_uom_conversions PRIMARY KEY (id);

ALTER TABLE ONLY public.uom_conversions
    ADD CONSTRAINT fk_uom_conversions_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.uom_conversions
    ADD CONSTRAINT fk_uom_conversions_units_of_measure_from_uom_id FOREIGN KEY (from_uom_id) REFERENCES public.units_of_measure(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.uom_conversions
    ADD CONSTRAINT fk_uom_conversions_units_of_measure_to_uom_id FOREIGN KEY (to_uom_id) REFERENCES public.units_of_measure(id) ON DELETE RESTRICT;
