CREATE TABLE public.user_sessions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    jti character varying(64) NOT NULL,
    user_device_id integer,
    auth_method character varying(30),
    ip_address character varying(45),
    user_agent character varying(500),
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_refreshed_at timestamp with time zone,
    revoked_at timestamp with time zone
);

ALTER TABLE public.user_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT pk_user_sessions PRIMARY KEY (id);

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT fk_user_sessions__user_devices_user_device_id FOREIGN KEY (user_device_id) REFERENCES public.user_devices(id) ON DELETE SET NULL;
