CREATE TABLE public.user_mfa_devices (
    id integer NOT NULL,
    user_id integer NOT NULL,
    device_type character varying(20) NOT NULL,
    encrypted_secret character varying(500) NOT NULL,
    device_name character varying(100),
    is_verified boolean NOT NULL,
    is_default boolean NOT NULL,
    last_used_at timestamp with time zone,
    failed_attempts integer NOT NULL,
    locked_until timestamp with time zone,
    credential_id character varying(500),
    public_key character varying(2000),
    sign_count bigint,
    phone_number character varying(20),
    email_address character varying(256),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.user_mfa_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_mfa_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_mfa_devices
    ADD CONSTRAINT pk_user_mfa_devices PRIMARY KEY (id);
