CREATE TABLE public.user_cloud_storage_links (
    id integer NOT NULL,
    user_id integer DEFAULT 0 NOT NULL,
    provider_id integer NOT NULL,
    external_user_id character varying(500),
    oauth_token_encrypted character varying(4000) NOT NULL,
    refresh_token_encrypted character varying(4000) NOT NULL,
    token_expires_at timestamp with time zone,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.user_cloud_storage_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_cloud_storage_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_cloud_storage_links
    ADD CONSTRAINT pk_user_cloud_storage_links PRIMARY KEY (id);

ALTER TABLE ONLY public.user_cloud_storage_links
    ADD CONSTRAINT fk_user_cloud_storage_links__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_cloud_storage_links
    ADD CONSTRAINT fk_user_cloud_storage_links_cloud_storage_providers_provider_id FOREIGN KEY (provider_id) REFERENCES public.cloud_storage_providers(id) ON DELETE CASCADE;
