CREATE TABLE public.user_scan_identifiers (
    id integer NOT NULL,
    user_id integer NOT NULL,
    identifier_type character varying(20) NOT NULL,
    identifier_value character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.user_scan_identifiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_scan_identifiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_scan_identifiers
    ADD CONSTRAINT pk_user_scan_identifiers PRIMARY KEY (id);

ALTER TABLE ONLY public.user_scan_identifiers
    ADD CONSTRAINT fk_user_scan_identifiers__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;
