CREATE TABLE public.user_integrations (
    id integer NOT NULL,
    user_id integer NOT NULL,
    category character varying(50) NOT NULL,
    provider_id character varying(100) NOT NULL,
    display_name character varying(200),
    encrypted_credentials character varying(4000) NOT NULL,
    is_active boolean NOT NULL,
    last_sync_at timestamp with time zone,
    last_error character varying(2000),
    config_json text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.user_integrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_integrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_integrations
    ADD CONSTRAINT pk_user_integrations PRIMARY KEY (id);
