CREATE TABLE public.user_devices (
    id integer NOT NULL,
    user_id integer,
    device_uuid character varying(64) NOT NULL,
    name character varying(200) NOT NULL,
    platform character varying(20) NOT NULL,
    os_version character varying(50),
    app_version character varying(30),
    is_shared boolean NOT NULL,
    enrolled_by_user_id integer NOT NULL,
    last_seen_at timestamp with time zone,
    revoked_at timestamp with time zone,
    revoked_by_user_id integer,
    is_flagged boolean NOT NULL,
    device_token_hash character varying(64),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.user_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT pk_user_devices PRIMARY KEY (id);

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT fk_user_devices__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;
