CREATE TABLE public.user_scan_devices (
    id integer NOT NULL,
    user_id integer NOT NULL,
    device_id character varying(200) NOT NULL,
    device_name character varying(200),
    paired_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL
);

ALTER TABLE public.user_scan_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_scan_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_scan_devices
    ADD CONSTRAINT pk_user_scan_devices PRIMARY KEY (id);

ALTER TABLE ONLY public.user_scan_devices
    ADD CONSTRAINT fk_user_scan_devices__asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE;
