CREATE TABLE public.vendor_contacts (
    id integer NOT NULL,
    vendor_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(200),
    phone character varying(50),
    mobile character varying(50),
    fax character varying(50),
    role character varying(50),
    is_primary boolean NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.vendor_contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_contacts
    ADD CONSTRAINT pk_vendor_contacts PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_contacts
    ADD CONSTRAINT fk_vendor_contacts__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE CASCADE;
