CREATE TABLE public.vendor_bank_accounts (
    id integer NOT NULL,
    vendor_id integer NOT NULL,
    nickname character varying(100) NOT NULL,
    account_type integer NOT NULL,
    routing_number_encrypted character varying(500) NOT NULL,
    account_number_encrypted character varying(500) NOT NULL,
    routing_number_masked character varying(20) NOT NULL,
    account_number_masked character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    changed_by_user_id integer NOT NULL,
    approved_by_user_id integer,
    approved_at timestamp with time zone,
    prenote_sent_at timestamp with time zone,
    verified_at timestamp with time zone,
    verified_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.vendor_bank_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_bank_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_bank_accounts
    ADD CONSTRAINT pk_vendor_bank_accounts PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_bank_accounts
    ADD CONSTRAINT fk_vendor_bank_accounts_vendor FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE RESTRICT;
