CREATE TABLE public.vendor_payments (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    payment_number character varying(30) NOT NULL,
    vendor_id integer NOT NULL,
    method integer NOT NULL,
    amount numeric(18,4) NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    reference_number character varying(100),
    notes character varying(2000),
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.vendor_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_payments
    ADD CONSTRAINT pk_vendor_payments PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_payments
    ADD CONSTRAINT fk_vendor_payments_vendor FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE RESTRICT;
