CREATE TABLE public.vendor_bills (
    id integer NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    bill_number character varying(30) NOT NULL,
    vendor_id integer NOT NULL,
    currency_id integer DEFAULT 1 NOT NULL,
    fx_rate numeric(18,8) DEFAULT 1.0 NOT NULL,
    vendor_invoice_number character varying(60),
    purchase_order_id integer,
    expense_id integer,
    status integer NOT NULL,
    bill_date timestamp with time zone NOT NULL,
    due_date timestamp with time zone NOT NULL,
    credit_terms integer,
    tax_amount numeric(18,4) NOT NULL,
    notes character varying(2000),
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.vendor_bills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_bills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_bills
    ADD CONSTRAINT pk_vendor_bills PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_bills
    ADD CONSTRAINT fk_vendor_bills_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.vendor_bills
    ADD CONSTRAINT fk_vendor_bills_expense FOREIGN KEY (expense_id) REFERENCES public.expenses(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.vendor_bills
    ADD CONSTRAINT fk_vendor_bills_po FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.vendor_bills
    ADD CONSTRAINT fk_vendor_bills_vendor FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE RESTRICT;
