CREATE TABLE public.vendor_bill_lines (
    id integer NOT NULL,
    vendor_bill_id integer NOT NULL,
    part_id integer,
    purchase_order_line_id integer,
    description character varying(500) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    line_number integer NOT NULL,
    job_id integer,
    account_determination_key character varying(64) NOT NULL
);

ALTER TABLE public.vendor_bill_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_bill_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_bill_lines
    ADD CONSTRAINT pk_vendor_bill_lines PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_bill_lines
    ADD CONSTRAINT fk_vendor_bill_lines_bill FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vendor_bill_lines
    ADD CONSTRAINT fk_vendor_bill_lines_job FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.vendor_bill_lines
    ADD CONSTRAINT fk_vendor_bill_lines_part FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.vendor_bill_lines
    ADD CONSTRAINT fk_vendor_bill_lines_po_line FOREIGN KEY (purchase_order_line_id) REFERENCES public.purchase_order_lines(id) ON DELETE SET NULL;
