CREATE TABLE public.vendors (
    id integer NOT NULL,
    company_name character varying(200) NOT NULL,
    contact_name character varying(200),
    email character varying(200),
    phone character varying(50),
    address character varying(500),
    city character varying(100),
    state character varying(100),
    zip_code character varying(20),
    country character varying(100),
    payment_terms character varying(200),
    notes character varying(2000),
    is_active boolean NOT NULL,
    deactivation_date timestamp with time zone,
    auto_po_mode character varying(20),
    min_order_amount numeric(18,4),
    off_tier_variance_pct numeric(6,2),
    external_id character varying(100),
    external_ref character varying(100),
    provider character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.vendors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT pk_vendors PRIMARY KEY (id);
