CREATE TABLE public.vendor_addresses (
    id integer NOT NULL,
    vendor_id integer NOT NULL,
    label character varying(100) NOT NULL,
    address_type integer NOT NULL,
    line1 character varying(200) NOT NULL,
    line2 character varying(200),
    city character varying(100) NOT NULL,
    state character varying(50) NOT NULL,
    postal_code character varying(20) NOT NULL,
    country character varying(10) NOT NULL,
    is_default boolean NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.vendor_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_addresses
    ADD CONSTRAINT pk_vendor_addresses PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_addresses
    ADD CONSTRAINT fk_vendor_addresses__vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE CASCADE;
