CREATE TABLE public.vendor_part_price_tiers (
    id integer NOT NULL,
    vendor_part_id integer NOT NULL,
    purchase_unit_id integer,
    min_quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    currency character varying(3) NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    notes character varying(2000),
    freight_included boolean DEFAULT false NOT NULL
);

ALTER TABLE public.vendor_part_price_tiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_part_price_tiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_part_price_tiers
    ADD CONSTRAINT pk_vendor_part_price_tiers PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_part_price_tiers
    ADD CONSTRAINT fk_vendor_part_price_tiers_part_purchase_units_purchase_unit_id FOREIGN KEY (purchase_unit_id) REFERENCES public.part_purchase_units(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.vendor_part_price_tiers
    ADD CONSTRAINT fk_vendor_part_price_tiers_vendor_parts_vendor_part_id FOREIGN KEY (vendor_part_id) REFERENCES public.vendor_parts(id) ON DELETE CASCADE;
