CREATE TABLE public.vendor_scorecards (
    id integer NOT NULL,
    vendor_id integer NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    total_purchase_orders integer NOT NULL,
    total_lines_received integer NOT NULL,
    on_time_deliveries integer NOT NULL,
    late_deliveries integer NOT NULL,
    early_deliveries integer NOT NULL,
    avg_lead_time_days numeric(18,2) NOT NULL,
    on_time_delivery_percent numeric(18,2) NOT NULL,
    total_inspected integer NOT NULL,
    total_accepted integer NOT NULL,
    total_rejected integer NOT NULL,
    total_ncrs integer NOT NULL,
    quality_acceptance_percent numeric(18,2) NOT NULL,
    total_spend numeric(18,2) NOT NULL,
    avg_price_variance_percent numeric(18,2) NOT NULL,
    cost_increase_count integer NOT NULL,
    quantity_shortages integer NOT NULL,
    quantity_overages integer NOT NULL,
    quantity_accuracy_percent numeric(18,2) NOT NULL,
    overall_score numeric(18,2) NOT NULL,
    grade character varying(10) NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    calculation_notes character varying(2000)
);

ALTER TABLE public.vendor_scorecards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_scorecards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_scorecards
    ADD CONSTRAINT pk_vendor_scorecards PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_scorecards
    ADD CONSTRAINT fk_vendor_scorecards_vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE CASCADE;
