CREATE TABLE public.vendor_parts (
    id integer NOT NULL,
    vendor_id integer NOT NULL,
    part_id integer NOT NULL,
    vendor_part_number character varying(100),
    manufacturer_name character varying(200),
    vendor_mpn character varying(100),
    lead_time_days integer,
    min_order_qty numeric(18,4),
    pack_size numeric(18,4),
    country_of_origin character varying(2),
    hts_code character varying(20),
    is_manufacturer boolean DEFAULT false NOT NULL,
    is_approved boolean NOT NULL,
    is_preferred boolean NOT NULL,
    certifications jsonb,
    last_quoted_date timestamp with time zone,
    currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    incoterm integer DEFAULT 0 NOT NULL,
    notes character varying(2000),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.vendor_parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_parts
    ADD CONSTRAINT pk_vendor_parts PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_parts
    ADD CONSTRAINT fk_vendor_parts_parts_part_id FOREIGN KEY (part_id) REFERENCES public.parts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vendor_parts
    ADD CONSTRAINT fk_vendor_parts_vendors_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE CASCADE;
