CREATE TABLE public.vendor_payment_applications (
    id integer NOT NULL,
    vendor_payment_id integer NOT NULL,
    vendor_bill_id integer NOT NULL,
    amount numeric(18,4) NOT NULL,
    settlement_fx_rate numeric(18,8) DEFAULT 1.0 NOT NULL
);

ALTER TABLE public.vendor_payment_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_payment_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.vendor_payment_applications
    ADD CONSTRAINT pk_vendor_payment_applications PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_payment_applications
    ADD CONSTRAINT fk_vpa_bill FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.vendor_payment_applications
    ADD CONSTRAINT fk_vpa_payment FOREIGN KEY (vendor_payment_id) REFERENCES public.vendor_payments(id) ON DELETE CASCADE;
