CREATE TABLE public.wbs_elements (
    id integer NOT NULL,
    project_id integer NOT NULL,
    parent_element_id integer,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    type integer NOT NULL,
    budget_labor numeric(18,2) NOT NULL,
    budget_material numeric(18,2) NOT NULL,
    budget_other numeric(18,2) NOT NULL,
    budget_total numeric(18,2) NOT NULL,
    actual_labor numeric(18,2) NOT NULL,
    actual_material numeric(18,2) NOT NULL,
    actual_other numeric(18,2) NOT NULL,
    actual_total numeric(18,2) NOT NULL,
    sort_order integer NOT NULL,
    planned_start date,
    planned_end date,
    percent_complete numeric(5,2),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.wbs_elements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wbs_elements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.wbs_elements
    ADD CONSTRAINT pk_wbs_elements PRIMARY KEY (id);

ALTER TABLE ONLY public.wbs_elements
    ADD CONSTRAINT fk_wbs_elements_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.wbs_elements
    ADD CONSTRAINT fk_wbs_elements_wbs_elements_parent_element_id FOREIGN KEY (parent_element_id) REFERENCES public.wbs_elements(id) ON DELETE RESTRICT;
