CREATE TABLE public.wbs_cost_entries (
    id integer NOT NULL,
    wbs_element_id integer NOT NULL,
    category integer NOT NULL,
    amount numeric(18,2) NOT NULL,
    description character varying(500),
    source_entity_type character varying(50),
    source_entity_id integer,
    entry_date timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.wbs_cost_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wbs_cost_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.wbs_cost_entries
    ADD CONSTRAINT pk_wbs_cost_entries PRIMARY KEY (id);

ALTER TABLE ONLY public.wbs_cost_entries
    ADD CONSTRAINT fk_wbs_cost_entries__wbs_elements_wbs_element_id FOREIGN KEY (wbs_element_id) REFERENCES public.wbs_elements(id) ON DELETE CASCADE;
