CREATE TABLE public.webhook_deliveries (
    id integer NOT NULL,
    subscription_id integer NOT NULL,
    event_type character varying(200) NOT NULL,
    payload_json text NOT NULL,
    status_code integer,
    response_body text,
    duration_ms numeric(18,2) NOT NULL,
    attempted_at timestamp with time zone NOT NULL,
    attempt_number integer NOT NULL,
    is_success boolean NOT NULL,
    error_message character varying(2000)
);

ALTER TABLE public.webhook_deliveries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.webhook_deliveries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.webhook_deliveries
    ADD CONSTRAINT pk_webhook_deliveries PRIMARY KEY (id);

ALTER TABLE ONLY public.webhook_deliveries
    ADD CONSTRAINT fk_webhook_deliveries__webhook_subscriptions_subscription_id FOREIGN KEY (subscription_id) REFERENCES public.webhook_subscriptions(id) ON DELETE CASCADE;
