CREATE TABLE public.webhook_subscriptions (
    id integer NOT NULL,
    url character varying(2000) NOT NULL,
    event_types_json text NOT NULL,
    encrypted_secret character varying(1000) NOT NULL,
    is_active boolean NOT NULL,
    failure_count integer NOT NULL,
    max_retries integer NOT NULL,
    last_delivered_at timestamp with time zone,
    last_failed_at timestamp with time zone,
    auto_disable_on_failure boolean NOT NULL,
    description character varying(500),
    headers_json text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.webhook_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.webhook_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.webhook_subscriptions
    ADD CONSTRAINT pk_webhook_subscriptions PRIMARY KEY (id);
