CREATE TABLE public.work_center_cost_rates (
    id integer NOT NULL,
    work_center_id integer NOT NULL,
    costing_period_id integer NOT NULL,
    labor_rate numeric(18,6) NOT NULL,
    labor_oh_rate numeric(18,6) NOT NULL,
    machine_rate numeric(18,6) NOT NULL,
    machine_oh_var_rate numeric(18,6) NOT NULL,
    machine_oh_fixed_rate numeric(18,6) NOT NULL,
    source_pool_ids text,
    frozen_at timestamp with time zone,
    frozen_by character varying(128),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.work_center_cost_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_center_cost_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.work_center_cost_rates
    ADD CONSTRAINT pk_work_center_cost_rates PRIMARY KEY (id);

ALTER TABLE ONLY public.work_center_cost_rates
    ADD CONSTRAINT fk_work_center_cost_rates__work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.work_center_cost_rates
    ADD CONSTRAINT fk_work_center_cost_rates__costing_periods_costing_period_id FOREIGN KEY (costing_period_id) REFERENCES public.costing_periods(id) ON DELETE CASCADE;

CREATE INDEX ix_work_center_cost_rates_work_center_id ON public.work_center_cost_rates (work_center_id);
CREATE INDEX ix_work_center_cost_rates_costing_period_id ON public.work_center_cost_rates (costing_period_id);
