CREATE TABLE public.work_center_shifts (
    id integer NOT NULL,
    work_center_id integer NOT NULL,
    shift_id integer NOT NULL,
    days_of_week integer NOT NULL
);

ALTER TABLE public.work_center_shifts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_center_shifts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.work_center_shifts
    ADD CONSTRAINT pk_work_center_shifts PRIMARY KEY (id);

ALTER TABLE ONLY public.work_center_shifts
    ADD CONSTRAINT fk_work_center_shifts_shifts_shift_id FOREIGN KEY (shift_id) REFERENCES public.shifts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.work_center_shifts
    ADD CONSTRAINT fk_work_center_shifts_work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE CASCADE;
