CREATE TABLE public.workflow_runs (
    id integer NOT NULL,
    entity_type character varying(64) NOT NULL,
    entity_id integer,
    draft_payload jsonb,
    definition_id character varying(64) NOT NULL,
    current_step_id character varying(64),
    mode character varying(16) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    started_by_user_id integer NOT NULL,
    completed_at timestamp with time zone,
    abandoned_at timestamp with time zone,
    abandoned_reason character varying(64),
    last_activity_at timestamp with time zone NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.workflow_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.workflow_runs
    ADD CONSTRAINT pk_workflow_runs PRIMARY KEY (id);
