CREATE TABLE public.work_centers (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(1000),
    company_location_id integer,
    asset_id integer,
    daily_capacity_hours numeric(8,2) NOT NULL,
    efficiency_percent numeric(5,2) NOT NULL,
    number_of_machines integer NOT NULL,
    labor_cost_per_hour numeric(18,4) NOT NULL,
    burden_rate_per_hour numeric(18,4) NOT NULL,
    ideal_cycle_time_seconds numeric(10,2),
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.work_centers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_centers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.work_centers
    ADD CONSTRAINT pk_work_centers PRIMARY KEY (id);

ALTER TABLE ONLY public.work_centers
    ADD CONSTRAINT fk_work_centers_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.work_centers
    ADD CONSTRAINT fk_work_centers_company_locations_company_location_id FOREIGN KEY (company_location_id) REFERENCES public.company_locations(id) ON DELETE SET NULL;
