CREATE TABLE public.work_center_calendars (
    id integer NOT NULL,
    work_center_id integer NOT NULL,
    date date NOT NULL,
    available_hours numeric(8,2) NOT NULL,
    reason character varying(200)
);

ALTER TABLE public.work_center_calendars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_center_calendars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.work_center_calendars
    ADD CONSTRAINT pk_work_center_calendars PRIMARY KEY (id);

ALTER TABLE ONLY public.work_center_calendars
    ADD CONSTRAINT fk_work_center_calendars_work_centers_work_center_id FOREIGN KEY (work_center_id) REFERENCES public.work_centers(id) ON DELETE CASCADE;
