CREATE TABLE public.workflow_definitions (
    id integer NOT NULL,
    definition_id character varying(64) NOT NULL,
    entity_type character varying(64) NOT NULL,
    default_mode character varying(16) NOT NULL,
    steps_json jsonb NOT NULL,
    express_template_component character varying(128),
    is_seed_data boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.workflow_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.workflow_definitions
    ADD CONSTRAINT pk_workflow_definitions PRIMARY KEY (id);
