CREATE TABLE public.working_calendars (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    time_zone character varying(64) NOT NULL,
    working_days_mask integer NOT NULL,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by text
);

ALTER TABLE public.working_calendars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.working_calendars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.working_calendars
    ADD CONSTRAINT pk_working_calendars PRIMARY KEY (id);
