using Forge.Db;
using Npgsql;
using Xunit;

namespace Forge.Db.Tests;

/// <summary>
/// Integration coverage of the dump → clean-rebuild import round trip against a real Postgres.
/// Skips silently unless <c>FORGE_DB_TEST_DSN</c> is set (same posture as
/// <see cref="DataSeedRunnerDbTests"/>); needs a superuser DSN (import suspends FK triggers).
/// Creates two uniquely-named throwaway DBs — source and target — and drops both in a finally.
/// </summary>
public class DataDumpDbTests
{
    private static string? Dsn => Environment.GetEnvironmentVariable("FORGE_DB_TEST_DSN");

    private const string Schema = """
        CREATE TABLE parents (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            is_deleted boolean NOT NULL DEFAULT false
        );
        CREATE TABLE children (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parent_id bigint NOT NULL REFERENCES parents(id),
            note text
        );
        CREATE TABLE junk_log (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payload text
        );
        """;

    [Fact]
    public void DumpThenImport_RoundTrips_Excludes_Scrubs_FixesSequences_AndFlagsOrphans()
    {
        if (string.IsNullOrWhiteSpace(Dsn)) return; // no DB configured — skip (see class summary)

        var baseConn = DbUrl.ToNpgsql(Dsn!);
        var admin = new NpgsqlConnectionStringBuilder(baseConn) { Database = "postgres" }.ConnectionString;
        var stamp = DateTime.UtcNow.Ticks;
        var sourceDb = $"forge_dump_src_{stamp}";
        var targetDb = $"forge_dump_dst_{stamp}";
        var source = new NpgsqlConnectionStringBuilder(baseConn) { Database = sourceDb }.ConnectionString;
        var target = new NpgsqlConnectionStringBuilder(baseConn) { Database = targetDb }.ConnectionString;
        var sourceUrl = WithDatabase(Dsn!, sourceDb);
        var targetUrl = WithDatabase(Dsn!, targetDb);

        var work = Path.Combine(Path.GetTempPath(), $"forge_dump_e2e_{stamp}");
        var dumpDir = Path.Combine(work, "dump");
        var repoRoot = Path.Combine(work, "repo"); // scrub/ lives here; no schema/ (fingerprint = null path)

        Exec(admin, $"CREATE DATABASE \"{sourceDb}\"");
        Exec(admin, $"CREATE DATABASE \"{targetDb}\"");
        try
        {
            Directory.CreateDirectory(Path.Combine(repoRoot, SchemaLayout.ScrubDir));
            File.WriteAllText(Path.Combine(repoRoot, SchemaLayout.ScrubDir, "0010-purge-soft-deleted.sql"),
                "DELETE FROM children WHERE parent_id IN (SELECT id FROM parents WHERE is_deleted);\n" +
                "DELETE FROM parents WHERE is_deleted;\n");

            Exec(source, Schema);
            Exec(source, """
                INSERT INTO parents (name, is_deleted) VALUES ('keep', false), ('garbage', true);
                INSERT INTO children (parent_id, note) VALUES (1, 'of keep'), (2, 'of garbage');
                INSERT INTO junk_log (payload) VALUES ('noise-1'), ('noise-2'), ('noise-3');
                """);
            Exec(target, Schema); // the freshly provisioned system

            // ── dump ─────────────────────────────────────────────────────────────────────────────
            var manifest = DataDumper.Run(repoRoot, sourceUrl, dumpDir);
            Assert.Equal(3, manifest.Tables.Count);
            Assert.Equal(2L, manifest.Tables.Single(t => t.Name == "parents").Rows);
            Assert.True(File.Exists(Path.Combine(dumpDir, "tables", "public.children.copy")));

            // ── import: junk_log excluded, scrub purges the soft-deleted family ──────────────────
            var result = DataImporter.Run(repoRoot, targetUrl, dumpDir,
                excludePatterns: ["junk_*"], skipScrub: false);

            Assert.Equal(2, result.Loaded.Count);
            Assert.Equal(["public.junk_log"], result.Excluded);
            Assert.Empty(result.Orphans); // scrub removed the child before its parent went away
            Assert.Equal(1L, ScalarLong(target, "SELECT count(*) FROM parents"));
            Assert.Equal(1L, ScalarLong(target, "SELECT count(*) FROM children"));
            Assert.Equal(0L, ScalarLong(target, "SELECT count(*) FROM junk_log"));

            // Sequences continue past the imported ids — a new insert must not collide.
            Exec(target, "INSERT INTO parents (name) VALUES ('after-import')");
            Assert.Equal(2L, ScalarLong(target, "SELECT count(*) FROM parents"));

            // ── orphan detection: excluding the parent table strands the children ────────────────
            var orphaned = DataImporter.Run(repoRoot, targetUrl, dumpDir,
                excludePatterns: ["parents", "junk_*"], skipScrub: true);
            var violation = Assert.Single(orphaned.Orphans);
            Assert.Equal("public.children", violation.ChildTable);
            Assert.Equal("public.parents", violation.ParentTable);
            Assert.Equal(2L, violation.Rows);
        }
        finally
        {
            TryExec(admin, $"DROP DATABASE IF EXISTS \"{sourceDb}\" WITH (FORCE)");
            TryExec(admin, $"DROP DATABASE IF EXISTS \"{targetDb}\" WITH (FORCE)");
            try { Directory.Delete(work, recursive: true); } catch { /* best effort */ }
        }
    }

    private static string WithDatabase(string url, string db)
    {
        var u = new UriBuilder(url) { Path = "/" + db };
        return u.Uri.ToString();
    }

    private static void Exec(string connString, string sql)
    {
        using var conn = new NpgsqlConnection(connString);
        conn.Open();
        using var cmd = new NpgsqlCommand(sql, conn);
        cmd.ExecuteNonQuery();
    }

    private static void TryExec(string connString, string sql)
    {
        try { Exec(connString, sql); } catch { /* teardown is best effort */ }
    }

    private static long ScalarLong(string connString, string sql)
    {
        using var conn = new NpgsqlConnection(connString);
        conn.Open();
        using var cmd = new NpgsqlCommand(sql, conn);
        return (long)cmd.ExecuteScalar()!;
    }
}
