-- forge-db apply plan (audit receipt — NOT replayable; schema/ + pg-schema-diff are the source of truth)
-- env: dev    captured: 20260620T073047Z

/*
Statement 0
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
CREATE TABLE "public"."document_set_links" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone,
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE),
	"document_set_id" integer NOT NULL,
	"entity_id" integer NOT NULL,
	"entity_type" character varying(50) COLLATE "pg_catalog"."default" NOT NULL,
	"deleted_by" text COLLATE "pg_catalog"."default"
);

/*
Statement 1
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
CREATE UNIQUE INDEX CONCURRENTLY pk_document_set_links ON public.document_set_links USING btree (id);

/*
Statement 2
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."document_set_links" ADD CONSTRAINT "pk_document_set_links" PRIMARY KEY USING INDEX "pk_document_set_links";

/*
Statement 3
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
CREATE INDEX CONCURRENTLY ix_document_set_links_document_set_id ON public.document_set_links USING btree (document_set_id);

/*
Statement 4
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
CREATE INDEX CONCURRENTLY ix_document_set_links_entity ON public.document_set_links USING btree (entity_type, entity_id);

/*
Statement 5
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
CREATE TABLE "public"."document_set_versions" (
	"created_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone,
	"updated_at" timestamp with time zone NOT NULL,
	"size" bigint NOT NULL,
	"effective_to" timestamp with time zone,
	"effective_from" timestamp with time zone NOT NULL,
	"created_by" integer,
	"version" integer NOT NULL,
	"document_set_id" integer NOT NULL,
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE),
	"is_archived" boolean DEFAULT false NOT NULL,
	"bucket_name" character varying(100) COLLATE "pg_catalog"."default" NOT NULL,
	"object_key" character varying(500) COLLATE "pg_catalog"."default" NOT NULL,
	"content_type" character varying(100) COLLATE "pg_catalog"."default" NOT NULL,
	"file_name" character varying(255) COLLATE "pg_catalog"."default" NOT NULL,
	"deleted_by" text COLLATE "pg_catalog"."default"
);

/*
Statement 6
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
CREATE UNIQUE INDEX CONCURRENTLY pk_document_set_versions ON public.document_set_versions USING btree (id);

/*
Statement 7
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."document_set_versions" ADD CONSTRAINT "pk_document_set_versions" PRIMARY KEY USING INDEX "pk_document_set_versions";

/*
Statement 8
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
CREATE INDEX CONCURRENTLY ix_document_set_versions_document_set_id ON public.document_set_versions USING btree (document_set_id);

/*
Statement 9
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
CREATE TABLE "public"."document_sets" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone,
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE),
	"created_by" integer,
	"kind" character varying(50) COLLATE "pg_catalog"."default" NOT NULL,
	"deleted_by" text COLLATE "pg_catalog"."default"
);

/*
Statement 10
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
CREATE UNIQUE INDEX CONCURRENTLY pk_document_sets ON public.document_sets USING btree (id);

/*
Statement 11
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."document_sets" ADD CONSTRAINT "pk_document_sets" PRIMARY KEY USING INDEX "pk_document_sets";

/*
Statement 12
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."document_set_links" ADD CONSTRAINT "fk_document_set_links_document_sets_document_set_id" FOREIGN KEY (document_set_id) REFERENCES document_sets(id) ON DELETE CASCADE NOT VALID;

/*
Statement 13
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."document_set_links" VALIDATE CONSTRAINT "fk_document_set_links_document_sets_document_set_id";

/*
Statement 14
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."document_set_versions" ADD CONSTRAINT "fk_document_set_versions_document_sets_document_set_id" FOREIGN KEY (document_set_id) REFERENCES document_sets(id) ON DELETE CASCADE NOT VALID;

/*
Statement 15
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."document_set_versions" VALIDATE CONSTRAINT "fk_document_set_versions_document_sets_document_set_id";

