-- 0010-identity-roles.sql — the 13 ASP.NET Identity roles.
--
-- Ported from forge-api SeedData.cs (roles[] + RoleManager create loop) via the compliance/roles
-- coop handoff (forge-api b9d34bdd, forge-db 32b59e8). RoleManager only writes plain deterministic
-- rows, so this is pure reference data. Natural key = normalized_name (= upper(name), matching
-- ASP.NET's ToUpperInvariant normalizer; spaces preserved). id is GENERATED BY DEFAULT AS IDENTITY,
-- so it is omitted here. gen_random_uuid() is core in PG13+ (pg17 target).
--
-- LeadIntake is a headless service-account role (bound to the seeded lead-intake system user,
-- authenticated via SystemApiKey) — still a normal asp_net_roles row.
--
-- Applied-once (forge_db.data_migration_log) AND idempotent: the NOT EXISTS guard skips existing
-- installs, which already hold these rows with their own concurrency stamps.

INSERT INTO asp_net_roles (name, normalized_name, concurrency_stamp)
SELECT r.name, upper(r.name), gen_random_uuid()::text
FROM (VALUES
  ('Admin'), ('Manager'), ('Engineer'), ('PM'), ('ProductionWorker'),
  ('OfficeManager'), ('Controller'), ('IT Admin'), ('Procurement'),
  ('Production Manager'), ('Production Planner'), ('LeadIntake'), ('ComplianceOfficer')
) AS r(name)
WHERE NOT EXISTS (
  SELECT 1 FROM asp_net_roles e WHERE e.normalized_name = upper(r.name));
