-- 0020-lead-sources.sql — website contact-form lead sources for the Tuyere relay.
--
-- Tuyere relays anonymous contact-form submissions from the public marketing sites into Forge
-- as leads (POST /api/v1/leads, LeadIntake role — see forge/docs/api-key-integrations.md §1.6).
-- The relay stamps leadSourceCode with the originating site's domain; CreateLead resolves that
-- against lead_sources.code to set leads.lead_source_id. Natural key = code (unique among live
-- rows via ix_lead_sources_code). quality_score starts at the LeadSource entity default (50);
-- RecomputeLeadSourceQualityJob recomputes it nightly from disposition outcomes. id is
-- GENERATED BY DEFAULT AS IDENTITY, so it is omitted here.
--
-- Applied-once (forge_db.data_migration_log) AND idempotent: the NOT EXISTS guard on code skips
-- installs that already created these sources via the lead-sources admin UI.

INSERT INTO lead_sources (name, description, code, quality_score, is_active, created_at, updated_at)
SELECT s.name, s.description, s.code, 50, true, now(), now()
FROM (VALUES
  ('ArmoryWorks Website', 'Contact-form submissions relayed from armoryworks.com by Tuyere', 'armoryworks.com'),
  ('NOM Website',         'Contact-form submissions relayed from nommeal.com by Tuyere',     'nommeal.com')
) AS s(name, description, code)
WHERE NOT EXISTS (
  SELECT 1 FROM lead_sources e WHERE e.code = s.code);
